-- AUTO-GENERATED by scripts/generate-brain-cutover-sql.mjs — do not edit by hand.
-- Brain cutover: DROP the 45 owner-private Brain tables from uwe.db.
--
-- !!! DESTRUCTIVE — Runbook stage 9 (docs/engineering/brain-migration-runbook.md) !!!
-- Apply ONLY after stages 3-8: a separate uwe-brain.db exists, every Brain
-- service is repointed to it, and integrity/restore/dry-run are green. Running
-- this before repointing DELETES Brain (it does not move it) and breaks all
-- Brain features. Take a verified backup of uwe.db first.
--
-- Apply (only when the above holds):
--   sqlite3 /var/lib/uwe/uwe.db < deploy/migrations/brain-cutover-drop.sql

PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS "mail_templates";
DROP TABLE IF EXISTS "mail_recipient_groups";
DROP TABLE IF EXISTS "mail_recipients";
DROP TABLE IF EXISTS "mail_message_logs";
DROP TABLE IF EXISTS "mail_accounts";
DROP TABLE IF EXISTS "mail_folders";
DROP TABLE IF EXISTS "mail_inbox_messages";
DROP TABLE IF EXISTS "mail_attachments";
DROP TABLE IF EXISTS "mail_priority_scores";
DROP TABLE IF EXISTS "mail_ai_actions";
DROP TABLE IF EXISTS "mail_unsubscribe_requests";
DROP TABLE IF EXISTS "mail_audit_log";
DROP TABLE IF EXISTS "mail_drafts";
DROP TABLE IF EXISTS "mail_rules";
DROP TABLE IF EXISTS "mail_vip_senders";
DROP TABLE IF EXISTS "capture_entries";
DROP TABLE IF EXISTS "personal_projects";
DROP TABLE IF EXISTS "project_steps";
DROP TABLE IF EXISTS "project_images";
DROP TABLE IF EXISTS "workshop_projects";
DROP TABLE IF EXISTS "workshop_paint_recipes";
DROP TABLE IF EXISTS "workshop_print_profiles";
DROP TABLE IF EXISTS "workshop_terrain_rentals";
DROP TABLE IF EXISTS "contract_expenses";
DROP TABLE IF EXISTS "hardware_devices";
DROP TABLE IF EXISTS "personal_brain_documents";
DROP TABLE IF EXISTS "personal_brain_chunks";
DROP TABLE IF EXISTS "personal_brain_facts";
DROP TABLE IF EXISTS "admin_entity_links";
DROP TABLE IF EXISTS "calendar_feeds";
DROP TABLE IF EXISTS "calendar_events";
DROP TABLE IF EXISTS "miniature_collection_items";
DROP TABLE IF EXISTS "document_templates";
DROP TABLE IF EXISTS "research_sessions";
DROP TABLE IF EXISTS "research_sources";
DROP TABLE IF EXISTS "recipes";
DROP TABLE IF EXISTS "recipe_ingredients";
DROP TABLE IF EXISTS "meal_plan_weeks";
DROP TABLE IF EXISTS "meal_plan_entries";
DROP TABLE IF EXISTS "shopping_lists";
DROP TABLE IF EXISTS "shopping_list_items";
DROP TABLE IF EXISTS "bring_connections";
DROP TABLE IF EXISTS "scan_documents";
DROP TABLE IF EXISTS "maintenance_tasks";
DROP TABLE IF EXISTS "pantry_items";

COMMIT;
PRAGMA foreign_keys = ON;
