import fs from "node:fs";
import path from "node:path";

import {
  DEFAULT_HOST,
  DEFAULT_PORTAL_PORT,
  DEFAULT_STUDIO_PORT,
} from "./constants.js";
import { toFileUrl } from "./paths.js";
import { generateAuthSecret } from "./secrets.js";
import type { InstallMode, InstallPaths, PortConfig } from "./types.js";
import { isPublicHost } from "./ports.js";

export interface EnvGenerationOptions {
  paths: InstallPaths;
  ports: PortConfig;
  mode: InstallMode;
  templatePath?: string;
  existingEnvPath?: string;
  dryRun?: boolean;
}

export function defaultPortConfig(): PortConfig {
  return {
    studioPort: DEFAULT_STUDIO_PORT,
    portalPort: DEFAULT_PORTAL_PORT,
    studioHost: DEFAULT_HOST,
    portalHost: DEFAULT_HOST,
  };
}

export function runDbSeedForMode(mode: InstallMode): "auto" | "false" {
  return mode === "dev" ? "auto" : "false";
}

export function buildStudioUrl(host: string, port: number): string {
  const normalizedHost = host === "0.0.0.0" ? "localhost" : host;
  return `http://${normalizedHost}:${port}`;
}

export function buildPortalUrl(host: string, port: number): string {
  return buildStudioUrl(host, port);
}

export function readEnvTemplate(templatePath: string): string {
  return fs.readFileSync(templatePath, "utf8");
}

export function parseEnvFile(content: string): Map<string, string> {
  const values = new Map<string, string>();

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const eq = trimmed.indexOf("=");
    if (eq === -1) {
      continue;
    }

    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    values.set(key, value);
  }

  return values;
}

export function upsertEnvValue(content: string, key: string, value: string): string {
  const lines = content.split(/\r?\n/);
  let replaced = false;

  const next = lines.map((line) => {
    if (line.startsWith(`${key}=`)) {
      replaced = true;
      return `${key}=${value}`;
    }

    return line;
  });

  if (!replaced) {
    next.push(`${key}=${value}`);
  }

  return `${next.join("\n").replace(/\n?$/, "\n")}`;
}

export function generateEnvContent(options: EnvGenerationOptions): {
  content: string;
  warnings: string[];
} {
  const warnings: string[] = [];
  const templatePath =
    options.templatePath ?? path.join(options.paths.app, ".env.example");

  let content: string;
  if (fs.existsSync(templatePath)) {
    content = readEnvTemplate(templatePath);
  } else if (options.existingEnvPath && fs.existsSync(options.existingEnvPath)) {
    content = readEnvTemplate(options.existingEnvPath);
  } else {
    content = [
      "# UWE environment generated by Windows installer",
      "AUTH_SECRET=",
      "RUN_DB_SEED=false",
      "STUDIO_PORT=3000",
      "NEXT_PUBLIC_STUDIO_URL=http://localhost:3000",
      "PORTAL_PORT=3001",
      "NEXT_PUBLIC_PORTAL_URL=http://localhost:3001",
      "DATABASE_URL=file:./data/uwe.db",
      "UPLOADS_DIR=./data/uploads",
      "EXPORTS_DIR=./exports",
      "BACKUPS_DIR=./data/backups",
      "",
    ].join("\n");
  }

  const dbPath = path.join(options.paths.data, "uwe.db");
  const authSecret = generateAuthSecret();

  content = upsertEnvValue(content, "AUTH_SECRET", authSecret);
  content = upsertEnvValue(content, "RUN_DB_SEED", runDbSeedForMode(options.mode));
  content = upsertEnvValue(content, "STUDIO_PORT", String(options.ports.studioPort));
  content = upsertEnvValue(content, "PORTAL_PORT", String(options.ports.portalPort));
  content = upsertEnvValue(
    content,
    "NEXT_PUBLIC_STUDIO_URL",
    buildStudioUrl(options.ports.studioHost, options.ports.studioPort),
  );
  content = upsertEnvValue(
    content,
    "NEXT_PUBLIC_PORTAL_URL",
    buildPortalUrl(options.ports.portalHost, options.ports.portalPort),
  );
  content = upsertEnvValue(content, "DATABASE_URL", toFileUrl(dbPath));
  content = upsertEnvValue(content, "UPLOADS_DIR", toFileUrl(options.paths.uploads));
  content = upsertEnvValue(content, "EXPORTS_DIR", toFileUrl(options.paths.exports));
  content = upsertEnvValue(content, "BACKUPS_DIR", toFileUrl(options.paths.backups));

  if (isPublicHost(options.ports.studioHost) || isPublicHost(options.ports.portalHost)) {
    warnings.push(
      "Studio/Portal are configured on a public host (0.0.0.0). UWE is intended for local or trusted networks only.",
    );
  }

  if (!options.dryRun) {
    fs.writeFileSync(options.paths.envFile, content, "utf8");
  }

  return { content, warnings };
}
