/**
 * SRD-Zauber Grad 5 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL5_SPELLS_A: Spell[] = [
  {
    key: "animate_objects",
    name: "Gegenstände beleben",
    nameEn: "Animate Objects",
    hook: "Gegenstände beleben: Grad 5, Verwandlung — Aktion, 36 Meter.",
    description: "Gegenstände beleben ist ein Zauber des 5. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: barde, hexenmeister, zauberer. Kernwirkung: Objects come to life at dein command. Choose up to ten nonmagical objects in Reichweite that are not being worn or carried. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "transmutation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "antilife_shell",
    name: "Antilebenshülle",
    nameEn: "Antilife Shell",
    hook: "Antilebenshülle: Grad 5, Abwehr — Aktion, Selbst.",
    description: "Antilebenshülle ist ein Zauber des 5. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: druide. Kernwirkung: Laut SRD: A shimmering barrier extends out from you in a 3 Meter radius and moves with you, remaining centered on you and hedging out Kreaturen other than undead and constructs. The barrier lasts für die Dauer.",
    source: SRD_SOURCE,
    level: 5,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "arcane_hand",
    name: "Arkane Hand",
    nameEn: "Arcane Hand",
    hook: "Arkane Hand: Grad 5, Hervorrufung — Aktion, 36 Meter.",
    description: "Arkane Hand ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: An eggshell and a snakeskin glove.). Listen: zauberer. Kernwirkung: Du create a Large hand of shimmering, translucent force in an unoccupied space that you can see in Reichweite. The hand lasts for the spell's duration, and it moves at dein command, mimicking the movements of dein own hand. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "eine Eierschale und ein Schlangenhaut-Handschuh" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "awaken",
    name: "Erwecken",
    nameEn: "Awaken",
    hook: "Erwecken: Grad 5, Verwandlung — 8 Stunden, Berührung.",
    description: "Erwecken ist ein Zauber des 5. Grades (Verwandlung). Wirkungszeit: 8 Stunden. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: An agate worth at least 1,000 gp, which the spell consumes.). Listen: druide, barde. Kernwirkung: After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant. The target must have either no Intelligence score or an Intelligence of 3 or less.",
    source: SRD_SOURCE,
    level: 5,
    school: "transmutation",
    castingTime: "8 Stunden",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Achat im Wert von mindestens 1000 KM, den der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde"],
  },
  {
    key: "cloudkill",
    name: "Wolkentod",
    nameEn: "Cloudkill",
    hook: "Wolkentod: Grad 5, Beschwörung — Aktion, 36 Meter.",
    description: "Wolkentod ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: druide, hexenmeister, zauberer. Kernwirkung: Du create a 6 Meter-radius sphere of poisonous, yellow-green fog centered on a point you choose in Reichweite. The fog spreads around corners. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "commune",
    name: "Kommunion",
    nameEn: "Commune",
    hook: "Kommunion: Grad 5, Erkenntnis — 1 Minute, Selbst.",
    description: "Kommunion ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: 1 Minute. Komponenten: V, G, M (Material: Incense and a vial of holy or unholy water.). Listen: kleriker. Kernwirkung: Du contact dein deity or a divine proxy and ask up to three questions that can be answered with a yes or no. Du must ask dein questions before the spell ends.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Weihrauch und eine Phiole Weih- oder Unheiliges Wasser" },
    duration: "1 Minute",
    concentration: false,
    ritual: true,
    lists: ["kleriker"],
  },
  {
    key: "commune_with_nature",
    name: "Mit der Natur kommunizieren",
    nameEn: "Commune with Nature",
    hook: "Mit der Natur kommunizieren: Grad 5, Erkenntnis — 1 Minute, Selbst.",
    description: "Mit der Natur kommunizieren ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G. Listen: druide, waldlaeufer. Kernwirkung: Du briefly become one with nature and gain knowledge of the surrounding territory. In the outdoors, the spell gives you knowledge of the land within 3 miles of you.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["druide", "waldlaeufer"],
  },
  {
    key: "cone_of_cold",
    name: "Kältekegel",
    nameEn: "Cone of Cold",
    hook: "Kältekegel: Grad 5, Hervorrufung — Aktion, Selbst.",
    description: "Kältekegel ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A small crystal or glass cone.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: A blast of cold air erupts from dein hands. Jede Kreatur in a 18 Meter cone muss einen constitution saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein kleiner Kristall- oder Glaskegel" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "conjure_elemental",
    name: "Elementar herbeizaubern",
    nameEn: "Conjure Elemental",
    hook: "Elementar herbeizaubern: Grad 5, Beschwörung — 1 Minute, 27 Meter.",
    description: "Elementar herbeizaubern ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: Burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water.). Listen: druide, zauberer. Kernwirkung: Du call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 3 Meter cube in Reichweite. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "brennender Weihrauch (Luft), weicher Lehm (Erde), Schwefel und Phosphor (Feuer) oder Wasser und Sand (Wasser)" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "contact_other_plane",
    name: "Andere Ebene kontaktieren",
    nameEn: "Contact Other Plane",
    hook: "Andere Ebene kontaktieren: Grad 5, Erkenntnis — 1 Minute, Selbst.",
    description: "Andere Ebene kontaktieren ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: 1 Minute. Komponenten: V. Listen: hexenpakt_magier, zauberer. Kernwirkung: Du mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane. Contacting this extraplanar intelligence can strain or even break dein mind.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: true,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "contagion",
    name: "Ansteckung",
    nameEn: "Contagion",
    hook: "Ansteckung: Grad 5, Nekromantie — Aktion, Berührung.",
    description: "Ansteckung ist ein Zauber des 5. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 7 Tage. Komponenten: V, G. Listen: kleriker, druide. Kernwirkung: Dein touch inflicts disease. Mache einen Nahkampf-Zauberangriff against a Kreatur within dein reach.",
    source: SRD_SOURCE,
    level: 5,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "7 Tage",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "creation",
    name: "Erschaffung",
    nameEn: "Creation",
    hook: "Erschaffung: Grad 5, Illusion — 1 Minute, 9 Meter.",
    description: "Erschaffung ist ein Zauber des 5. Grades (Illusion). Wirkungszeit: 1 Minute. Reichweite: 9 Meter. Dauer: besonders. Komponenten: V, G, M (Material: A tiny piece of matter of the same type of the item you plan to create.). Listen: hexenmeister, zauberer. Kernwirkung: Du pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within 'range': soft goods, rope, wood, or something similar. Du can also use this spell to create mineral objects such as stone, crystal, or metal. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "illusion",
    castingTime: "1 Minute",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein winziges Stück Materie derselben Art wie der zu erschaffende Gegenstand" },
    duration: "besonders",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "dispel_evil_and_good",
    name: "Böses und Gutes bannen",
    nameEn: "Dispel Evil and Good",
    hook: "Böses und Gutes bannen: Grad 5, Abwehr — Aktion, Selbst.",
    description: "Böses und Gutes bannen ist ein Zauber des 5. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: Holy water or powdered silver and iron.). Listen: kleriker. Kernwirkung: Shimmering energy surrounds and protects you from fey, undead, and Kreaturen originating from beyond the Material Plane. For the duration, celestials, elementals, fey, fiends, and undead have disadvantage on attack rolls against you.",
    source: SRD_SOURCE,
    level: 5,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Weihwasser oder pulverisiertes Silber und Eisen" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "dominate_person",
    name: "Person beherrschen",
    nameEn: "Dominate Person",
    hook: "Person beherrschen: Grad 5, Verzauberung — Aktion, 18 Meter.",
    description: "Person beherrschen ist ein Zauber des 5. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du attempt to beguile a humanoid that you can see in Reichweite. It muss einen wisdom saving throw bestehen or be charmed by you für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "dream",
    name: "Traum",
    nameEn: "Dream",
    hook: "Traum: Grad 5, Illusion — 1 Minute, besonders.",
    description: "Traum ist ein Zauber des 5. Grades (Illusion). Wirkungszeit: 1 Minute. Reichweite: besonders. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird.). Listen: druide, barde, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: This spell shapes a Kreatur's dreams. Choose a Kreatur known to you as the target of this spell.",
    source: SRD_SOURCE,
    level: 5,
    school: "illusion",
    castingTime: "1 Minute",
    range: "besonders",
    components: { verbal: true, somatic: true, material: "eine Handvoll Sand, ein Tupfer Tinte und eine Feder eines schlafenden Vogels" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "flame_strike",
    name: "Flammenstoß",
    nameEn: "Flame Strike",
    hook: "Flammenstoß: Grad 5, Hervorrufung — Aktion, 18 Meter.",
    description: "Flammenstoß ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Pinch of sulfur.). Listen: kleriker, hexenpakt_magier. Kernwirkung: Laut SRD: A vertical column of divine fire roars down from the heavens in a location you specify. Jede Kreatur in a 3 Meter-radius, 12 Meter-high cylinder centered on a point in Reichweite muss einen dexterity saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Schwefel" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier"],
  },
  {
    key: "geas",
    name: "Banngebot",
    nameEn: "Geas",
    hook: "Banngebot: Grad 5, Verzauberung — 1 Minute, 18 Meter.",
    description: "Banngebot ist ein Zauber des 5. Grades (Verzauberung). Wirkungszeit: 1 Minute. Reichweite: 18 Meter. Dauer: 30 Tage. Komponenten: V. Listen: kleriker, druide, barde, zauberer. Kernwirkung: Du place a magical command on a Kreatur that you can see in Reichweite, forcing it to carry out some service or refrain from some action or course of activity as you decide. If the Kreatur can understand you, it muss einen wisdom saving throw bestehen or become charmed by you für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "enchantment",
    castingTime: "1 Minute",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "30 Tage",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "zauberer"],
  },
  {
    key: "greater_restoration",
    name: "Höhere Wiederherstellung",
    nameEn: "Greater Restoration",
    hook: "Höhere Wiederherstellung: Grad 5, Abwehr — Aktion, Berührung.",
    description: "Höhere Wiederherstellung ist ein Zauber des 5. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Diamond dust worth at least 100gp, which the spell consumes.). Listen: kleriker, druide, barde. Kernwirkung: Du imbue a Kreatur you touch with positive energy to undo a debilitating effect. Du can reduce the target's exhaustion level by one, or end one of the following effects on the target: - One effect that charmed or petrified the target - One curse, including the target's attunement to a cursed magic item - Any reduction to one of the target's ability scores - One effect reducing the target's hit point maximum.",
    source: SRD_SOURCE,
    level: 5,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Diamantstaub im Wert von mindestens 100 KM, den der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde"],
  },
  {
    key: "hallow",
    name: "Weihen",
    nameEn: "Hallow",
    hook: "Weihen: Grad 5, Hervorrufung — 24 Stunden, Berührung.",
    description: "Weihen ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: 24 Stunden. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Herbs, oils, and incense worth at least 1,000 gp, which the spell consumes.). Listen: kleriker, hexenpakt_magier. Kernwirkung: Du berührst a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 18 Meter, and the spell fails if the radius includes an area already under the effect a hallow spell.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "24 Stunden",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Kräuter, Öle und Weihrauch im Wert von mindestens 1000 KM, die der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier"],
  },
  {
    key: "hold_monster",
    name: "Monster festhalten",
    nameEn: "Hold Monster",
    hook: "Monster festhalten: Grad 5, Verzauberung — Aktion, 27 Meter.",
    description: "Monster festhalten ist ein Zauber des 5. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A small piece of iron.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: Choose a Kreatur you can see in Reichweite. The target must make a saving throw of Wisdom or be paralyzed für die Dauer of the spell. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "enchantment",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "ein kleines Stück Eisen" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "insect_plague",
    name: "Insektenplage",
    nameEn: "Insect Plague",
    hook: "Insektenplage: Grad 5, Beschwörung — Aktion, 90 Meter.",
    description: "Insektenplage ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 90 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A few grains of sugar, some kernels of grain, and a smear of fat.). Listen: kleriker, druide, hexenmeister. Kernwirkung: Swarming, biting locusts fill a 6 Meter-radius sphere centered on a point you choose in Reichweite. The sphere spreads around corners. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "Aktion",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "einige Zuckerkörner, einige Getreidekörner und ein Fettfleck" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister"],
  },
  {
    key: "legend_lore",
    name: "Legendenkunde",
    nameEn: "Legend Lore",
    hook: "Legendenkunde: Grad 5, Erkenntnis — 10 Minuten, Selbst.",
    description: "Legendenkunde ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: 10 Minuten. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Incense worth 250 inches that fate consumes and four sticks of ivory worth 50 gp each.). Listen: kleriker, barde, zauberer. Kernwirkung: Name or describe a person, place, or object. The spell brings to dein mind a brief summary of the significant lore about the thing you named.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "10 Minuten",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Weihrauch im Wert von 250 KM, den der Zauber verbraucht, und vier Elfenbeinstäbe im Wert von je 50 KM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "zauberer"],
  },
  {
    key: "mass_cure_wounds",
    name: "Massenheilung der Wunden",
    nameEn: "Mass Cure Wounds",
    hook: "Massenheilung der Wunden: Grad 5, Beschwörung — Aktion, 18 Meter.",
    description: "Massenheilung der Wunden ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, barde. Kernwirkung: Laut SRD: A wave of healing energy washes out from a point of dein choice in Reichweite. Choose up to six Kreaturen in a 9 Meter-radius sphere centered on that point. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde"],
  },
  {
    key: "mislead",
    name: "Irreführung",
    nameEn: "Mislead",
    hook: "Irreführung: Grad 5, Illusion — Aktion, Selbst.",
    description: "Irreführung ist ein Zauber des 5. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: G. Listen: barde, zauberer. Kernwirkung: Du become invisible at the same time that an illusory double of you appears where you are standing. The double lasts für die Dauer, but the invisibility ends if you attack or cast a spell.",
    source: SRD_SOURCE,
    level: 5,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: false, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "modify_memory",
    name: "Erinnerung verändern",
    nameEn: "Modify Memory",
    hook: "Erinnerung verändern: Grad 5, Verzauberung — Aktion, 9 Meter.",
    description: "Erinnerung verändern ist ein Zauber des 5. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, barde, zauberer. Kernwirkung: Du attempt to reshape another Kreatur's memories. One Kreatur that you can see muss einen wisdom saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "zauberer"],
  },
  {
    key: "passwall",
    name: "Wanddurchgang",
    nameEn: "Passwall",
    hook: "Wanddurchgang: Grad 5, Verwandlung — Aktion, 9 Meter.",
    description: "Wanddurchgang ist ein Zauber des 5. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 1 Stunde. Komponenten: V, G, M (Material: A pinch of sesame seeds.). Listen: druide, zauberer. Kernwirkung: Laut SRD: A passage appears at a point of dein choice that you can see on a wooden, plaster, or stone surface (such as a wall, a ceiling, or a floor) in Reichweite, and lasts für die Dauer. Du choose the opening's dimensions: up to 1.5 Meter wide, 2.4 Meter tall, and 6 Meter deep.",
    source: SRD_SOURCE,
    level: 5,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Sesamsamen" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "planar_binding",
    name: "Ebenenbindung",
    nameEn: "Planar Binding",
    hook: "Ebenenbindung: Grad 5, Abwehr — 1 Stunde, 18 Meter.",
    description: "Ebenenbindung ist ein Zauber des 5. Grades (Abwehr). Wirkungszeit: 1 Stunde. Reichweite: 18 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A jewel worth at least 1,000 gp, which the spell consumes.). Listen: kleriker, druide, barde, zauberer. Kernwirkung: With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to dein service. The Kreatur must be in Reichweite for the entire casting of the spell. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 5,
    school: "abjuration",
    castingTime: "1 Stunde",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Juwel im Wert von mindestens 1000 KM, das der Zauber verbraucht" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "zauberer"],
  },
  {
    key: "raise_dead",
    name: "Tote erwecken",
    nameEn: "Raise Dead",
    hook: "Tote erwecken: Grad 5, Nekromantie — 1 Stunde, Berührung.",
    description: "Tote erwecken ist ein Zauber des 5. Grades (Nekromantie). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A diamond worth at least 500gp, which the spell consumes.). Listen: kleriker, barde. Kernwirkung: Du return a dead Kreatur you touch to life, provided that it has been dead no longer than 10 days. If the Kreatur's soul is both willing and at liberty to rejoin the body, the Kreatur returns to life with 1 hit point.",
    source: SRD_SOURCE,
    level: 5,
    school: "necromancy",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Diamant im Wert von mindestens 500 KM, den der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde"],
  },
];
