/**
 * SRD-Zauber Grad 8 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL8_SPELLS: Spell[] = [
  {
    key: "animal_shapes",
    name: "Tiergestalten",
    nameEn: "Animal Shapes",
    hook: "Tiergestalten: Grad 8, Verwandlung — Aktion, 9 Meter.",
    description: "Tiergestalten ist ein Zauber des 8. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 24 Stunden. Komponenten: V, G. Listen: druide. Kernwirkung: Dein magic turns others into beasts. Choose any number of willing Kreaturen that you can see in Reichweite.",
    source: SRD_SOURCE,
    level: 8,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 24 Stunden",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "antimagic_field",
    name: "Antimagiefeld",
    nameEn: "Antimagic Field",
    hook: "Antimagiefeld: Grad 8, Abwehr — Aktion, Selbst.",
    description: "Antimagiefeld ist ein Zauber des 8. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A pinch of powdered iron or iron filings.). Listen: kleriker, zauberer. Kernwirkung: Laut SRD: A 3 Meter-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse.",
    source: SRD_SOURCE,
    level: 8,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Prise Eisenpulver oder Eisenspäne" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "antipathysympathy",
    name: "Antipathie/Sympathie",
    nameEn: "Antipathy/Sympathy",
    hook: "Antipathie/Sympathie: Grad 8, Verzauberung — 1 Stunde, 18 Meter.",
    description: "Antipathie/Sympathie ist ein Zauber des 8. Grades (Verzauberung). Wirkungszeit: 1 Stunde. Reichweite: 18 Meter. Dauer: 10 Tage. Komponenten: V, G, M (Material: Either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect.). Listen: druide, zauberer. Kernwirkung: Laut SRD: This spell attracts or repels Kreaturen of dein choice. Du target something in Reichweite, either a Huge or smaller object or Kreatur or an area that is no larger than a 60 Meter cube.",
    source: SRD_SOURCE,
    level: 8,
    school: "enchantment",
    castingTime: "1 Stunde",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "entweder ein in Essig getränktes Alaunstück (Antipathie) oder ein Tropfen Honig (Sympathie)" },
    duration: "10 Tage",
    concentration: false,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "clone",
    name: "Klon",
    nameEn: "Clone",
    hook: "Klon: Grad 8, Nekromantie — 1 Stunde, Berührung.",
    description: "Klon ist ein Zauber des 8. Grades (Nekromantie). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold a Medium creature, such as a huge urn, coffin, mud-filled cyst in the ground, or crystal container filled with salt water.). Listen: zauberer. Kernwirkung: Laut SRD: This spell grows an inert duplicate of a living Kreatur as a safeguard against death. This clone forms inside a sealed vessel and grows to full size and maturity after 120 days; you can also choose to have the clone be a younger version of the same Kreatur.",
    source: SRD_SOURCE,
    level: 8,
    school: "necromancy",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Diamant im Wert von mindestens 1000 KM und mindestens 1 Kubikzoll Fleisch der zu klonenden Kreatur (werden verbraucht), sowie ein verschließbares Gefäß im Wert von mindestens 2000 KM, groß genug für eine mittelgroße Kreatur" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "control_weather",
    name: "Wetter kontrollieren",
    nameEn: "Control Weather",
    hook: "Wetter kontrollieren: Grad 8, Verwandlung — 10 Minuten, Selbst.",
    description: "Wetter kontrollieren ist ein Zauber des 8. Grades (Verwandlung). Wirkungszeit: 10 Minuten. Reichweite: Selbst. Dauer: Konzentration, bis zu 8 Stunden. Komponenten: V, G, M (Material: Burning incense and bits of earth and wood mixed in water.). Listen: kleriker, druide, zauberer. Kernwirkung: Du take control of the weather within 5 miles of you für die Dauer. Du must be outdoors to cast this spell.",
    source: SRD_SOURCE,
    level: 8,
    school: "transmutation",
    castingTime: "10 Minuten",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "brennender Weihrauch sowie Erde und Holzstücke, in Wasser gemischt" },
    duration: "Konzentration, bis zu 8 Stunden",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "zauberer"],
  },
  {
    key: "demiplane",
    name: "Halbebene",
    nameEn: "Demiplane",
    hook: "Halbebene: Grad 8, Beschwörung — Aktion, 18 Meter.",
    description: "Halbebene ist ein Zauber des 8. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 1 Stunde. Komponenten: G. Listen: hexenpakt_magier, zauberer. Kernwirkung: Du create a shadowy door on a flat solid surface that you can see in Reichweite. The door is large enough to allow Medium Kreaturen to pass through unhindered.",
    source: SRD_SOURCE,
    level: 8,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: false, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "dominate_monster",
    name: "Monster beherrschen",
    nameEn: "Dominate Monster",
    hook: "Monster beherrschen: Grad 8, Verzauberung — Aktion, 18 Meter.",
    description: "Monster beherrschen ist ein Zauber des 8. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du attempt to beguile a Kreatur that you can see in Reichweite. It muss einen wisdom saving throw bestehen or be charmed by you für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 8,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "earthquake",
    name: "Erdbeben",
    nameEn: "Earthquake",
    hook: "Erdbeben: Grad 8, Hervorrufung — Aktion, 150 Meter.",
    description: "Erdbeben ist ein Zauber des 8. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 150 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A pinch of dirt, a piece of rock, and a lump of clay.). Listen: kleriker, druide, hexenmeister. Kernwirkung: Du create a seismic disturbance at a point on the ground that you can see in Reichweite. For the duration, an intense tremor rips through the ground in a 30 Meter-radius circle centered on that point and shakes Kreaturen and structures in contact with the ground in that area.",
    source: SRD_SOURCE,
    level: 8,
    school: "evocation",
    castingTime: "Aktion",
    range: "150 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Erde, ein Stück Gestein und ein Lehmklumpen" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister"],
  },
  {
    key: "feeblemind",
    name: "Geistesschwäche",
    nameEn: "Feeblemind",
    hook: "Geistesschwäche: Grad 8, Verzauberung — Aktion, 45 Meter.",
    description: "Geistesschwäche ist ein Zauber des 8. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A handful of clay, crystal, glass, or mineral spheres.). Listen: druide, barde, hexenpakt_magier, zauberer. Kernwirkung: Du blast the mind of a Kreatur that you can see in Reichweite, attempting to shatter its intellect and personality. The target takes 4d6 psychischen Schaden and must make an intelligence saving throw.",
    source: SRD_SOURCE,
    level: 8,
    school: "enchantment",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "eine Handvoll Lehm-, Kristall-, Glas- oder Mineralkugeln" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "glibness",
    name: "Zungenfertigkeit",
    nameEn: "Glibness",
    hook: "Zungenfertigkeit: Grad 8, Verwandlung — Aktion, Selbst.",
    description: "Zungenfertigkeit ist ein Zauber des 8. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 1 Stunde. Komponenten: V. Listen: barde, hexenpakt_magier. Kernwirkung: Laut SRD: Until the spell ends, when you make a Charisma check, you can replace the number you roll with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.",
    source: SRD_SOURCE,
    level: 8,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenpakt_magier"],
  },
  {
    key: "holy_aura",
    name: "Heilige Aura",
    nameEn: "Holy Aura",
    hook: "Heilige Aura: Grad 8, Abwehr — Aktion, Selbst.",
    description: "Heilige Aura ist ein Zauber des 8. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A tiny reliquary worth at least 1,000gp containing a sacred relic, such as a scrap of cloth from a saint's robe or a piece of parchment from a religious text.). Listen: kleriker. Kernwirkung: Divine light washes out from you and coalesces in a soft radiance in a 9 Meter radius around you. Creatures of dein choice in that radius when you cast this spell shed dim light in a 1.5 Meter radius and have advantage on all saving throws, and other Kreaturen have disadvantage on attack rolls against them bis der Zauber endet.",
    source: SRD_SOURCE,
    level: 8,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein winziges Reliquiar im Wert von mindestens 1000 KM mit einer heiligen Reliquie, z. B. Stoff einer Heiligenrobe oder Pergament aus einem religiösen Text" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "incendiary_cloud",
    name: "Brandwolke",
    nameEn: "Incendiary Cloud",
    hook: "Brandwolke: Grad 8, Beschwörung — Aktion, 45 Meter.",
    description: "Brandwolke ist ein Zauber des 8. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: hexenmeister, zauberer. Kernwirkung: Laut SRD: A swirling cloud of smoke shot through with white-hot embers appears in a 6 Meter-radius sphere centered on a point in Reichweite. The cloud spreads around corners and is heavily obscured.",
    source: SRD_SOURCE,
    level: 8,
    school: "conjuration",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "maze",
    name: "Labyrinth",
    nameEn: "Maze",
    hook: "Labyrinth: Grad 8, Beschwörung — Aktion, 18 Meter.",
    description: "Labyrinth ist ein Zauber des 8. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: zauberer. Kernwirkung: Du banish a Kreatur that you can see in Reichweite into a labyrinthine demiplane. The target remains there für die Dauer or until it escapes the maze.",
    source: SRD_SOURCE,
    level: 8,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "mind_blank",
    name: "Gedankenleere",
    nameEn: "Mind Blank",
    hook: "Gedankenleere: Grad 8, Abwehr — Aktion, Berührung.",
    description: "Gedankenleere ist ein Zauber des 8. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 24 Stunden. Komponenten: V, G. Listen: barde, zauberer. Kernwirkung: Laut SRD: Until the spell ends, one willing Kreatur you touch is immune to psychischen Schaden, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition. The spell even foils wish spells and spells or effects of similar power used to affect the target's mind or to gain information about the target.",
    source: SRD_SOURCE,
    level: 8,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "power_word_stun",
    name: "Machtwort Betäuben",
    nameEn: "Power Word Stun",
    hook: "Machtwort Betäuben: Grad 8, Verzauberung — Aktion, 18 Meter.",
    description: "Machtwort Betäuben ist ein Zauber des 8. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du speak a word of power that can overwhelm the mind of one Kreatur you can see in Reichweite, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned.",
    source: SRD_SOURCE,
    level: 8,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "sunburst",
    name: "Sonnenexplosion",
    nameEn: "Sunburst",
    hook: "Sonnenexplosion: Grad 8, Hervorrufung — Aktion, 45 Meter.",
    description: "Sonnenexplosion ist ein Zauber des 8. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Fire and a piece of sunstone.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Brilliant sunlight flashes in a 18 Meter radius centered on a point you choose in Reichweite. Jede Kreatur in that light muss einen constitution saving throw bestehen.",
    source: SRD_SOURCE,
    level: 8,
    school: "evocation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "Feuer und ein Stück Sonnenstein" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
];
