/**
 * SRD-Zauber Grad 3 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL3_SPELLS_A: Spell[] = [
  {
    key: "animate_dead",
    name: "Untote beleben",
    nameEn: "Animate Dead",
    hook: "Untote beleben: Grad 3, Nekromantie — 1 Minute, 3 Meter.",
    description: "Untote beleben ist ein Zauber des 3. Grades (Nekromantie). Wirkungszeit: 1 Minute. Reichweite: 3 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A drop of blood, a piece of flesh, and a pinch of bone dust.). Listen: kleriker, zauberer. Kernwirkung: Laut SRD: This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid in Reichweite. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "necromancy",
    castingTime: "1 Minute",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Blut, ein Stück Fleisch und eine Prise Knochenstaub" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "beacon_of_hope",
    name: "Leuchtfeuer der Hoffnung",
    nameEn: "Beacon of Hope",
    hook: "Leuchtfeuer der Hoffnung: Grad 3, Abwehr — Aktion, 9 Meter.",
    description: "Leuchtfeuer der Hoffnung ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker. Kernwirkung: Laut SRD: This spell bestows hope and vitality. Choose any number of Kreaturen in Reichweite.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "bestow_curse",
    name: "Fluch verleihen",
    nameEn: "Bestow Curse",
    hook: "Fluch verleihen: Grad 3, Nekromantie — Aktion, Berührung.",
    description: "Fluch verleihen ist ein Zauber des 3. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, barde, zauberer. Kernwirkung: Du berührst eine Kreatur, and that Kreatur muss einen wisdom saving throw bestehen or become cursed für die Dauer of the spell. When you cast this spell, choose the nature of the curse from the following options: - Choose one ability score. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "zauberer"],
  },
  {
    key: "blink",
    name: "Blinzeln",
    nameEn: "Blink",
    hook: "Blinzeln: Grad 3, Verwandlung — Aktion, Selbst.",
    description: "Blinzeln ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 1 Minute. Komponenten: V, G. Listen: kleriker, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Roll a d20 at the end of each of dein turns für die Dauer of the spell. On a roll of 11 or higher, you vanish from dein current plane of existence and appear in the Ethereal Plane (the spell fails and the casting is wasted if you were already on that plane).",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "call_lightning",
    name: "Blitz herbeirufen",
    nameEn: "Call Lightning",
    hook: "Blitz herbeirufen: Grad 3, Beschwörung — Aktion, 36 Meter.",
    description: "Blitz herbeirufen ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: kleriker, druide. Kernwirkung: Laut SRD: A storm cloud appears in the shape of a cylinder that is 3 Meter tall with a 18 Meter radius, centered on a point you can see 30 Meter directly above you. The spell fails if you can't see a point in the air where the storm cloud could appear (for example, if you are in a room that can't accommodate the cloud). Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "clairvoyance",
    name: "Hellsehen",
    nameEn: "Clairvoyance",
    hook: "Hellsehen: Grad 3, Erkenntnis — 10 Minuten, 1 mile.",
    description: "Hellsehen ist ein Zauber des 3. Grades (Erkenntnis). Wirkungszeit: 10 Minuten. Reichweite: 1 mile. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A focus worth at least 100gp, either a jeweled horn for hearing or a glass eye for seeing.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du create an invisible sensor in Reichweite in a location familiar to you (a place you have visited or seen before) or in an obvious location that is unfamiliar to you (such as behind a door, around a corner, or in a grove of trees). The sensor remains in place für die Dauer, and it can't be attacked or otherwise interacted with.",
    source: SRD_SOURCE,
    level: 3,
    school: "divination",
    castingTime: "10 Minuten",
    range: "1 mile",
    components: { verbal: true, somatic: true, material: "ein Fokus im Wert von mindestens 100 KM — juwelenbesetztes Horn (Hören) oder Glasauge (Sehen)" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "conjure_animals",
    name: "Tiere herbeizaubern",
    nameEn: "Conjure Animals",
    hook: "Tiere herbeizaubern: Grad 3, Beschwörung — Aktion, 18 Meter.",
    description: "Tiere herbeizaubern ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: druide, waldlaeufer. Kernwirkung: Du summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see in Reichweite. Choose one of the following options for what appears: - One beast of challenge rating 2 or lower - Two beasts of challenge rating 1 or lower - Four beasts of challenge rating 1/2 or lower - Eight beasts of challenge rating 1/4 or lower - Each beast is also considered fey, and it disappears when it drops to 0 hit points or when the spell ends. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "waldlaeufer"],
  },
  {
    key: "counterspell",
    name: "Gegenzauber",
    nameEn: "Counterspell",
    hook: "Gegenzauber: Grad 3, Abwehr — 1 reaction, which you take when you see a creature within 60 feet of you casting a spell, 18 Meter.",
    description: "Gegenzauber ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: 1 reaction, which you take when you see a creature within 60 feet of you casting a spell. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: G. Listen: hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du attempt to interrupt a Kreatur in the process of casting a spell. If the Kreatur is casting a spell of 3rd level or lower, its spell fails and has no effect. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "1 reaction, which you take when you see a creature within 60 feet of you casting a spell",
    range: "18 Meter",
    components: { verbal: false, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "create_food_and_water",
    name: "Nahrung und Wasser erschaffen",
    nameEn: "Create Food and Water",
    hook: "Nahrung und Wasser erschaffen: Grad 3, Beschwörung — Aktion, 9 Meter.",
    description: "Nahrung und Wasser erschaffen ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide. Kernwirkung: Du create 45 pounds of food and 30 gallons of water on the ground or in containers in Reichweite, enough to sustain up to fifteen humanoids or five steeds for 24 hours. The food is bland but nourishing, and spoils if uneaten after 24 hours.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "daylight",
    name: "Tageslicht",
    nameEn: "Daylight",
    hook: "Tageslicht: Grad 3, Hervorrufung — Aktion, 18 Meter.",
    description: "Tageslicht ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 1 Stunde. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer, hexenmeister. Kernwirkung: Laut SRD: A 18 Meter-radius sphere of light spreads out from a point you choose in Reichweite. The sphere is bright light and sheds dim light for an additional 18 Meter.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "hexenmeister"],
  },
  {
    key: "dispel_magic",
    name: "Magie bannen",
    nameEn: "Dispel Magic",
    hook: "Magie bannen: Grad 3, Abwehr — Aktion, 36 Meter.",
    description: "Magie bannen ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: Choose one Kreatur, object, or magical effect in Reichweite. Any spell of 3rd level or lower on the target ends. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "fear",
    name: "Furcht",
    nameEn: "Fear",
    hook: "Furcht: Grad 3, Illusion — Aktion, Selbst.",
    description: "Furcht ist ein Zauber des 3. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A white feather or the heart of a hen.). Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du project a phantasmal image of a Kreatur's worst fears. Jede Kreatur in a 9 Meter cone muss einen wisdom saving throw bestehen or drop whatever it is holding and become frightened für die Dauer.",
    source: SRD_SOURCE,
    level: 3,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine weiße Feder oder ein Hühnerherz" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "fireball",
    name: "Feuerball",
    nameEn: "Fireball",
    hook: "Feuerball: Grad 3, Hervorrufung — Aktion, 45 Meter.",
    description: "Feuerball ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A tiny ball of bat guano and sulfur.). Listen: hexenmeister, zauberer. Kernwirkung: Laut SRD: A bright streak flashes from dein pointing finger to a point you choose in Reichweite and then blossoms with a low roar into an explosion of flame. Jede Kreatur in a 6 Meter-radius sphere centered on that point muss einen dexterity saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "eine winzige Kugel aus Fledermausguano und Schwefel" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "fly",
    name: "Fliegen",
    nameEn: "Fly",
    hook: "Fliegen: Grad 3, Verwandlung — Aktion, Berührung.",
    description: "Fliegen ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A wing feather from any bird.). Listen: hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du berührst eine willige Kreatur. The target gains a flying speed of 18 Meter für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Schwungfeder eines beliebigen Vogels" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "gaseous_form",
    name: "Gasförmige Gestalt",
    nameEn: "Gaseous Form",
    hook: "Gasförmige Gestalt: Grad 3, Verwandlung — Aktion, Berührung.",
    description: "Gasförmige Gestalt ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A bit of gauze and a wisp of smoke.). Listen: druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du transform a willing Kreatur you touch, along with everything it's wearing and carrying, into a misty cloud für die Dauer. The spell ends if the Kreatur drops to 0 hit points.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Stück Gaze und ein Rauchwölkchen" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "glyph_of_warding",
    name: "Glyphe der Bewachung",
    nameEn: "Glyph of Warding",
    hook: "Glyphe der Bewachung: Grad 3, Abwehr — 1 Stunde, Berührung.",
    description: "Glyphe der Bewachung ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Incense and powdered diamond worth at least 200 gp, which the spell consumes.). Listen: kleriker, barde, zauberer. Kernwirkung: Laut SRD: When you cast this spell, you inscribe a glyph that harms other Kreaturen, either upon a surface (such as a table or a section of floor or wall) or within an object that can be closed (such as a book, a scroll, or a treasure chest) to conceal the glyph. If you choose a surface, the glyph can cover an area of the surface no larger than 3 Meter in diameter. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Weihrauch und Diamantpulver im Wert von mindestens 200 KM, die der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "zauberer"],
  },
  {
    key: "haste",
    name: "Eile",
    nameEn: "Haste",
    hook: "Eile: Grad 3, Verwandlung — Aktion, 9 Meter.",
    description: "Eile ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A shaving of licorice root.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: Choose a willing Kreatur that you can see in Reichweite. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on dexterity saving throws, and it gains an additional action on each of its turns.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Raspel Süßholzwurzel" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "hypnotic_pattern",
    name: "Hypnotisches Muster",
    nameEn: "Hypnotic Pattern",
    hook: "Hypnotisches Muster: Grad 3, Illusion — Aktion, 36 Meter.",
    description: "Hypnotisches Muster ist ein Zauber des 3. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: G, M (Material: A glowing stick of incense or a crystal vial filled with phosphorescent material.). Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du create a twisting pattern of colors that weaves through the air inside a 9 Meter cube in Reichweite. The pattern appears for a moment and vanishes.",
    source: SRD_SOURCE,
    level: 3,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: false, somatic: true, material: "ein glühendes Räucherstäbchen oder eine Kristallphiole mit phosphoreszierendem Material" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "lightning_bolt",
    name: "Blitzstrahl",
    nameEn: "Lightning Bolt",
    hook: "Blitzstrahl: Grad 3, Hervorrufung — Aktion, Selbst.",
    description: "Blitzstrahl ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A bit of fur and a rod of amber, crystal, or glass.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: A stroke of lightning forming a line 30 Meter long and 1.5 Meter wide blasts out from you in a direction you choose. Jede Kreatur in the line muss einen dexterity saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "etwas Fell und ein Stab aus Bernstein, Kristall oder Glas" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "magic_circle",
    name: "Magischer Kreis",
    nameEn: "Magic Circle",
    hook: "Magischer Kreis: Grad 3, Abwehr — 1 Minute, 3 Meter.",
    description: "Magischer Kreis ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: 1 Minute. Reichweite: 3 Meter. Dauer: 1 Stunde. Komponenten: V, G, M (Material: Holy water or powdered silver and iron worth at least 100 gp, which the spell consumes.). Listen: kleriker, hexenpakt_magier, zauberer. Kernwirkung: Du create a 10-­--foot-­--radius, 20-­--foot-­--tall cylinder of magical energy centered on a point on the ground that you can see in Reichweite. Glowing runes appear wherever the cylinder intersects with the floor or other surface. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "1 Minute",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "Weihwasser oder pulverisiertes Silber und Eisen im Wert von mindestens 100 KM, die der Zauber verbraucht" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "major_image",
    name: "Mächtiges Trugbild",
    nameEn: "Major Image",
    hook: "Mächtiges Trugbild: Grad 3, Illusion — Aktion, 36 Meter.",
    description: "Mächtiges Trugbild ist ein Zauber des 3. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A bit of fleece.). Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du create the image of an object, a Kreatur, or some other visible phenomenon that is no larger than a 6 Meter cube. The image appears at a spot that you can see in Reichweite and lasts für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein Stück Vlies" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "mass_healing_word",
    name: "Massenheilendes Wort",
    nameEn: "Mass Healing Word",
    hook: "Massenheilendes Wort: Grad 3, Hervorrufung — Bonusaktion, 18 Meter.",
    description: "Massenheilendes Wort ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Bonusaktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: kleriker. Kernwirkung: As you call out words of restoration, up to six Kreaturen of dein choice that you can see in Reichweite regain hit points equal to 1d4 + dein spellcasting ability modifier. This spell has no effect on undead or constructs. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Bonusaktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "meld_into_stone",
    name: "In Stein verschmelzen",
    nameEn: "Meld into Stone",
    hook: "In Stein verschmelzen: Grad 3, Verwandlung — Aktion, Berührung.",
    description: "In Stein verschmelzen ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 8 Stunden. Komponenten: V, G. Listen: kleriker, druide. Kernwirkung: Du step into a stone object or surface large enough to fully contain dein body, melding yourself and all the equipment you carry with the stone für die Dauer. Using dein movement, you step into the stone at a point you can touch.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "8 Stunden",
    concentration: false,
    ritual: true,
    lists: ["kleriker", "druide"],
  },
  {
    key: "nondetection",
    name: "Unauffindbarkeit",
    nameEn: "Nondetection",
    hook: "Unauffindbarkeit: Grad 3, Abwehr — Aktion, Berührung.",
    description: "Unauffindbarkeit ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A pinch of diamond dust worth 25 gp sprinkled over the target, which the spell consumes.). Listen: kleriker, waldlaeufer, barde, zauberer. Kernwirkung: For the duration, you hide a target that you touch from divination magic. The target can be a willing Kreatur or a place or an object no larger than 3 Meter in any dimension.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Prise Diamantstaub im Wert von 25 KM, über das Ziel gestreut, die der Zauber verbraucht" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "waldlaeufer", "barde", "zauberer"],
  },
  {
    key: "phantom_steed",
    name: "Phantomross",
    nameEn: "Phantom Steed",
    hook: "Phantomross: Grad 3, Illusion — 1 Minute, 9 Meter.",
    description: "Phantomross ist ein Zauber des 3. Grades (Illusion). Wirkungszeit: 1 Minute. Reichweite: 9 Meter. Dauer: 1 Stunde. Komponenten: V, G. Listen: zauberer. Kernwirkung: Laut SRD: A Large quasi-real, horselike Kreatur appears on the ground in an unoccupied space of dein choice in Reichweite. Du decide the Kreatur's appearance, but it is equipped with a saddle, bit, and bridle.",
    source: SRD_SOURCE,
    level: 3,
    school: "illusion",
    castingTime: "1 Minute",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["zauberer"],
  },
  {
    key: "plant_growth",
    name: "Pflanzenwachstum",
    nameEn: "Plant Growth",
    hook: "Pflanzenwachstum: Grad 3, Verwandlung — Aktion, 45 Meter.",
    description: "Pflanzenwachstum ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer, barde, hexenpakt_magier. Kernwirkung: Laut SRD: This spell channels vitality into plants within a specific area. There are two possible uses for the spell, granting either immediate or long-term benefits.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "barde", "hexenpakt_magier"],
  },
  {
    key: "protection_from_energy",
    name: "Schutz vor Energie",
    nameEn: "Protection from Energy",
    hook: "Schutz vor Energie: Grad 3, Abwehr — Aktion, Berührung.",
    description: "Schutz vor Energie ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer, hexenmeister, zauberer. Kernwirkung: For the duration, the willing Kreatur you touch has resistance to one Schaden type of dein choice: acid, cold, fire, lightning, or thunder.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "hexenmeister", "zauberer"],
  },
  {
    key: "remove_curse",
    name: "Fluch aufheben",
    nameEn: "Remove Curse",
    hook: "Fluch aufheben: Grad 3, Abwehr — Aktion, Berührung.",
    description: "Fluch aufheben ist ein Zauber des 3. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, hexenpakt_magier, zauberer. Kernwirkung: At dein touch, all curses affecting one Kreatur or object end. If the object is a cursed magic item, its curse remains, but the spell breaks its owner's attunement to the object so it can be removed or discarded.",
    source: SRD_SOURCE,
    level: 3,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier", "zauberer"],
  },
];
