/**
 * SRD-Zauber Grad 3 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL3_SPELLS_B: Spell[] = [
  {
    key: "revivify",
    name: "Wiederbeleben",
    nameEn: "Revivify",
    hook: "Wiederbeleben: Grad 3, Beschwörung — Aktion, Berührung.",
    description: "Wiederbeleben ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Diamonds worth 300gp, which the spell consumes.). Listen: kleriker. Kernwirkung: Du berührst eine Kreatur that has died within the last minute. That Kreatur returns to life with 1 hit point.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Diamanten im Wert von 300 KM, die der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "sending",
    name: "Botschaft",
    nameEn: "Sending",
    hook: "Botschaft: Grad 3, Hervorrufung — Aktion, Unlimited.",
    description: "Botschaft ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Unlimited. Dauer: 1 Runde. Komponenten: V, G, M (Material: A short piece of fine copper wire.). Listen: kleriker, barde, hexenpakt_magier, zauberer. Kernwirkung: Du send a short message of twenty-five words or less to a Kreatur with which you are familiar. The Kreatur hears the message in its mind, recognizes you as the sender if it knows you, and can answer in a like manner immediately.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Aktion",
    range: "Unlimited",
    components: { verbal: true, somatic: true, material: "ein kurzes Stück feiner Kupferdraht" },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "sleet_storm",
    name: "Graupelsturm",
    nameEn: "Sleet Storm",
    hook: "Graupelsturm: Grad 3, Beschwörung — Aktion, 45 Meter.",
    description: "Graupelsturm ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A pinch of dust and a few drops of water.). Listen: kleriker, druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: Until the spell ends, freezing rain and sleet fall in a 6 Meter-tall cylinder with a 12 Meter radius centered on a point you choose in Reichweite. The area is heavily obscured, and exposed flames in the area are doused.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Staub und ein paar Tropfen Wasser" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "slow",
    name: "Verlangsamen",
    nameEn: "Slow",
    hook: "Verlangsamen: Grad 3, Verwandlung — Aktion, 36 Meter.",
    description: "Verlangsamen ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A drop of molasses.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Du alter time around up to six Kreaturen of dein choice in a 12 Meter cube in Reichweite. Each target muss einen wisdom saving throw bestehen or be affected by this spell für die Dauer.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Melasse" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "speak_with_dead",
    name: "Mit Toten sprechen",
    nameEn: "Speak with Dead",
    hook: "Mit Toten sprechen: Grad 3, Nekromantie — Aktion, 3 Meter.",
    description: "Mit Toten sprechen ist ein Zauber des 3. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 3 Meter. Dauer: 10 Minuten. Komponenten: V, G, M (Material: Burning incense.). Listen: kleriker, barde. Kernwirkung: Du grant the semblance of life and intelligence to a corpse of dein choice in Reichweite, allowing it to answer the questions you pose. The corpse must still have a mouth and can't be undead.",
    source: SRD_SOURCE,
    level: 3,
    school: "necromancy",
    castingTime: "Aktion",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "brennender Weihrauch" },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde"],
  },
  {
    key: "speak_with_plants",
    name: "Mit Pflanzen sprechen",
    nameEn: "Speak with Plants",
    hook: "Mit Pflanzen sprechen: Grad 3, Verwandlung — Aktion, Selbst.",
    description: "Mit Pflanzen sprechen ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 10 Minuten. Komponenten: V, G. Listen: druide, waldlaeufer, barde. Kernwirkung: Du imbue plants within 9 Meter of you with limited sentience and animation, giving them the ability to communicate with you and follow dein simple commands. Du can question plants about events in the spell's area within the past day, gaining information about Kreaturen that have passed, weather, and other circumstances.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["druide", "waldlaeufer", "barde"],
  },
  {
    key: "spirit_guardians",
    name: "Geistige Wächter",
    nameEn: "Spirit Guardians",
    hook: "Geistige Wächter: Grad 3, Beschwörung — Aktion, Selbst.",
    description: "Geistige Wächter ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A holy symbol.). Listen: kleriker. Kernwirkung: Du call forth spirits to protect you. They flit around you to a distance of 4.5 Meter für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein heiliges Symbol" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "stinking_cloud",
    name: "Stinkende Wolke",
    nameEn: "Stinking Cloud",
    hook: "Stinkende Wolke: Grad 3, Beschwörung — Aktion, 27 Meter.",
    description: "Stinkende Wolke ist ein Zauber des 3. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A rotten egg or several skunk cabbage leaves.). Listen: druide, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du create a 6 Meter-radius sphere of yellow, nauseating gas centered on a point in Reichweite. The cloud spreads around corners, and its area is heavily obscured.",
    source: SRD_SOURCE,
    level: 3,
    school: "conjuration",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "ein faules Ei oder mehrere Stinkkohlblätter" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "tiny_hut",
    name: "Winzige Hütte",
    nameEn: "Tiny Hut",
    hook: "Winzige Hütte: Grad 3, Hervorrufung — 1 Minute, Selbst.",
    description: "Winzige Hütte ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A small crystal bead.). Listen: barde, zauberer. Kernwirkung: Laut SRD: A 3 Meter-radius immobile dome of force springs into existence around and above you and remains stationary für die Dauer. The spell ends if you leave its area.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine kleine Kristallperle" },
    duration: "8 Stunden",
    concentration: false,
    ritual: true,
    lists: ["barde", "zauberer"],
  },
  {
    key: "tongues",
    name: "Zungen",
    nameEn: "Tongues",
    hook: "Zungen: Grad 3, Erkenntnis — Aktion, Berührung.",
    description: "Zungen ist ein Zauber des 3. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, M (Material: A small clay model of a ziggurat.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: This spell grants the Kreatur you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any Kreatur that knows at least one language and can hear the target understands what it says.",
    source: SRD_SOURCE,
    level: 3,
    school: "divination",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: false, material: "ein kleines Lehmmodell einer Ziggurat" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "vampiric_touch",
    name: "Vampirberührung",
    nameEn: "Vampiric Touch",
    hook: "Vampirberührung: Grad 3, Nekromantie — Aktion, Selbst.",
    description: "Vampirberührung ist ein Zauber des 3. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: The touch of dein shadow-wreathed hand can siphon life force from others to heal dein wounds. Mache einen Nahkampf-Zauberangriff against a Kreatur within dein reach. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 3,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "water_breathing",
    name: "Wasseratmung",
    nameEn: "Water Breathing",
    hook: "Wasseratmung: Grad 3, Verwandlung — Aktion, 9 Meter.",
    description: "Wasseratmung ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A short piece of reed or straw.). Listen: druide, waldlaeufer, hexenmeister, zauberer. Kernwirkung: Laut SRD: This spell gives a maximum of ten willing Kreaturen in Reichweite and you can see, the ability to breathe underwater until the end of its term. Affected Kreaturen also retain their normal breathing pattern.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein kurzes Stück Schilf oder Stroh" },
    duration: "24 Stunden",
    concentration: false,
    ritual: true,
    lists: ["druide", "waldlaeufer", "hexenmeister", "zauberer"],
  },
  {
    key: "water_walk",
    name: "Wasserwandeln",
    nameEn: "Water Walk",
    hook: "Wasserwandeln: Grad 3, Verwandlung — Aktion, 9 Meter.",
    description: "Wasserwandeln ist ein Zauber des 3. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 1 Stunde. Komponenten: V, G, M. Listen: kleriker, druide, waldlaeufer, hexenmeister. Kernwirkung: Laut SRD: This spell grants the ability to move across any liquid surface-such as water, acid, mud, snow, quicksand, or lava-as if it were harmless solid ground (Kreaturen crossing molten lava can still take Schaden from the heat). Up to ten willing Kreaturen you can see in Reichweite gain this ability für die Dauer.",
    source: SRD_SOURCE,
    level: 3,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["kleriker", "druide", "waldlaeufer", "hexenmeister"],
  },
  {
    key: "wind_wall",
    name: "Windwall",
    nameEn: "Wind Wall",
    hook: "Windwall: Grad 3, Hervorrufung — Aktion, 36 Meter.",
    description: "Windwall ist ein Zauber des 3. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A tiny fan and a feather of exotic origin.). Listen: kleriker, druide, waldlaeufer. Kernwirkung: Laut SRD: A wall of strong wind rises from the ground at a point you choose in Reichweite. Du can make the wall up to 15 Meter long, 4.5 Meter high, and 0.3 Meter thick.",
    source: SRD_SOURCE,
    level: 3,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein winziger Fächer und eine exotische Feder" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
];
