/**
 * SRD-Zauber Grad 2 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL2_SPELLS_A: Spell[] = [
  {
    key: "acid_arrow",
    name: "Säurepfeil",
    nameEn: "Acid Arrow",
    hook: "Säurepfeil: Grad 2, Hervorrufung — Aktion, 27 Meter.",
    description: "Säurepfeil ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Powdered rhubarb leaf and an adder's stomach.). Listen: druide, zauberer. Kernwirkung: Ein schimmernder grüner Pfeil rast auf ein Ziel in Reichweite zu und zerplatzt in einem Säureschauer. Mache einen Fernkampf-Zauberangriff gegen das Ziel. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "pulverisiertes Rhabarberblatt und ein Ottermagen" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "aid",
    name: "Unterstützung",
    nameEn: "Aid",
    hook: "Unterstützung: Grad 2, Abwehr — Aktion, 9 Meter.",
    description: "Unterstützung ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A tiny strip of white cloth.). Listen: kleriker. Kernwirkung: Dein spell bolsters dein allies with toughness and resolve. Choose up to three Kreaturen in Reichweite. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein winziger Streifen weißes Tuch" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "alter_self",
    name: "Gestalt verändern",
    nameEn: "Alter Self",
    hook: "Gestalt verändern: Grad 2, Verwandlung — Aktion, Selbst.",
    description: "Gestalt verändern ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: hexenmeister, zauberer. Kernwirkung: Du nimmst eine andere Gestalt an. When you cast the spell, choose one of the following options, the effects of which last für die Dauer of the spell.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "animal_messenger",
    name: "Tierbote",
    nameEn: "Animal Messenger",
    hook: "Tierbote: Grad 2, Verzauberung — Aktion, 9 Meter.",
    description: "Tierbote ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A morsel of food.). Listen: druide, waldlaeufer, barde. Kernwirkung: By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see in Reichweite, such as a squirrel, a blue jay, or a bat. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Happen Nahrung" },
    duration: "24 Stunden",
    concentration: false,
    ritual: true,
    lists: ["druide", "waldlaeufer", "barde"],
  },
  {
    key: "arcane_lock",
    name: "Arkanes Schloss",
    nameEn: "Arcane Lock",
    hook: "Arkanes Schloss: Grad 2, Abwehr — Aktion, Berührung.",
    description: "Arkanes Schloss ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Gold dust worth at least 25gp, which the spell consumes.). Listen: zauberer. Kernwirkung: Du berührst a closed door, window, gate, chest, or other entryway, and it becomes locked für die Dauer. Du and the Kreaturen you designate when you cast this spell can open the object normally.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Goldstaub im Wert von mindestens 25 KM, den der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "arcanists_magic_aura",
    name: "Arkane Aura",
    nameEn: "Arcanist's Magic Aura",
    hook: "Arkane Aura: Grad 2, Illusion — Aktion, Berührung.",
    description: "Arkane Aura ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A small square of silk.). Listen: zauberer. Kernwirkung: Du legst eine Illusion auf eine berührte Kreatur oder einen berührten Gegenstand, sodass Wahrsagezauber falsche Informationen darüber enthüllen. The target can be a willing Kreatur or an object that isn't being carried or worn by another Kreatur.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein kleines Seidenquadrat" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "augury",
    name: "Vorzeichen",
    nameEn: "Augury",
    hook: "Vorzeichen: Grad 2, Erkenntnis — 1 Minute, Selbst.",
    description: "Vorzeichen ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Specially marked sticks, bones, or similar tokens worth at least 25gp.). Listen: kleriker. Kernwirkung: By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The DM chooses from the following possible omens: - Weal, for good results - Woe, for bad results - Weal and woe, for both good and bad results - Nothing, for results that aren't especially good or bad The spell doesn't take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "besonders markierte Stäbe, Knochen oder ähnliche Token im Wert von mindestens 25 KM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["kleriker"],
  },
  {
    key: "barkskin",
    name: "Baumrinde",
    nameEn: "Barkskin",
    hook: "Baumrinde: Grad 2, Verwandlung — Aktion, Berührung.",
    description: "Baumrinde ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A handful of oak bark.). Listen: kleriker, druide, waldlaeufer. Kernwirkung: Du berührst eine willige Kreatur. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 16, regardless of what kind of armor it is wearing.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Handvoll Eichenrinde" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "blindnessdeafness",
    name: "Blindheit/Taubheit",
    nameEn: "Blindness/Deafness",
    hook: "Blindheit/Taubheit: Grad 2, Nekromantie — Aktion, 9 Meter.",
    description: "Blindheit/Taubheit ist ein Zauber des 2. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 1 Minute. Komponenten: V. Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du kannst einen Gegner blenden oder taub machen. Choose one Kreatur that you can see in Reichweite to make a constitution saving throw. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "necromancy",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "blur",
    name: "Verschwimmen",
    nameEn: "Blur",
    hook: "Verschwimmen: Grad 2, Illusion — Aktion, Selbst.",
    description: "Verschwimmen ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V. Listen: druide, hexenmeister, zauberer. Kernwirkung: Dein body becomes blurred, shifting and wavering to all who can see you. For the duration, any Kreatur has disadvantage on attack rolls against you.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "branding_smite",
    name: "Brandmal-Bannschlag",
    nameEn: "Branding Smite",
    hook: "Brandmal-Bannschlag: Grad 2, Hervorrufung — Bonusaktion, Selbst.",
    description: "Brandmal-Bannschlag ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Bonusaktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V. Listen: paladin. Kernwirkung: Laut SRD: The next time you hit a Kreatur with a weapon attack before this spell ends, the weapon gleams with astral radiance as you strike. The attack deals an extra 2d6 gleißenden Schaden to the target, which becomes visible if it's invisible, and the target sheds dim light in a 5-­--foot radius and can't become invisible bis der Zauber endet. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["paladin"],
  },
  {
    key: "calm_emotions",
    name: "Gefühle beruhigen",
    nameEn: "Calm Emotions",
    hook: "Gefühle beruhigen: Grad 2, Verzauberung — Aktion, 18 Meter.",
    description: "Gefühle beruhigen ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, barde, hexenpakt_magier. Kernwirkung: Du versuchst, starke Emotionen in einer Gruppe von Personen zu unterdrücken. Each humanoid in a 6 Meter-radius sphere centered on a point you choose in Reichweite muss einen charisma saving throw bestehen; a Kreatur can choose to fail this saving throw if it wishes.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "hexenpakt_magier"],
  },
  {
    key: "continual_flame",
    name: "Ewige Flamme",
    nameEn: "Continual Flame",
    hook: "Ewige Flamme: Grad 2, Hervorrufung — Aktion, Berührung.",
    description: "Ewige Flamme ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Ruby dust worth 50 gp, which the spell consumes.). Listen: kleriker, zauberer. Kernwirkung: Eine Flamme so hell wie eine Fackel entspringt einem von dir berührten Gegenstand. The effect looks like a regular flame, but it creates no heat and doesn't use oxygen.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Rubinpulver im Wert von 50 KM, das der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "darkness",
    name: "Dunkelheit",
    nameEn: "Darkness",
    hook: "Dunkelheit: Grad 2, Hervorrufung — Aktion, 18 Meter.",
    description: "Dunkelheit ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, M (Material: Bat fur and a drop of pitch or piece of coal.). Listen: druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Magical darkness spreads from a point you choose in Reichweite to fill a 4.5 Meter-radius sphere für die Dauer. The darkness spreads around corners.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: "Fledermausfell und ein Tropfen Pech oder ein Stück Kohle" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "darkvision",
    name: "Dunkelsicht",
    nameEn: "Darkvision",
    hook: "Dunkelsicht: Grad 2, Verwandlung — Aktion, Berührung.",
    description: "Dunkelsicht ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 8 Stunden. Komponenten: V, G, M (Material: Either a pinch of dried carrot or an agate.). Listen: druide, waldlaeufer, hexenmeister, zauberer. Kernwirkung: Du berührst eine willige Kreatur to grant it the ability to see in the dark. For the duration, that Kreatur has darkvision out to a range of 18 Meter.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "entweder eine Prise getrocknete Karotte oder ein Achat" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["druide", "waldlaeufer", "hexenmeister", "zauberer"],
  },
  {
    key: "detect_thoughts",
    name: "Gedanken wahrnehmen",
    nameEn: "Detect Thoughts",
    hook: "Gedanken wahrnehmen: Grad 2, Erkenntnis — Aktion, Selbst.",
    description: "Gedanken wahrnehmen ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A copper coin.). Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: For the duration, you can read the thoughts of certain Kreaturen. When you cast the spell and as dein action on each turn bis der Zauber endet, you can focus dein mind on any one Kreatur that you can see within 9 Meter of you.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Kupfermünze" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "enhance_ability",
    name: "Attribut verbessern",
    nameEn: "Enhance Ability",
    hook: "Attribut verbessern: Grad 2, Verwandlung — Aktion, Berührung.",
    description: "Attribut verbessern ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: Fur or a feather from a beast.). Listen: kleriker, druide, barde, hexenmeister. Kernwirkung: Du berührst eine Kreatur and bestow upon it a magical enhancement. Choose one of the following effects; the target gains that effect bis der Zauber endet. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Fell oder eine Feder eines Biests" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenmeister"],
  },
  {
    key: "enlargereduce",
    name: "Vergrößern/Verkleinern",
    nameEn: "Enlarge/Reduce",
    hook: "Vergrößern/Verkleinern: Grad 2, Verwandlung — Aktion, 9 Meter.",
    description: "Vergrößern/Verkleinern ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A pinch iron powder.). Listen: hexenmeister, zauberer. Kernwirkung: Du lässt eine Kreatur oder einen Gegenstand in Sicht und Reichweite für die Dauer wachsen oder schrumpfen. Choose either a Kreatur or an object that is neither worn nor carried.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Eisenpulver" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "enthrall",
    name: "Fesseln",
    nameEn: "Enthrall",
    hook: "Fesseln: Grad 2, Verzauberung — Aktion, 18 Meter.",
    description: "Fesseln ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 1 Minute. Komponenten: V, G. Listen: barde, hexenpakt_magier. Kernwirkung: Du webst ablenkende Worte; gewählte Kreaturen in Reichweite, die dich sehen und hören können, müssen einen Wisdom saving throw bestehen. Any Kreatur that can't be charmed succeeds on this saving throw automatically, and if you or dein companions are fighting a Kreatur, it has advantage on the save.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenpakt_magier"],
  },
  {
    key: "find_steed",
    name: "Streitross finden",
    nameEn: "Find Steed",
    hook: "Streitross finden: Grad 2, Beschwörung — 10 Minuten, 9 Meter.",
    description: "Streitross finden ist ein Zauber des 2. Grades (Beschwörung). Wirkungszeit: 10 Minuten. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: paladin. Kernwirkung: Du rufst einen Geist, der die Gestalt eines ungewöhnlich intelligenten, starken und treuen Rosses annimmt, und bindest euch dauerhaft. Appearing in an unoccupied space in Reichweite, the steed takes on a form that you choose, such as a warhorse, a pony, a camel, an elk, or a mastiff.",
    source: SRD_SOURCE,
    level: 2,
    school: "conjuration",
    castingTime: "10 Minuten",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["paladin"],
  },
  {
    key: "find_traps",
    name: "Fallen finden",
    nameEn: "Find Traps",
    hook: "Fallen finden: Grad 2, Erkenntnis — Aktion, 36 Meter.",
    description: "Fallen finden ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer. Kernwirkung: Du spürst jede Falle in Reichweite, die in Sichtlinie liegt. A trap, for the purpose of this spell, includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable, which was specifically intended as such by its creator.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "flame_blade",
    name: "Flammenschwert",
    nameEn: "Flame Blade",
    hook: "Flammenschwert: Grad 2, Hervorrufung — Bonusaktion, Selbst.",
    description: "Flammenschwert ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Bonusaktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: Leaf of sumac.). Listen: druide. Kernwirkung: Du rufst eine flammende Klinge in deine freie Hand. The blade is similar in size and shape to a scimitar, and it lasts für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Sumachblatt" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "flaming_sphere",
    name: "Flammenkugel",
    nameEn: "Flaming Sphere",
    hook: "Flammenkugel: Grad 2, Beschwörung — Aktion, 18 Meter.",
    description: "Flammenkugel ist ein Zauber des 2. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A bit of tallow, a pinch of brimstone, and a dusting of powdered iron.). Listen: kleriker, druide, zauberer. Kernwirkung: Eine Feuerkugel von 1.5 Meter Durchmesser erscheint in einem freien Raum deiner Wahl in Reichweite und hält für die Dauer. Any Kreatur that ends its turn within 1.5 Meter of the sphere muss einen dexterity saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "etwas Talg, eine Prise Schwefel und etwas Eisenpulver" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "zauberer"],
  },
  {
    key: "gentle_repose",
    name: "Sanfte Ruhe",
    nameEn: "Gentle Repose",
    hook: "Sanfte Ruhe: Grad 2, Nekromantie — Aktion, Berührung.",
    description: "Sanfte Ruhe ist ein Zauber des 2. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 10 Tage. Komponenten: V, G, M (Material: A pinch of salt and one copper piece placed on each of the corpse's eyes, which must remain there for the duration.). Listen: kleriker, zauberer. Kernwirkung: Du berührst eine Leiche oder andere Überreste. For the duration, the target is protected from decay and can't become undead.",
    source: SRD_SOURCE,
    level: 2,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Prise Salz und je ein Kupferstück auf den Augen der Leiche, die für die Dauer dort bleiben müssen" },
    duration: "10 Tage",
    concentration: false,
    ritual: true,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "gust_of_wind",
    name: "Windstoß",
    nameEn: "Gust of Wind",
    hook: "Windstoß: Grad 2, Hervorrufung — Aktion, Selbst.",
    description: "Windstoß ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A legume seed.). Listen: kleriker, druide, hexenmeister, zauberer. Kernwirkung: Ein Windstoß von 18 Meter Länge und 3 Meter Breite bläst für die Dauer in eine von dir gewählte Richtung. Jede Kreatur that starts its turn in the line muss einen strength saving throw bestehen or be pushed 4.5 Meter away from you in a direction following the line.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Hülsenfruchtsamen" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "heat_metal",
    name: "Metall erhitzen",
    nameEn: "Heat Metal",
    hook: "Metall erhitzen: Grad 2, Verwandlung — Aktion, 18 Meter.",
    description: "Metall erhitzen ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A piece of iron and a flame.). Listen: druide, barde. Kernwirkung: Laut SRD: Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see in Reichweite. Du cause the object to glow red-hot. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Eisenstück und eine Flamme" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "barde"],
  },
  {
    key: "hold_person",
    name: "Person festhalten",
    nameEn: "Hold Person",
    hook: "Person festhalten: Grad 2, Verzauberung — Aktion, 18 Meter.",
    description: "Person festhalten ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A small, straight piece of iron.). Listen: kleriker, druide, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: Choose a humanoid that you can see in Reichweite. The target muss einen wisdom saving throw bestehen or be paralyzed für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein kleines, gerades Eisenstück" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "invisibility",
    name: "Unsichtbarkeit",
    nameEn: "Invisibility",
    hook: "Unsichtbarkeit: Grad 2, Illusion — Aktion, Berührung.",
    description: "Unsichtbarkeit ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: An eyelash encased in gum arabic.). Listen: druide, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Eine von dir berührte Kreatur wird unsichtbar, bis der Zauber endet. Anything the target is wearing or carrying is invisible as long as it is on the target's person. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Wimper, eingeschlossen in Gummiarabikum" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
];
