/**
 * Alle Zaubertricks des SRD 5.2.1 — Grad 0.
 *
 * Herkunft: SRD 5.2.1 (CC-BY-4.0, Wizards of the Coast), Regeln von 2024.
 * Mechanik — Grad, Schule, Zeit, Reichweite, Komponenten, Dauer und vor allem
 * `lists` — ist 1:1 aus dem SRD übernommen; `lists` steuert den Zauberschritt,
 * eine falsche Liste zeigt einem Spieler Zauber, die er nicht wirken kann.
 *
 * Deutsch ist Übersetzung, nicht Zitat: Ein deutsches SRD gibt es nicht, daher
 * sind `name`, `hook` und `description` UWEs eigene Fassung. `nameEn` hält den
 * Originalnamen, damit der Abgleich gegen die Quelle möglich bleibt.
 * Entfernungen stehen wie im übrigen Katalog in Metern (1,5 m je 5 Fuß).
 */

import { SRD_SOURCE, type Spell } from "../types";

/** Die 27 Zaubertricks des SRD, alphabetisch nach dem englischen Namen. */
export const CANTRIPS: Spell[] = [
  {
    key: "saeurespritzer",
    name: "Säurespritzer",
    nameEn: "Acid Splash",
    hook: "Eine platzende Säureblase trifft alles, was zu eng beieinandersteht.",
    description: "Du erschaffst an einem Punkt in 18 Metern eine Säureblase, die in einer Kugel mit 1,5 Metern Radius zerplatzt. Jede Kreatur darin muss einen Geschicklichkeits-Rettungswurf bestehen oder nimmt 1W6 Säureschaden. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W6.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "frostberuehrung",
    name: "Frostberührung",
    nameEn: "Chill Touch",
    hook: "Die Kälte des Grabes in deiner Hand — wen sie trifft, der kann sich vorerst nicht heilen.",
    description: "Du machst einen Nahkampf-Zauberangriff gegen ein Ziel in Reichweite. Bei einem Treffer nimmt es 1W10 nekrotischen Schaden und kann bis zum Ende deines nächsten Zuges keine Trefferpunkte zurückgewinnen. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W10.",
    source: SRD_SOURCE,
    level: 0,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "tanzende_lichter",
    name: "Tanzende Lichter",
    nameEn: "Dancing Lights",
    hook: "Vier schwebende Lichter, die du vorausschickst, statt selbst in den dunklen Gang zu gehen.",
    description: "Du erschaffst bis zu vier fackelgroße Lichter in 36 Metern — als Fackeln, Laternen oder schwebende Kugeln — oder fasst sie zu einer mittelgroßen, vage menschenähnlichen Gestalt zusammen. Jedes Licht spendet schwaches Licht im Umkreis von 3 Metern. Als Bonusaktion bewegst du die Lichter bis zu 18 Meter; ein Licht erlischt, sobald es die Reichweite verlässt.",
    source: SRD_SOURCE,
    level: 0,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "etwas Phosphor" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "druidenkunst",
    name: "Druidenkunst",
    nameEn: "Druidcraft",
    hook: "Kleine Naturwunder auf Zuruf: Wettervorhersage, aufblühende Knospe, ein Geräusch aus dem Nichts.",
    description: "Du flüsterst den Naturgeistern zu und erzeugst in 9 Metern einen Effekt: einen winzigen Sinneseffekt, der das Wetter der nächsten 24 Stunden am Ort vorhersagt; eine Blüte, Samenkapsel oder Knospe, die sich augenblicklich öffnet; oder einen harmlosen Sinneseffekt wie fallende Blätter, eine sanfte Brise oder ein Tiergeräusch in einem Würfel von 1,5 Metern Kantenlänge.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "schauerlicher_strahl",
    name: "Schauerlicher Strahl",
    nameEn: "Eldritch Blast",
    hook: "Der Standardangriff des Hexenpakt-Magiers — ein Energiestrahl, aus dem mit der Stufe vier werden.",
    description: "Du schleuderst einen knisternden Energiestrahl und machst einen Fernkampf-Zauberangriff gegen eine Kreatur oder ein Objekt in 36 Metern. Bei einem Treffer nimmt das Ziel 1W10 energetischen Schaden. Auf Stufe 5 entstehen zwei Strahlen, auf Stufe 11 drei und auf Stufe 17 vier — jeder mit eigenem Angriffswurf, auf dasselbe oder auf verschiedene Ziele.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenpakt_magier"],
  },
  {
    key: "elementarkunst",
    name: "Elementarkunst",
    nameEn: "Elementalism",
    hook: "Luft, Erde, Feuer oder Wasser in kleiner Dosis — nützlich am Lagerfeuer, nie tödlich.",
    description: "Du erzeugst in 9 Metern einen elementaren Effekt: eine Brise, die Stoff kräuselt, Staub aufwirbelt und offene Türen schließt; einen dünnen Schleier aus Staub oder Sand oder ein Wort in deiner Handschrift im Sand; harmlose Glut und farbigen, duftenden Rauch, der Kerzen und Fackeln entzünden kann; kühlen Sprühnebel oder eine Tasse sauberes Wasser; oder du formst Erde, Sand, Feuer, Rauch, Nebel oder Wasser für eine Stunde zu einer groben Gestalt.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "feuerblitz",
    name: "Feuerblitz",
    nameEn: "Fire Bolt",
    hook: "Der zuverlässigste Angriffszauber überhaupt: ein Feuerfunke auf 36 Meter, unbegrenzt oft.",
    description: "Du schleuderst einen Feuerfunken auf eine Kreatur oder ein Objekt in 36 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt das Ziel 1W10 Feuerschaden; ein brennbarer Gegenstand, den niemand trägt, fängt Feuer. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W10.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "fuehrung",
    name: "Führung",
    nameEn: "Guidance",
    hook: "Ein W4 auf die Probe, die gleich wichtig wird — der meistgenutzte Zaubertrick am Tisch.",
    description: "Du berührst eine willige Kreatur und wählst eine Fertigkeit. Bis der Zauber endet, addiert die Kreatur 1W4 auf jede Attributsprobe, die diese Fertigkeit verwendet.",
    source: SRD_SOURCE,
    level: 0,
    school: "divination",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "licht",
    name: "Licht",
    nameEn: "Light",
    hook: "Fackellicht ohne Fackel — auf einem Gegenstand deiner Wahl, eine Stunde lang.",
    description: "Du berührst einen großen oder kleineren Gegenstand, den niemand sonst trägt. Bis der Zauber endet, spendet er helles Licht im Umkreis von 6 Metern und weitere 6 Meter schwaches Licht, in der Farbe deiner Wahl. Etwas Undurchsichtiges darüber blockiert das Licht; ein erneutes Wirken beendet den Zauber.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: false, material: "ein Glühwürmchen oder phosphoreszierendes Moos" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "kleriker", "hexenmeister", "zauberer"],
  },
  {
    key: "magierhand",
    name: "Magierhand",
    nameEn: "Mage Hand",
    hook: "Eine geisterhafte Hand auf 9 Meter Entfernung — für alles, wofür du selbst nicht hingehen willst.",
    description: "Eine schwebende, geisterhafte Hand erscheint an einem Punkt in 9 Metern. Sie kann einen Gegenstand bewegen, eine unverschlossene Tür oder Truhe öffnen, etwas aus einem offenen Behälter nehmen oder eine Phiole ausgießen. Als Magieaktion steuerst du sie erneut und bewegst sie dabei bis zu 9 Meter. Angreifen, magische Gegenstände auslösen oder mehr als 10 Pfund tragen kann sie nicht.",
    source: SRD_SOURCE,
    level: 0,
    school: "conjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "ausbessern",
    name: "Ausbessern",
    nameEn: "Mending",
    hook: "Ein Riss, ein Bruch, ein Leck — nach einer Minute ist nichts mehr davon zu sehen.",
    description: "Du reparierst einen einzelnen Bruch oder Riss an einem Gegenstand, den du berührst: ein gerissenes Kettenglied, zwei Hälften eines Schlüssels, einen zerrissenen Umhang, einen undichten Weinschlauch. Der Schaden darf in keiner Richtung größer als 30 Zentimeter sein. Magische Gegenstände lassen sich so körperlich flicken, ihre Magie kehrt dadurch aber nicht zurück.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "1 Minute",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "zwei Magnetsteine" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "kleriker", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "botschaft",
    name: "Botschaft",
    nameEn: "Message",
    hook: "Ein Flüstern, das nur eine Person hört — quer durch den Raum oder durch eine Wand.",
    description: "Du zeigst auf eine Kreatur in 36 Metern und flüsterst eine Botschaft. Nur dieses Ziel hört sie und kann ebenso leise antworten. Durch feste Objekte hindurch gelingt der Zauber, wenn du das Ziel kennst und weißt, dass es dahinter ist. Magische Stille, 30 Zentimeter Stein, Metall oder Holz oder eine dünne Bleischicht blockieren ihn.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: false, somatic: true, material: "ein Kupferdraht" },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "kleine_illusion",
    name: "Kleine Illusion",
    nameEn: "Minor Illusion",
    hook: "Ein Geräusch oder ein Bild — damit lässt sich eine Wache erstaunlich zuverlässig ablenken.",
    description: "Du erschaffst in 9 Metern ein Geräusch oder das Bild eines Gegenstands. Das Geräusch reicht vom Flüstern bis zum Schrei und darf jede Stimme und jeder Laut sein. Ein Bild füllt höchstens einen Würfel von 1,5 Metern Kantenlänge und erzeugt weder Ton noch Licht noch Geruch. Wer die Illusion mit einer Untersuchen-Aktion und einer gelungenen Intelligenzprobe (Nachforschen) gegen deinen Zauberrettungswurf-SG durchschaut, sieht sie nur noch verblasst.",
    source: SRD_SOURCE,
    level: 0,
    school: "illusion",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: false, somatic: true, material: "ein Stück Vlies" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "giftschwall",
    name: "Giftschwall",
    nameEn: "Poison Spray",
    hook: "Ein Stoß giftigen Nebels auf kurze Distanz — der härteste Zaubertrick, solange das Ziel nicht immun ist.",
    description: "Du sprühst giftigen Nebel auf eine Kreatur in 9 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt das Ziel 1W12 Giftschaden. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W12.",
    source: SRD_SOURCE,
    level: 0,
    school: "necromancy",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "zaubertrick",
    name: "Zaubertrick",
    nameEn: "Prestidigitation",
    hook: "Der Werkzeugkasten für alles Kleine: säubern, anzünden, markieren, würzen, verblüffen.",
    description: "Du erzeugst in 3 Metern einen kleinen magischen Effekt: einen harmlosen Sinneseffekt wie Funkenregen, Windhauch oder seltsamen Geruch; eine Kerze, Fackel oder ein kleines Lagerfeuer entzünden oder löschen; einen Gegenstand von höchstens einem Kubikfuß säubern oder beschmutzen; totes Material eine Stunde lang kühlen, wärmen oder würzen; eine Farbe, Marke oder ein Symbol für eine Stunde erscheinen lassen; oder eine wertlose Spielerei bzw. ein Trugbild in Handgröße erschaffen. Bis zu drei nicht augenblickliche Effekte laufen gleichzeitig.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Aktion",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Bis zu 1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "flamme_erschaffen",
    name: "Flamme erschaffen",
    nameEn: "Produce Flame",
    hook: "Eine Flamme in der Hand: Licht für zehn Minuten und ein Wurfgeschoss, wenn es sein muss.",
    description: "Eine flackernde Flamme erscheint in deiner Hand. Sie erzeugt keine Hitze, entzündet nichts und spendet helles Licht im Umkreis von 6 Metern sowie weitere 6 Meter schwaches Licht. Bis der Zauber endet, schleuderst du als Magieaktion Feuer auf eine Kreatur oder ein Objekt in 18 Metern: ein Fernkampf-Zauberangriff, bei einem Treffer 1W8 Feuerschaden. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "conjuration",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "froststrahl",
    name: "Froststrahl",
    nameEn: "Ray of Frost",
    hook: "Kälteschaden und ein langsameres Ziel — der Zaubertrick gegen alles, was auf dich zuläuft.",
    description: "Ein eisiger, blauweißer Strahl schießt auf eine Kreatur in 18 Metern zu. Mach einen Fernkampf-Zauberangriff; bei einem Treffer nimmt das Ziel 1W8 Kälteschaden, und seine Bewegungsrate sinkt bis zum Beginn deines nächsten Zuges um 3 Meter. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "widerstand",
    name: "Widerstand",
    nameEn: "Resistance",
    hook: "Ein W4 weniger Schaden von genau dem Typ, den du kommen siehst.",
    description: "Du berührst eine willige Kreatur und wählst einen Schadenstyp. Nimmt sie vor dem Ende des Zaubers Schaden dieses Typs, reduziert sie den Gesamtschaden um 1W4. Pro Zug wirkt das nur einmal.",
    source: SRD_SOURCE,
    level: 0,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "heilige_flamme",
    name: "Heilige Flamme",
    nameEn: "Sacred Flame",
    hook: "Gleißender Schaden, gegen den Deckung nicht hilft — der Angriffszauber des Klerikers.",
    description: "Flammengleicher Glanz senkt sich auf eine sichtbare Kreatur in 18 Metern. Sie muss einen Geschicklichkeits-Rettungswurf bestehen oder nimmt 1W8 gleißenden Schaden — halbe oder dreiviertel Deckung hilft ihr dabei nicht. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "druidenknueppel",
    name: "Druidenknüppel",
    nameEn: "Shillelagh",
    hook: "Dein Kampfstab schlägt mit dem Zauberattribut statt mit Stärke — und mit größerem Würfel.",
    description: "Eine Keule oder ein Kampfstab in deiner Hand wird von der Kraft der Natur durchdrungen. Eine Minute lang verwendest du für Angriffs- und Schadenswürfe damit im Nahkampf dein Zauberattribut statt Stärke, und der Schadenswürfel der Waffe wird zu einem W8; der Schaden darf energetisch oder vom normalen Typ der Waffe sein. Der Würfel wächst auf Stufe 5 (W10), 11 (W12) und 17 (2W6).",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Mistelzweig" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "schockgriff",
    name: "Schockgriff",
    nameEn: "Shocking Grasp",
    hook: "Ein Stromstoß per Handschlag — und der Getroffene kann dir nicht hinterherschlagen.",
    description: "Blitze springen von dir auf eine Kreatur über, die du zu berühren versuchst. Mach einen Nahkampf-Zauberangriff; bei einem Treffer nimmt das Ziel 1W8 Blitzschaden und kann bis zum Beginn seines nächsten Zuges keine Gelegenheitsangriffe machen. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "arkaner_ausbruch",
    name: "Arkaner Ausbruch",
    nameEn: "Sorcerous Burst",
    hook: "Der Zaubertrick des Hexenmeisters: freier Schadenstyp und Würfel, die weiterexplodieren.",
    description: "Du schleuderst rohe Zauberkraft auf eine Kreatur oder ein Objekt in 36 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt das Ziel 1W8 Schaden eines Typs deiner Wahl: Säure, Kälte, Feuer, Blitz, Gift, psychisch oder Schall. Würfelst du dabei eine 8, darfst du einen weiteren W8 würfeln und addieren — höchstens so oft, wie dein Zauberattributsmodifikator beträgt. Der Grundschaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister"],
  },
  {
    key: "sterbende_stabilisieren",
    name: "Sterbende stabilisieren",
    nameEn: "Spare the Dying",
    hook: "Aus viereinhalb Metern Entfernung stabilisieren, ohne einen Heiltrank zu verbrauchen.",
    description: "Du wählst eine Kreatur in 4,5 Metern, die auf 0 Trefferpunkte gefallen und nicht tot ist. Sie wird stabilisiert. Die Reichweite verdoppelt sich auf Stufe 5 (9 Meter), 11 (18 Meter) und 17 (36 Meter).",
    source: SRD_SOURCE,
    level: 0,
    school: "necromancy",
    castingTime: "Aktion",
    range: "4,5 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "sternenfunke",
    name: "Sternenfunke",
    nameEn: "Starry Wisp",
    hook: "Gleißender Schaden, und das Ziel leuchtet — unsichtbar bleiben kann es danach nicht mehr.",
    description: "Du schleuderst einen Lichtfunken auf eine Kreatur oder ein Objekt in 18 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt das Ziel 1W8 gleißenden Schaden, strahlt bis zum Ende deines nächsten Zuges schwaches Licht im Umkreis von 3 Metern ab und kann in dieser Zeit nicht vom Zustand Unsichtbar profitieren. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W8.",
    source: SRD_SOURCE,
    level: 0,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide"],
  },
  {
    key: "thaumaturgie",
    name: "Thaumaturgie",
    nameEn: "Thaumaturgy",
    hook: "Die kleine Show des Klerikers: dröhnende Stimme, flackernde Flammen, Türen, die von selbst aufspringen.",
    description: "Du wirkst in 9 Metern ein kleines Wunder: deine Augen verändern eine Minute lang ihr Aussehen; deine Stimme dröhnt eine Minute lang dreifach laut und gibt dir Vorteil auf Charismaproben (Einschüchtern); Flammen flackern, leuchten auf, verdunkeln sich oder wechseln die Farbe; eine unverschlossene Tür oder ein Fenster fliegt auf oder knallt zu; ein Geräusch entsteht an einem Punkt deiner Wahl; oder der Boden bebt eine Minute lang harmlos. Bis zu drei der Minuteneffekte laufen gleichzeitig.",
    source: SRD_SOURCE,
    level: 0,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Bis zu 1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "wahrer_schlag",
    name: "Wahrer Schlag",
    nameEn: "True Strike",
    hook: "Ein Waffenangriff mit deinem Zauberattribut — der mit der Stufe gleißenden Zusatzschaden bekommt.",
    description: "Geleitet von einem magischen Geistesblitz machst du einen Angriff mit der Waffe, die du beim Wirken benutzt hast. Der Angriff verwendet für Angriffs- und Schadenswürfe dein Zauberattribut statt Stärke oder Geschicklichkeit, und der Schaden darf gleißend oder vom normalen Typ der Waffe sein. Ab Stufe 5 kommt zusätzlicher gleißender Schaden dazu: 1W6, ab Stufe 11 2W6, ab Stufe 17 3W6.",
    source: SRD_SOURCE,
    level: 0,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: false, somatic: true, material: "eine Waffe, mit der du geübt bist und die mindestens 1 KM wert ist" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "bissiger_spott",
    name: "Bissiger Spott",
    nameEn: "Vicious Mockery",
    hook: "Eine Beleidigung, die weh tut — psychischer Schaden und Nachteil auf den nächsten Angriff.",
    description: "Du schleuderst einer sichtbaren oder hörbaren Kreatur in 18 Metern eine mit Magie durchsetzte Beleidigung entgegen. Sie muss einen Weisheits-Rettungswurf bestehen oder nimmt 1W6 psychischen Schaden und hat Nachteil auf ihren nächsten Angriffswurf vor dem Ende ihres nächsten Zuges. Der Schaden steigt auf Stufe 5, 11 und 17 um je 1W6.",
    source: SRD_SOURCE,
    level: 0,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde"],
  },
];
