/**
 * SRD-Zauber Grad 4 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL4_SPELLS_A: Spell[] = [
  {
    key: "arcane_eye",
    name: "Arkanes Auge",
    nameEn: "Arcane Eye",
    hook: "Arkanes Auge: Grad 4, Erkenntnis — Aktion, 9 Meter.",
    description: "Arkanes Auge ist ein Zauber des 4. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A bit of bat fur.). Listen: kleriker, zauberer. Kernwirkung: Du create an invisible, magical eye in Reichweite that hovers in the air für die Dauer. Du mentally receive visual information from the eye, which has normal vision and darkvision out to 9 Meter.",
    source: SRD_SOURCE,
    level: 4,
    school: "divination",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "etwas Fledermausfell" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "banishment",
    name: "Verbannung",
    nameEn: "Banishment",
    hook: "Verbannung: Grad 4, Abwehr — Aktion, 18 Meter.",
    description: "Verbannung ist ein Zauber des 4. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: An item distasteful to the target.). Listen: kleriker, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du attempt to send one Kreatur that you can see in Reichweite to another plane of existence. The target muss einen charisma saving throw bestehen or be banished. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "abjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Gegenstand, der dem Ziel zuwider ist" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "black_tentacles",
    name: "Schwarze Tentakel",
    nameEn: "Black Tentacles",
    hook: "Schwarze Tentakel: Grad 4, Beschwörung — Aktion, 27 Meter.",
    description: "Schwarze Tentakel ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A piece of tentacle from a giant octopus or a giant squid). Listen: hexenpakt_magier, zauberer. Kernwirkung: Squirming, ebony tentacles fill a 6 Meter square on ground that you can see in Reichweite. For the duration, these tentacles turn the ground in the area into difficult terrain.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "ein Stück Tentakel eines Riesenkraken oder Riesenkalmars" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "blight",
    name: "Verdorrung",
    nameEn: "Blight",
    hook: "Verdorrung: Grad 4, Nekromantie — Aktion, 9 Meter.",
    description: "Verdorrung ist ein Zauber des 4. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Necromantic energy washes over a Kreatur of dein choice that you can see in Reichweite, draining moisture and vitality from it. The target muss einen constitution saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "necromancy",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "compulsion",
    name: "Zwang",
    nameEn: "Compulsion",
    hook: "Zwang: Grad 4, Verzauberung — Aktion, 9 Meter.",
    description: "Zwang ist ein Zauber des 4. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: barde. Kernwirkung: Creatures of dein choice that you can see in Reichweite and that can hear you muss einen Wisdom saving throw bestehen. A target automatically succeeds on this saving throw if it can't be charmed.",
    source: SRD_SOURCE,
    level: 4,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde"],
  },
  {
    key: "confusion",
    name: "Verwirrung",
    nameEn: "Confusion",
    hook: "Verwirrung: Grad 4, Verzauberung — Aktion, 27 Meter.",
    description: "Verwirrung ist ein Zauber des 4. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: Three walnut shells.). Listen: kleriker, druide, barde, hexenmeister, zauberer. Kernwirkung: Laut SRD: This spell assaults and twists Kreaturen' minds, spawning delusions and provoking uncontrolled action. Jede Kreatur in a 3 Meter radius sphere centered on a point you choose in Reichweite muss einen Wisdom saving throw bestehen when you cast this spell or be affected by it. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "enchantment",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "drei Walnussschalen" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenmeister", "zauberer"],
  },
  {
    key: "conjure_minor_elementals",
    name: "Geringe Elementare herbeizaubern",
    nameEn: "Conjure Minor Elementals",
    hook: "Geringe Elementare herbeizaubern: Grad 4, Beschwörung — 1 Minute, 27 Meter.",
    description: "Geringe Elementare herbeizaubern ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: druide, zauberer. Kernwirkung: Du summon elementals that appear in unoccupied spaces that you can see in Reichweite. Du choose one the following options for what appears: - One elemental of challenge rating 2 or lower - Two elementals of challenge rating 1 or lower - Four elementals of challenge rating 1/2 or lower - Eight elementals of challenge rating 1/4 or lower. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "conjure_woodland_beings",
    name: "Waldwesen herbeizaubern",
    nameEn: "Conjure Woodland Beings",
    hook: "Waldwesen herbeizaubern: Grad 4, Beschwörung — Aktion, 18 Meter.",
    description: "Waldwesen herbeizaubern ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: One holly berry per creature summoned.). Listen: druide, waldlaeufer. Kernwirkung: Du summon fey Kreaturen that appear in unoccupied spaces that you can see in Reichweite. Choose one of the following options for what appears: - One fey Kreatur of challenge rating 2 or lower - Two fey Kreaturen of challenge rating 1 or lower - Four fey Kreaturen of challenge rating 1/2 or lower - Eight fey Kreaturen of challenge rating 1/4 or lower A summoned Kreatur disappears when it drops to 0 hit points or when the spell ends. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "eine Stechpalmenbeere pro beschworener Kreatur" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "waldlaeufer"],
  },
  {
    key: "control_water",
    name: "Wasser kontrollieren",
    nameEn: "Control Water",
    hook: "Wasser kontrollieren: Grad 4, Verwandlung — Aktion, 90 Meter.",
    description: "Wasser kontrollieren ist ein Zauber des 4. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 90 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A drop of water and a pinch of dust.). Listen: kleriker, druide, zauberer. Kernwirkung: Laut SRD: Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 30 Meter on a side. Du can choose from any of the following effects when you cast this spell.",
    source: SRD_SOURCE,
    level: 4,
    school: "transmutation",
    castingTime: "Aktion",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Wasser und eine Prise Staub" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "zauberer"],
  },
  {
    key: "death_ward",
    name: "Todesschutz",
    nameEn: "Death Ward",
    hook: "Todesschutz: Grad 4, Abwehr — Aktion, Berührung.",
    description: "Todesschutz ist ein Zauber des 4. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 8 Stunden. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du berührst eine Kreatur and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking Schaden, the target instead drops to 1 hit point, and the spell ends.",
    source: SRD_SOURCE,
    level: 4,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "dimension_door",
    name: "Dimensions Tür",
    nameEn: "Dimension Door",
    hook: "Dimensions Tür: Grad 4, Beschwörung — Aktion, 150 Meter.",
    description: "Dimensions Tür ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 150 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du teleport yourself from dein current location to any other spot in Reichweite. Du arrive at exactly the spot desired.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "150 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "divination",
    name: "Weissagung",
    nameEn: "Divination",
    hook: "Weissagung: Grad 4, Erkenntnis — Aktion, Selbst.",
    description: "Weissagung ist ein Zauber des 4. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Incense and a sacrificial offering appropriate to your religion, together worth at least 25gp, which the spell consumes.). Listen: kleriker, druide. Kernwirkung: Dein magic and an offering put you in contact with a god or a god's servants. Du ask a single question concerning a specific goal, event, or activity to occur within 7 days.",
    source: SRD_SOURCE,
    level: 4,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Weihrauch und eine Opfergabe passend zu deiner Religion, zusammen mindestens 25 KM wert, die der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["kleriker", "druide"],
  },
  {
    key: "dominate_beast",
    name: "Tier beherrschen",
    nameEn: "Dominate Beast",
    hook: "Tier beherrschen: Grad 4, Verzauberung — Aktion, 18 Meter.",
    description: "Tier beherrschen ist ein Zauber des 4. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, druide, hexenmeister, hexenpakt_magier. Kernwirkung: Du attempt to beguile a beast that you can see in Reichweite. It muss einen wisdom saving throw bestehen or be charmed by you für die Dauer. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister", "hexenpakt_magier"],
  },
  {
    key: "fabricate",
    name: "Fertigung",
    nameEn: "Fabricate",
    hook: "Fertigung: Grad 4, Verwandlung — 10 Minuten, 36 Meter.",
    description: "Fertigung ist ein Zauber des 4. Grades (Verwandlung). Wirkungszeit: 10 Minuten. Reichweite: 36 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: zauberer. Kernwirkung: Du convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool.",
    source: SRD_SOURCE,
    level: 4,
    school: "transmutation",
    castingTime: "10 Minuten",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "faithful_hound",
    name: "Getreuer Hund",
    nameEn: "Faithful Hound",
    hook: "Getreuer Hund: Grad 4, Beschwörung — Aktion, 9 Meter.",
    description: "Getreuer Hund ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A tiny silver whistle, a piece of bone, and a thread). Listen: zauberer. Kernwirkung: Du conjure a phantom watchdog in an unoccupied space that you can see in Reichweite, where it remains für die Dauer, until you dismiss it as an action, or until you move more than 30 Meter away from it. The hound is invisible to all Kreaturen except you and can't be harmed.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine winzige Silberpfeife, ein Stück Knochen und ein Faden" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "fire_shield",
    name: "Feuerschild",
    nameEn: "Fire Shield",
    hook: "Feuerschild: Grad 4, Hervorrufung — Aktion, Selbst.",
    description: "Feuerschild ist ein Zauber des 4. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 10 Minuten. Komponenten: V, G, M (Material: A little phosphorus or a firefly.). Listen: hexenpakt_magier, zauberer. Kernwirkung: Thin and vaporous flame surround dein body für die Dauer of the spell, radiating a bright light bright light in a 3 Meter radius and dim light for an additional 3 Meter. Du can end the spell using an action to make it disappear.",
    source: SRD_SOURCE,
    level: 4,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "etwas Phosphor oder ein Glühwürmchen" },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "freedom_of_movement",
    name: "Bewegungsfreiheit",
    nameEn: "Freedom of Movement",
    hook: "Bewegungsfreiheit: Grad 4, Abwehr — Aktion, Berührung.",
    description: "Bewegungsfreiheit ist ein Zauber des 4. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G, M (Material: A leather strap, bound around the arm or a similar appendage.). Listen: kleriker, druide, waldlaeufer, barde. Kernwirkung: Du berührst eine willige Kreatur. For the duration, the target's movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target's speed nor cause the target to be paralyzed or restrained.",
    source: SRD_SOURCE,
    level: 4,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Lederriemen, um den Arm oder ein ähnliches Glied gebunden" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "barde"],
  },
  {
    key: "giant_insect",
    name: "Rieseninsekt",
    nameEn: "Giant Insect",
    hook: "Rieseninsekt: Grad 4, Verwandlung — Aktion, 9 Meter.",
    description: "Rieseninsekt ist ein Zauber des 4. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: druide. Kernwirkung: Du transform up to ten centipedes, three spiders, five wasps, or one scorpion in Reichweite into giant versions of their natural forms für die Dauer. A centipede becomes a giant centipede, a spider becomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion.",
    source: SRD_SOURCE,
    level: 4,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "greater_invisibility",
    name: "Höhere Unsichtbarkeit",
    nameEn: "Greater Invisibility",
    hook: "Höhere Unsichtbarkeit: Grad 4, Illusion — Aktion, Berührung.",
    description: "Höhere Unsichtbarkeit ist ein Zauber des 4. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: druide, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du or a Kreatur you touch becomes invisible bis der Zauber endet. Anything the target is wearing or carrying is invisible as long as it is on the target's person.",
    source: SRD_SOURCE,
    level: 4,
    school: "illusion",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "guardian_of_faith",
    name: "Wächter des Glaubens",
    nameEn: "Guardian of Faith",
    hook: "Wächter des Glaubens: Grad 4, Beschwörung — Aktion, 9 Meter.",
    description: "Wächter des Glaubens ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 8 Stunden. Komponenten: V. Listen: kleriker. Kernwirkung: Laut SRD: A Large spectral guardian appears and hovers für die Dauer in an unoccupied space of dein choice that you can see in Reichweite. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of dein deity.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "hallucinatory_terrain",
    name: "Halluzinatorisches Gelände",
    nameEn: "Hallucinatory Terrain",
    hook: "Halluzinatorisches Gelände: Grad 4, Illusion — 10 Minuten, 90 Meter.",
    description: "Halluzinatorisches Gelände ist ein Zauber des 4. Grades (Illusion). Wirkungszeit: 10 Minuten. Reichweite: 90 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A stone, a twig, and a bit of green plant.). Listen: druide, barde, hexenpakt_magier, zauberer. Kernwirkung: Du make natural terrain in a 45 Meter cube in range look, sound, and smell like some other sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain.",
    source: SRD_SOURCE,
    level: 4,
    school: "illusion",
    castingTime: "10 Minuten",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "ein Stein, ein Zweig und etwas grüne Pflanze" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "ice_storm",
    name: "Eissturm",
    nameEn: "Ice Storm",
    hook: "Eissturm: Grad 4, Hervorrufung — Aktion, 90 Meter.",
    description: "Eissturm ist ein Zauber des 4. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 90 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A pinch of dust and a few drops of water.). Listen: kleriker, druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: A hail of rock-hard ice pounds to the ground in a 6 Meter-radius, 12 Meter-high cylinder centered on a point in Reichweite. Jede Kreatur in the cylinder muss einen dexterity saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "evocation",
    castingTime: "Aktion",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Staub und ein paar Tropfen Wasser" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "locate_creature",
    name: "Kreatur orten",
    nameEn: "Locate Creature",
    hook: "Kreatur orten: Grad 4, Erkenntnis — Aktion, Selbst.",
    description: "Kreatur orten ist ein Zauber des 4. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A bit of fur from a bloodhound.). Listen: kleriker, druide, waldlaeufer, barde, zauberer. Kernwirkung: Describe or name a Kreatur that is familiar to you. Du sense the direction to the Kreatur's location, as long as that Kreatur is within 1,0 Meter of you.",
    source: SRD_SOURCE,
    level: 4,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "etwas Fell eines Bluthundes" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "barde", "zauberer"],
  },
  {
    key: "phantasmal_killer",
    name: "Phantasmaler Mörder",
    nameEn: "Phantasmal Killer",
    hook: "Phantasmaler Mörder: Grad 4, Illusion — Aktion, 36 Meter.",
    description: "Phantasmaler Mörder ist ein Zauber des 4. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: zauberer. Kernwirkung: Du tap into the nightmares of a Kreatur you can see in Reichweite and create an illusory manifestation of its deepest fears, visible only to that Kreatur. The target muss einen wisdom saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "polymorph",
    name: "Verwandlung",
    nameEn: "Polymorph",
    hook: "Verwandlung: Grad 4, Verwandlung — Aktion, 18 Meter.",
    description: "Verwandlung ist ein Zauber des 4. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A caterpillar cocoon.). Listen: kleriker, druide, barde, hexenmeister, zauberer. Kernwirkung: Laut SRD: This spell transforms a Kreatur that you can see in Reichweite into a new form. An unwilling Kreatur muss einen wisdom saving throw bestehen to avoid the effect.",
    source: SRD_SOURCE,
    level: 4,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Raupenkokon" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenmeister", "zauberer"],
  },
  {
    key: "private_sanctum",
    name: "Privates Sanktum",
    nameEn: "Private Sanctum",
    hook: "Privates Sanktum: Grad 4, Abwehr — 10 Minuten, 36 Meter.",
    description: "Privates Sanktum ist ein Zauber des 4. Grades (Abwehr). Wirkungszeit: 10 Minuten. Reichweite: 36 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite.). Listen: zauberer. Kernwirkung: Du make an area in Reichweite magically secure. The area is a cube that can be as small as 1.5 Meter to as large as 30 Meter on each side. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 4,
    school: "abjuration",
    castingTime: "10 Minuten",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein dünnes Bleiblech, ein Stück undurchsichtiges Glas, ein Watte- oder Stoffbausch und pulverisierter Chrysolith" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "resilient_sphere",
    name: "Widerstandsfähige Sphäre",
    nameEn: "Resilient Sphere",
    hook: "Widerstandsfähige Sphäre: Grad 4, Hervorrufung — Aktion, 9 Meter.",
    description: "Widerstandsfähige Sphäre ist ein Zauber des 4. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic.). Listen: zauberer. Kernwirkung: Laut SRD: A sphere of shimmering force encloses a Kreatur or object of Large size or smaller in Reichweite. An unwilling Kreatur muss einen dexterity saving throw bestehen.",
    source: SRD_SOURCE,
    level: 4,
    school: "evocation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein halb kugelförmiges Stück klaren Kristalls und ein passendes Stück Gummiarabikum" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "secret_chest",
    name: "Geheime Truhe",
    nameEn: "Secret Chest",
    hook: "Geheime Truhe: Grad 4, Beschwörung — Aktion, Berührung.",
    description: "Geheime Truhe ist ein Zauber des 4. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: An exquisite chest, 0.9 Meter by 0.6 Meter by 0.6 Meter, constructed from rare materials worth at least 5,000 gp, and a Tiny replica made from the same materials worth at least 50 gp.). Listen: zauberer. Kernwirkung: Du hide a chest, and all its contents, on the Ethereal Plane. Du must touch the chest and the miniature replica that serves as a material component for the spell.",
    source: SRD_SOURCE,
    level: 4,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine exquisite Truhe (ca. 90×60×60 cm) aus seltenen Materialien im Wert von mindestens 5000 KM und eine winzige Nachbildung aus denselben Materialien im Wert von mindestens 50 KM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
];
