/**
 * SRD-Zauber Grad 6 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL6_SPELLS_A: Spell[] = [
  {
    key: "blade_barrier",
    name: "Klingenbarriere",
    nameEn: "Blade Barrier",
    hook: "Klingenbarriere: Grad 6, Hervorrufung — Aktion, 27 Meter.",
    description: "Klingenbarriere ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du create a vertical wall of whirling, razor-sharp blades made of magical energy. The wall appears in Reichweite and lasts für die Dauer.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "chain_lightning",
    name: "Kettenblitz",
    nameEn: "Chain Lightning",
    hook: "Kettenblitz: Grad 6, Hervorrufung — Aktion, 45 Meter.",
    description: "Kettenblitz ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins.). Listen: hexenmeister, zauberer. Kernwirkung: Du create a bolt of lightning that arcs toward a target of dein choice that you can see in Reichweite. Three bolts then leap from that target to as many as three other targets, each of which must be within 9 Meter of the first target. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "etwas Fell; ein Stück Bernstein, Glas oder ein Kristallstab; und drei Silbernadeln" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "circle_of_death",
    name: "Kreis des Todes",
    nameEn: "Circle of Death",
    hook: "Kreis des Todes: Grad 6, Nekromantie — Aktion, 45 Meter.",
    description: "Kreis des Todes ist ein Zauber des 6. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: The powder of a crushed black pearl worth at least 500 gp.). Listen: hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: A sphere of negative energy ripples out in a 18 Meter-radius sphere from a point in Reichweite. Jede Kreatur in that area muss einen constitution saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "necromancy",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "Pulver einer zerdrückten schwarzen Perle im Wert von mindestens 500 KM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "conjure_fey",
    name: "Feenwesen herbeizaubern",
    nameEn: "Conjure Fey",
    hook: "Feenwesen herbeizaubern: Grad 6, Beschwörung — 1 Minute, 27 Meter.",
    description: "Feenwesen herbeizaubern ist ein Zauber des 6. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: druide, hexenpakt_magier. Kernwirkung: Du summon a fey Kreatur of challenge rating 6 or lower, or a fey spirit that takes the form of a beast of challenge rating 6 or lower. It appears in an unoccupied space that you can see in Reichweite. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenpakt_magier"],
  },
  {
    key: "contingency",
    name: "Eventualzauber",
    nameEn: "Contingency",
    hook: "Eventualzauber: Grad 6, Hervorrufung — 10 Minuten, Selbst.",
    description: "Eventualzauber ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: 10 Minuten. Reichweite: Selbst. Dauer: 10 Tage. Komponenten: V, G, M (Material: A statuette of yourself carved from ivory and decorated with gems worth at least 1,500 gp.). Listen: zauberer. Kernwirkung: Laut SRD: Choose a spell of 5th level or lower that you can cast, that has a casting time of 1 action, and that can target you. Du cast that spell-called the contingent spell-as part of casting contingency, expending spell slots for both, but the contingent spell doesn't come into effect.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "10 Minuten",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Elfenbein-Statuette von dir, mit Edelsteinen verziert, im Wert von mindestens 1500 KM" },
    duration: "10 Tage",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "create_undead",
    name: "Untote erschaffen",
    nameEn: "Create Undead",
    hook: "Untote erschaffen: Grad 6, Nekromantie — 1 Minute, 3 Meter.",
    description: "Untote erschaffen ist ein Zauber des 6. Grades (Nekromantie). Wirkungszeit: 1 Minute. Reichweite: 3 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: One clay pot filled with grave dirt, one clay pot filled with brackish water, and one 150 gp black onyx stone for each corpse.). Listen: kleriker, hexenpakt_magier, zauberer. Kernwirkung: Du can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids in Reichweite. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "necromancy",
    castingTime: "1 Minute",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "pro Leiche ein Tontopf Friedhofserde, ein Tontopf Brackwasser und ein schwarzer Onyx im Wert von 150 KM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "disintegrate",
    name: "Auflösen",
    nameEn: "Disintegrate",
    hook: "Auflösen: Grad 6, Verwandlung — Aktion, 18 Meter.",
    description: "Auflösen ist ein Zauber des 6. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A lodestone and a pinch of dust.). Listen: hexenmeister, zauberer. Kernwirkung: Laut SRD: A thin green ray springs from dein pointing finger to a target that you can see in Reichweite. The target can be a Kreatur, an object, or a creation of magical force, such as the wall created by wall of force. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Magnetstein und eine Prise Staub" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "eyebite",
    name: "Augenbiss",
    nameEn: "Eyebite",
    hook: "Augenbiss: Grad 6, Nekromantie — Aktion, Selbst.",
    description: "Augenbiss ist ein Zauber des 6. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: For the spell's duration, dein eyes become an inky void imbued with dread power. One Kreatur of dein choice within 18 Meter of you that you can see muss einen wisdom saving throw bestehen or be affected by one of the following effects of dein choice für die Dauer.",
    source: SRD_SOURCE,
    level: 6,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "find_the_path",
    name: "Den Weg finden",
    nameEn: "Find the Path",
    hook: "Den Weg finden: Grad 6, Erkenntnis — 1 Minute, Selbst.",
    description: "Den Weg finden ist ein Zauber des 6. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: Konzentration, bis zu 24 Stunden. Komponenten: V, G, M (Material: A set of divinatory tools-such as bones, ivory sticks, cards, teeth, or carved runes-worth 100gp and an object from the location you wish to find.). Listen: kleriker, druide, barde. Kernwirkung: Laut SRD: This spell allows you to find the shortest, most direct physical route to a specific fixed location that you are familiar with on the same plane of existence. If you name a destination on another plane of existence, a destination that moves (such as a mobile fortress), or a destination that isn't specific (such as \"a green dragon's lair\"), the spell fails.",
    source: SRD_SOURCE,
    level: 6,
    school: "divination",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Satz Wahrsagewerkzeuge — z. B. Knochen, Elfenbeinstäbe, Karten, Zähne oder geschnitzte Runen — im Wert von 100 KM und ein Gegenstand vom gesuchten Ort" },
    duration: "Konzentration, bis zu 24 Stunden",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde"],
  },
  {
    key: "flesh_to_stone",
    name: "Fleisch zu Stein",
    nameEn: "Flesh to Stone",
    hook: "Fleisch zu Stein: Grad 6, Verwandlung — Aktion, 18 Meter.",
    description: "Fleisch zu Stein ist ein Zauber des 6. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A pinch of lime, water, and earth.). Listen: hexenpakt_magier, zauberer. Kernwirkung: Du attempt to turn one Kreatur that you can see in Reichweite into stone. If the target's body is made of flesh, the Kreatur muss einen constitution saving throw bestehen.",
    source: SRD_SOURCE,
    level: 6,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Kalk, Wasser und Erde" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "forbiddance",
    name: "Bannkreis",
    nameEn: "Forbiddance",
    hook: "Bannkreis: Grad 6, Abwehr — 10 Minuten, Berührung.",
    description: "Bannkreis ist ein Zauber des 6. Grades (Abwehr). Wirkungszeit: 10 Minuten. Reichweite: Berührung. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A sprinkling of holy water, rare incense, and powdered ruby worth at least 1,000 gp.). Listen: kleriker. Kernwirkung: Du create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 9 Meter above the floor. For the duration, Kreaturen can't teleport into the area or use portals, such as those created by the gate spell, to enter the area.",
    source: SRD_SOURCE,
    level: 6,
    school: "abjuration",
    castingTime: "10 Minuten",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Prise Weihwasser, seltener Weihrauch und Rubinpulver im Wert von mindestens 1000 KM" },
    duration: "24 Stunden",
    concentration: false,
    ritual: true,
    lists: ["kleriker"],
  },
  {
    key: "freezing_sphere",
    name: "Frostsphäre",
    nameEn: "Freezing Sphere",
    hook: "Frostsphäre: Grad 6, Hervorrufung — Aktion, 90 Meter.",
    description: "Frostsphäre ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 90 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A small crystal sphere.). Listen: zauberer. Kernwirkung: Laut SRD: A frigid globe of cold energy streaks from dein fingertips to a point of dein choice in Reichweite, where it explodes in a 18 Meter-radius sphere. Jede Kreatur within the area muss einen constitution saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "eine kleine Kristallkugel" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "globe_of_invulnerability",
    name: "Kugel der Unverwundbarkeit",
    nameEn: "Globe of Invulnerability",
    hook: "Kugel der Unverwundbarkeit: Grad 6, Abwehr — Aktion, Selbst.",
    description: "Kugel der Unverwundbarkeit ist ein Zauber des 6. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A glass or crystal bead that shatters when the spell ends.). Listen: hexenmeister, zauberer. Kernwirkung: Laut SRD: An immobile, faintly shimmering barrier springs into existence in a 3 Meter radius around you and remains für die Dauer. Any spell of 5th level or lower cast from outside the barrier can't affect Kreaturen or objects within it, even if the spell is cast using a higher level spell slot. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Glas- oder Kristallperle, die zerbricht, wenn der Zauber endet" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "guards_and_wards",
    name: "Wächter und Schutzzeichen",
    nameEn: "Guards and Wards",
    hook: "Wächter und Schutzzeichen: Grad 6, Abwehr — 10 Minuten, Berührung.",
    description: "Wächter und Schutzzeichen ist ein Zauber des 6. Grades (Abwehr). Wirkungszeit: 10 Minuten. Reichweite: Berührung. Dauer: 24 Stunden. Komponenten: V, G, M (Material: Burning incense, a small measure of brimstone and oil, a knotted string, a small amount of umber hulk blood, and a small silver rod worth at least 10 gp.). Listen: barde, zauberer. Kernwirkung: Du create a ward that protects up to 2,500 square feet of floor space (an area 15 Meter square, or one hundred 1.5 Meter squares or twenty-five 3 Meter squares). The warded area can be up to 6 Meter tall, and shaped as you desire.",
    source: SRD_SOURCE,
    level: 6,
    school: "abjuration",
    castingTime: "10 Minuten",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "brennender Weihrauch, etwas Schwefel und Öl, eine verknotete Schnur, etwas Umberhulk-Blut und eine kleine Silberstange im Wert von mindestens 10 KM" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "harm",
    name: "Verletzen",
    nameEn: "Harm",
    hook: "Verletzen: Grad 6, Nekromantie — Aktion, 18 Meter.",
    description: "Verletzen ist ein Zauber des 6. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du unleash a virulent disease on a Kreatur that you can see in Reichweite. The target muss einen constitution saving throw bestehen.",
    source: SRD_SOURCE,
    level: 6,
    school: "necromancy",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "heal",
    name: "Heilen",
    nameEn: "Heal",
    hook: "Heilen: Grad 6, Hervorrufung — Aktion, 18 Meter.",
    description: "Heilen ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide. Kernwirkung: Laut SRD: Choose a Kreatur that you can see in Reichweite. A surge of positive energy washes through the Kreatur, causing it to regain 70 hit points. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "heroes_feast",
    name: "Heldenmahl",
    nameEn: "Heroes' Feast",
    hook: "Heldenmahl: Grad 6, Beschwörung — 10 Minuten, 9 Meter.",
    description: "Heldenmahl ist ein Zauber des 6. Grades (Beschwörung). Wirkungszeit: 10 Minuten. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A gem-encrusted bowl worth at least 1,000gp, which the spell consumes.). Listen: kleriker, druide. Kernwirkung: Du bring forth a great feast, including magnificent food and drink. The feast takes 1 hour to consume and disappears at the end of that time, and the beneficial effects don't set in until this hour is over.",
    source: SRD_SOURCE,
    level: 6,
    school: "conjuration",
    castingTime: "10 Minuten",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine juwelenbesetzte Schale im Wert von mindestens 1000 KM, die der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "instant_summons",
    name: "Sofortige Beschwörung",
    nameEn: "Instant Summons",
    hook: "Sofortige Beschwörung: Grad 6, Beschwörung — 1 Minute, Berührung.",
    description: "Sofortige Beschwörung ist ein Zauber des 6. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A sapphire worth 1,000 gp.). Listen: zauberer. Kernwirkung: Du berührst an object weighing 10 pounds or less whose longest dimension is 1.8 Meter or less. The spell leaves an invisible mark on its surface and invisibly inscribes the name of the item on the sapphire you use as the material component.",
    source: SRD_SOURCE,
    level: 6,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Saphir im Wert von 1000 KM" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: true,
    lists: ["zauberer"],
  },
  {
    key: "irresistible_dance",
    name: "Unwiderstehlicher Tanz",
    nameEn: "Irresistible Dance",
    hook: "Unwiderstehlicher Tanz: Grad 6, Verzauberung — Aktion, 9 Meter.",
    description: "Unwiderstehlicher Tanz ist ein Zauber des 6. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V. Listen: barde, zauberer. Kernwirkung: Laut SRD: Choose one Kreatur that you can see in Reichweite. The target begins a comic dance in place: shuffling, tapping its feet, and capering für die Dauer.",
    source: SRD_SOURCE,
    level: 6,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "magic_jar",
    name: "Magischer Krug",
    nameEn: "Magic Jar",
    hook: "Magischer Krug: Grad 6, Nekromantie — 1 Minute, Selbst.",
    description: "Magischer Krug ist ein Zauber des 6. Grades (Nekromantie). Wirkungszeit: 1 Minute. Reichweite: Selbst. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A gem, crystal, reliquary, or some other ornamental container worth at least 500 gp.). Listen: zauberer. Kernwirkung: Dein body falls into a catatonic state as dein soul leaves it and enters the container you used for the spell's material component. While dein soul inhabits the container, you are aware of dein surroundings as if you were in the container's space.",
    source: SRD_SOURCE,
    level: 6,
    school: "necromancy",
    castingTime: "1 Minute",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Edelstein, Kristall, Reliquiar oder ein anderer Zierbehälter im Wert von mindestens 500 KM" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "mass_suggestion",
    name: "Massensuggestion",
    nameEn: "Mass Suggestion",
    hook: "Massensuggestion: Grad 6, Verzauberung — Aktion, 18 Meter.",
    description: "Massensuggestion ist ein Zauber des 6. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 24 Stunden. Komponenten: V, M (Material: A snake's tongue and either a bit of honeycomb or a drop of sweet oil.). Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du suggest a course of activity (limited to a sentence or two) and magically influence up to twelve Kreaturen of dein choice that you can see in Reichweite and that can hear and understand you. Creatures that can't be charmed are immune to this effect. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: "eine Schlangenzunge und entweder etwas Honigwabe oder ein Tropfen süßes Öl" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "move_earth",
    name: "Erde bewegen",
    nameEn: "Move Earth",
    hook: "Erde bewegen: Grad 6, Verwandlung — Aktion, 36 Meter.",
    description: "Erde bewegen ist ein Zauber des 6. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 2 Stunden. Komponenten: V, G, M (Material: An iron blade and a small bag containing a mixture of soils-clay, loam, and sand.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: Choose an area of terrain no larger than 12 Meter on a side in Reichweite. Du can reshape dirt, sand, or clay in the area in any manner you choose für die Dauer.",
    source: SRD_SOURCE,
    level: 6,
    school: "transmutation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "eine Eisenklinge und ein kleiner Beutel mit einer Mischung aus Lehm, Humus und Sand" },
    duration: "Konzentration, bis zu 2 Stunden",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "planar_ally",
    name: "Ebenenverbündeter",
    nameEn: "Planar Ally",
    hook: "Ebenenverbündeter: Grad 6, Beschwörung — 10 Minuten, 18 Meter.",
    description: "Ebenenverbündeter ist ein Zauber des 6. Grades (Beschwörung). Wirkungszeit: 10 Minuten. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du beseech an otherworldly entity for aid. The being must be known to you: a god, a primordial, a demon prince, or some other being of cosmic power.",
    source: SRD_SOURCE,
    level: 6,
    school: "conjuration",
    castingTime: "10 Minuten",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "programmed_illusion",
    name: "Programmierte Illusion",
    nameEn: "Programmed Illusion",
    hook: "Programmierte Illusion: Grad 6, Illusion — Aktion, 36 Meter.",
    description: "Programmierte Illusion ist ein Zauber des 6. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A bit of fleece and jade dust worth at least 25 gp.). Listen: barde, zauberer. Kernwirkung: Du create an illusion of an object, a Kreatur, or some other visible phenomenon in Reichweite that activates when a specific condition occurs. The illusion is imperceptible until then.",
    source: SRD_SOURCE,
    level: 6,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "etwas Vlies und Jadestaub im Wert von mindestens 25 KM" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "sunbeam",
    name: "Sonnenstrahl",
    nameEn: "Sunbeam",
    hook: "Sonnenstrahl: Grad 6, Hervorrufung — Aktion, Selbst.",
    description: "Sonnenstrahl ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A magnifying glass.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: A beam of brilliant light flashes out from dein hand in a 1.5 Meter-wide, 18 Meter-long line. Jede Kreatur in the line muss einen constitution saving throw bestehen.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Lupe" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "transport_via_plants",
    name: "Transport durch Pflanzen",
    nameEn: "Transport via Plants",
    hook: "Transport durch Pflanzen: Grad 6, Beschwörung — Aktion, 3 Meter.",
    description: "Transport durch Pflanzen ist ein Zauber des 6. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 3 Meter. Dauer: 1 Runde. Komponenten: V, G. Listen: druide. Kernwirkung: Laut SRD: This spell creates a magical link between a Large or larger inanimate plant in Reichweite and another plant, at any distance, on the same plane of existence. Du must have seen or touched the destination plant at least once before.",
    source: SRD_SOURCE,
    level: 6,
    school: "conjuration",
    castingTime: "Aktion",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "true_seeing",
    name: "Wahrer Blick",
    nameEn: "True Seeing",
    hook: "Wahrer Blick: Grad 6, Erkenntnis — Aktion, Berührung.",
    description: "Wahrer Blick ist ein Zauber des 6. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G, M (Material: An ointment for the eyes that costs 25gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: This spell gives the willing Kreatur you touch the ability to see things as they actually are. For the duration, the Kreatur has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane, all out to a range of 36 Meter.",
    source: SRD_SOURCE,
    level: 6,
    school: "divination",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Augensalbe für 25 KM aus Pilzpulver, Safran und Fett; wird vom Zauber verbraucht" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "wall_of_ice",
    name: "Eiswall",
    nameEn: "Wall of Ice",
    hook: "Eiswall: Grad 6, Hervorrufung — Aktion, 36 Meter.",
    description: "Eiswall ist ein Zauber des 6. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A small piece of quartz.). Listen: zauberer. Kernwirkung: Du create a wall of ice on a solid surface in Reichweite. Du can form it into a hemispherical dome or a sphere with a radius of up to 3 Meter, or you can shape a flat surface made up of ten 3 Meter-square panels. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 6,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein kleines Stück Quarz" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
];
