/**
 * Zauber des 1. Grades, Teil 1: Alarm bis Fog Cloud.
 *
 * Die Aufteilung ist rein mechanisch — 57 Zauber passen nicht in eine Datei,
 * die unter der Zeilengrenze bleibt. `spells-level1.ts` setzt beide Hälften
 * wieder zusammen; niemand außerhalb dieser Datei kennt den Schnitt.
 *
 * Herkunft: SRD 5.2.1 (CC-BY-4.0, Wizards of the Coast), Regeln von 2024.
 * Mechanik — Grad, Schule, Zeit, Reichweite, Komponenten, Dauer und vor allem
 * `lists` — ist 1:1 aus dem SRD übernommen; `lists` steuert den Zauberschritt,
 * eine falsche Liste zeigt einem Spieler Zauber, die er nicht wirken kann.
 *
 * Deutsch ist Übersetzung, nicht Zitat: Ein deutsches SRD gibt es nicht, daher
 * sind `name`, `hook` und `description` UWEs eigene Fassung. `nameEn` hält den
 * Originalnamen, damit der Abgleich gegen die Quelle möglich bleibt.
 * Entfernungen stehen wie im übrigen Katalog in Metern (1,5 m je 5 Fuß).
 */

import { SRD_SOURCE, type Spell } from "../types";

/** Alarm … Fog Cloud (28 Zauber), alphabetisch nach dem englischen Namen. */
export const LEVEL1_SPELLS_A_F: Spell[] = [
  {
    key: "alarm",
    name: "Alarm",
    nameEn: "Alarm",
    hook: "Acht Stunden Wache, die niemand halten muss.",
    description: "Du sicherst eine Tür, ein Fenster oder einen Bereich in 9 Metern, der höchstens einen Würfel von 6 Metern Kantenlänge füllt. Berührt oder betritt eine Kreatur den Bereich, schlägt der Alarm an; beim Wirken benennst du Kreaturen, die ihn nicht auslösen. Du wählst hörbar — zehn Sekunden Handglockenklang im Umkreis von 18 Metern — oder mental: ein gedanklicher Stoß, der dich noch auf eine Meile Entfernung erreicht und aus dem Schlaf holt.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "1 Minute oder Ritual",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Glocke und Silberdraht" },
    duration: "8 Stunden",
    concentration: false,
    ritual: true,
    lists: ["waldlaeufer", "zauberer", "erfinder"],
  },
  {
    key: "tierfreundschaft",
    name: "Tierfreundschaft",
    nameEn: "Animal Friendship",
    hook: "Ein Tier hält dich einen ganzen Tag lang für einen Freund.",
    description: "Du zielst auf ein sichtbares Tier in 9 Metern. Es muss einen Weisheits-Rettungswurf bestehen oder ist für die Dauer bezaubert. Fügst du oder ein Verbündeter ihm Schaden zu, endet der Zauber. Mit einem höheren Zauberplatz zielst du je Grad auf ein weiteres Tier.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Happen Futter" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide", "waldlaeufer"],
  },
  {
    key: "fluch",
    name: "Fluch",
    nameEn: "Bane",
    hook: "Drei Feinde ziehen einen W4 von jedem Angriff und jedem Rettungswurf ab.",
    description: "Bis zu drei sichtbare Kreaturen deiner Wahl in 9 Metern machen je einen Charisma-Rettungswurf. Wer scheitert, zieht bis zum Ende des Zaubers 1W4 von jedem Angriffswurf und jedem Rettungswurf ab. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Blut" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "kleriker", "hexenpakt_magier"],
  },
  {
    key: "segen",
    name: "Segen",
    nameEn: "Bless",
    hook: "Das Gegenstück zum Fluch: drei Verbündete addieren einen W4 auf Angriffe und Rettungswürfe.",
    description: "Du segnest bis zu drei Kreaturen in 9 Metern. Bis der Zauber endet, addiert jede von ihnen 1W4 auf jeden Angriffswurf und jeden Rettungswurf. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein heiliges Symbol im Wert von mindestens 5 GM" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "paladin"],
  },
  {
    key: "brennende_haende",
    name: "Brennende Hände",
    nameEn: "Burning Hands",
    hook: "Ein Flammenkegel aus den Fingerspitzen — der erste Flächenzauber, den man lernt.",
    description: "Aus deinen Händen schießt eine dünne Flammenwand. Jede Kreatur in einem Kegel von 4,5 Metern macht einen Geschicklichkeits-Rettungswurf und nimmt bei Misserfolg 3W6 Feuerschaden, bei Erfolg die Hälfte. Brennbare Gegenstände im Kegel, die niemand trägt, fangen Feuer. Je höherem Zauberplatz steigt der Schaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "person_bezaubern",
    name: "Person bezaubern",
    nameEn: "Charm Person",
    hook: "Eine Stunde lang hält dich ein Humanoider für freundlich gesinnt — bis du ihn angreifst.",
    description: "Ein sichtbarer Humanoider in 9 Metern macht einen Weisheits-Rettungswurf, mit Vorteil, falls ihr gerade gegeneinander kämpft. Bei Misserfolg ist er für die Dauer bezaubert und dir gegenüber freundlich gesinnt. Der Zauber endet, sobald du oder deine Verbündeten ihm Schaden zufügen; danach weiß das Ziel, dass du es bezaubert hast. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "chromatische_kugel",
    name: "Chromatische Kugel",
    nameEn: "Chromatic Orb",
    hook: "3W8 Schaden im Element deiner Wahl — und bei Würfelpaaren springt die Kugel weiter.",
    description: "Du schleuderst eine Energiekugel auf ein Ziel in 27 Metern und wählst Säure, Kälte, Feuer, Blitz, Gift oder Schall. Mach einen Fernkampf-Zauberangriff; bei einem Treffer nimmt das Ziel 3W8 Schaden des gewählten Typs. Zeigen zwei oder mehr der W8 dieselbe Zahl, springt die Kugel auf ein anderes Ziel deiner Wahl in 9 Metern über — mit neuem Angriffs- und Schadenswurf. Ohne höheren Zauberplatz springt sie nur einmal. Je höherem Zauberplatz steigt der Schaden um 1W8.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "ein Diamant im Wert von mindestens 50 GM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "farbspruehen",
    name: "Farbsprühen",
    nameEn: "Color Spray",
    hook: "Ein Lichtblitz, der alles im Kegel für eine Runde blind macht.",
    description: "Ein grelles Spiel blitzender Farben schießt aus deinen Händen. Jede Kreatur in einem Kegel von 4,5 Metern muss einen Konstitutions-Rettungswurf bestehen oder ist bis zum Ende deines nächsten Zuges blind.",
    source: SRD_SOURCE,
    level: 1,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Prise bunter Sand" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "befehl",
    name: "Befehl",
    nameEn: "Command",
    hook: "Ein einziges Wort, dem eine Kreatur in ihrem nächsten Zug folgen muss.",
    description: "Du sprichst einer sichtbaren Kreatur in 18 Metern ein Wort zu. Bei einem misslungenen Weisheits-Rettungswurf befolgt sie es in ihrem nächsten Zug. Zur Wahl stehen: Herkommen (sie geht auf kürzestem Weg zu dir), Fallenlassen (sie lässt fallen, was sie hält), Fliehen (sie entfernt sich so schnell wie möglich), Kriechen (sie geht zu Boden) und Halt (sie bewegt sich nicht und nimmt weder Aktion noch Bonusaktion). Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "kleriker", "paladin"],
  },
  {
    key: "sprachen_verstehen",
    name: "Sprachen verstehen",
    nameEn: "Comprehend Languages",
    hook: "Eine Stunde lang verstehst du jede gesprochene und geschriebene Sprache.",
    description: "Bis der Zauber endet, verstehst du die wörtliche Bedeutung jeder Sprache, die du hörst oder als Gebärde siehst. Geschriebenes verstehst du ebenfalls, musst dabei aber die Oberfläche berühren; eine Seite dauert etwa eine Minute. Chiffren und Geheimbotschaften entschlüsselt der Zauber nicht.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Aktion oder Ritual",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Prise Ruß und Salz" },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "wasser_erschaffen_oder_vernichten",
    name: "Wasser erschaffen oder vernichten",
    nameEn: "Create or Destroy Water",
    hook: "Rund vierzig Liter Wasser aus dem Nichts — oder weg damit, samt Nebel.",
    description: "Du erschaffst rund 40 Liter sauberes Wasser in einem offenen Behälter in 9 Metern, oder du lässt es als Regen in einem Würfel von 9 Metern Kantenlänge fallen und löschst dort offene Flammen. Alternativ vernichtest du dieselbe Menge Wasser in einem offenen Behälter oder den Nebel in einem solchen Würfel. Je höherem Zauberplatz kommen weitere 40 Liter dazu oder der Würfel wächst um 1,5 Meter.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Mischung aus Wasser und Sand" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "wunden_heilen",
    name: "Wunden heilen",
    nameEn: "Cure Wounds",
    hook: "Der Heilzauber per Berührung: 2W8 plus Attributsmodifikator zurück.",
    description: "Eine Kreatur, die du berührst, erhält Trefferpunkte in Höhe von 2W8 plus deinem Zauberattributsmodifikator zurück. Je höherem Zauberplatz steigt die Heilung um 2W8.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "kleriker", "druide", "paladin", "waldlaeufer", "erfinder"],
  },
  {
    key: "gut_und_boese_entdecken",
    name: "Gut und Böse entdecken",
    nameEn: "Detect Evil and Good",
    hook: "Zehn Minuten lang spürst du Aberrationen, Himmlische, Elementare, Feen, Unholde und Untote in der Nähe.",
    description: "Bis der Zauber endet, spürst du den Ort jeder Aberration, jedes Himmlischen, Elementars, Feenwesens, Unholds und Untoten im Umkreis von 9 Metern. Du merkst außerdem, ob dort ein Weihezauber wirkt und wo. Dreißig Zentimeter Stein, Erde oder Holz, zweieinhalb Zentimeter Metall oder eine dünne Bleischicht blockieren den Zauber.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "paladin"],
  },
  {
    key: "magie_entdecken",
    name: "Magie entdecken",
    nameEn: "Detect Magic",
    hook: "Der Zauber, den man am häufigsten als Ritual wirkt: Was hier ist magisch?",
    description: "Bis der Zauber endet, spürst du magische Effekte im Umkreis von 9 Metern. Mit einer Magieaktion siehst du eine schwache Aura um jede sichtbare Kreatur und jedes sichtbare Objekt, das Magie trägt, und erkennst bei Zaubern die Schule. Dreißig Zentimeter Stein, Erde oder Holz, zweieinhalb Zentimeter Metall oder eine dünne Bleischicht blockieren den Zauber.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Aktion oder Ritual",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: true,
    lists: ["barde", "kleriker", "druide", "paladin", "waldlaeufer", "hexenmeister", "hexenpakt_magier", "zauberer", "erfinder"],
  },
  {
    key: "gift_und_krankheit_entdecken",
    name: "Gift und Krankheit entdecken",
    nameEn: "Detect Poison and Disease",
    hook: "Ist das Essen vergiftet? Der Zauber sagt es dir, bevor jemand probiert.",
    description: "Bis der Zauber endet, spürst du Gifte, giftige Kreaturen und magische Seuchen im Umkreis von 9 Metern und erkennst in jedem Fall die Art. Dreißig Zentimeter Stein, Erde oder Holz, zweieinhalb Zentimeter Metall oder eine dünne Bleischicht blockieren den Zauber.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Aktion oder Ritual",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Eibenblatt" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: true,
    lists: ["kleriker", "druide", "paladin", "waldlaeufer"],
  },
  {
    key: "selbstverkleidung",
    name: "Selbstverkleidung",
    nameEn: "Disguise Self",
    hook: "Ein anderes Gesicht für eine Stunde — solange niemand hinfasst.",
    description: "Du lässt dich selbst samt Kleidung, Rüstung, Waffen und Gepäck anders aussehen. Du kannst 30 Zentimeter größer oder kleiner, schwerer oder leichter wirken, musst aber dieselbe Grundanordnung von Gliedmaßen behalten. Der Trug hält keiner Berührung stand: Gegenstände gleiten durch einen aufgesetzten Hut hindurch. Wer dich durchschauen will, braucht eine Untersuchen-Aktion und eine gelungene Intelligenzprobe (Nachforschen) gegen deinen Zauberrettungswurf-SG.",
    source: SRD_SOURCE,
    level: 1,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer", "erfinder"],
  },
  {
    key: "dissonantes_fluestern",
    name: "Dissonantes Flüstern",
    nameEn: "Dissonant Whispers",
    hook: "Eine Melodie im Kopf des Ziels, die weh tut und es zur Flucht zwingt.",
    description: "Eine sichtbare Kreatur deiner Wahl in 18 Metern hört eine schrille Melodie in ihrem Geist und macht einen Weisheits-Rettungswurf. Bei Misserfolg nimmt sie 3W6 psychischen Schaden und muss sofort ihre Reaktion nutzen, um sich auf dem sichersten Weg so weit wie möglich von dir zu entfernen. Bei Erfolg nur der halbe Schaden. Je höherem Zauberplatz steigt der Schaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde"],
  },
  {
    key: "goettliche_gunst",
    name: "Göttliche Gunst",
    nameEn: "Divine Favor",
    hook: "Eine Minute lang trägt jeder deiner Waffentreffer zusätzlichen gleißenden Schaden.",
    description: "Bis der Zauber endet, verursachen deine Angriffe mit Waffen bei einem Treffer 1W4 zusätzlichen gleißenden Schaden.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["paladin"],
  },
  {
    key: "goettliches_schmettern",
    name: "Göttliches Schmettern",
    nameEn: "Divine Smite",
    hook: "Der Paladin-Moment: einen Zauberplatz verbrennen und den Treffer in gleißenden Schaden verwandeln.",
    description: "Du wirkst den Zauber unmittelbar nach einem Treffer mit einer Nahkampfwaffe oder einem waffenlosen Schlag. Das Ziel nimmt zusätzlich 2W8 gleißenden Schaden, gegen Unholde und Untote 1W8 mehr. Je höherem Zauberplatz steigt der Schaden um 1W8.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Bonusaktion, unmittelbar nachdem du ein Ziel mit einer Nahkampfwaffe oder einem waffenlosen Schlag getroffen hast",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["paladin"],
  },
  {
    key: "umgarnender_schlag",
    name: "Umgarnender Schlag",
    nameEn: "Ensnaring Strike",
    hook: "Ranken schießen aus dem Treffer und halten das Ziel fest.",
    description: "Du wirkst den Zauber unmittelbar nach einem Waffentreffer. Ranken umschlingen das Ziel; es macht einen Stärke-Rettungswurf, große und größere Kreaturen mit Vorteil. Bei Misserfolg ist es festgesetzt und nimmt zu Beginn jedes seiner Züge 1W6 Stichschaden. Das Ziel oder eine Kreatur in Reichweite kann sich mit einer Aktion und einer Stärkeprobe (Athletik) gegen deinen Zauberrettungswurf-SG befreien. Je höherem Zauberplatz steigt der Schaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Bonusaktion, unmittelbar nachdem du eine Kreatur mit einer Waffe getroffen hast",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["waldlaeufer"],
  },
  {
    key: "verstricken",
    name: "Verstricken",
    nameEn: "Entangle",
    hook: "Sechs mal sechs Meter Boden werden zu greifenden Pflanzen.",
    description: "Auf einer Fläche von 6 mal 6 Metern in 27 Metern sprießen greifende Pflanzen aus dem Boden und machen sie für die Dauer zu schwierigem Gelände. Jede Kreatur außer dir, die beim Wirken darin steht, muss einen Stärke-Rettungswurf bestehen oder ist festgesetzt. Eine festgesetzte Kreatur befreit sich mit einer Aktion und einer gelungenen Stärkeprobe (Athletik) gegen deinen Zauberrettungswurf-SG.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "waldlaeufer"],
  },
  {
    key: "eiliger_rueckzug",
    name: "Eiliger Rückzug",
    nameEn: "Expeditious Retreat",
    hook: "Spurten als Bonusaktion, zehn Minuten lang.",
    description: "Du nimmst die Spurten-Aktion und darfst sie bis zum Ende des Zaubers in jedem Zug erneut als Bonusaktion nehmen.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer", "erfinder"],
  },
  {
    key: "feenfeuer",
    name: "Feenfeuer",
    nameEn: "Faerie Fire",
    hook: "Alles im Würfel leuchtet — und wird deutlich leichter zu treffen.",
    description: "Objekte in einem Würfel von 6 Metern Kantenlänge in 18 Metern werden blau, grün oder violett umrissen; Kreaturen darin ebenso, wenn sie einen Geschicklichkeits-Rettungswurf nicht bestehen. Betroffene strahlen schwaches Licht im Umkreis von 3 Metern ab und können nicht vom Zustand Unsichtbar profitieren. Angriffe gegen sie haben Vorteil, solange der Angreifer sie sehen kann.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "druide", "erfinder"],
  },
  {
    key: "falsches_leben",
    name: "Falsches Leben",
    nameEn: "False Life",
    hook: "Ein Puffer aus temporären Trefferpunkten, bevor es losgeht.",
    description: "Du erhältst 2W4 + 4 temporäre Trefferpunkte. Je höherem Zauberplatz kommen 5 weitere dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Tropfen Alkohol" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer", "erfinder"],
  },
  {
    key: "federfall",
    name: "Federfall",
    nameEn: "Feather Fall",
    hook: "Die Reaktion, die einen Sturz aus jeder Höhe folgenlos macht — für bis zu fünf Leute.",
    description: "Du wirkst den Zauber als Reaktion, wenn du oder eine sichtbare Kreatur in 18 Metern fällt. Bis zu fünf fallende Kreaturen in Reichweite sinken nur noch 18 Meter pro Runde. Landet eine von ihnen, bevor der Zauber endet, nimmt sie keinen Fallschaden, und der Zauber endet für sie.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Reaktion, wenn du oder eine sichtbare Kreatur in 18 Metern fällt",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: "eine kleine Feder oder etwas Daunen" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer", "erfinder"],
  },
  {
    key: "vertrauten_herbeirufen",
    name: "Vertrauten herbeirufen",
    nameEn: "Find Familiar",
    hook: "Ein Tiergeist, der für dich späht, Berührungszauber überbringt und nie ganz stirbt.",
    description: "Du gewinnst die Dienste eines Vertrauten in einer Tiergestalt deiner Wahl — Fledermaus, Katze, Frosch, Falke, Echse, Krake, Eule, Ratte, Rabe, Spinne, Wiesel oder ein anderes Tier mit Herausforderungsgrad 0. Er hat die Werte dieser Gestalt, ist aber ein Himmlischer, ein Feenwesen oder ein Unhold. Innerhalb von 30 Metern sprichst du telepathisch mit ihm und siehst als Bonusaktion durch seine Augen. Wirkst du einen Zauber mit Reichweite Berührung, kann er ihn überbringen. Angreifen kann er nicht; fällt er auf 0 Trefferpunkte, verschwindet er und kehrt beim nächsten Wirken zurück.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "1 Stunde oder Ritual",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "brennender Weihrauch im Wert von mindestens 10 GM, den der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["zauberer"],
  },
  {
    key: "schwebende_scheibe",
    name: "Schwebende Scheibe",
    nameEn: "Floating Disk",
    hook: "Ein Packesel aus reiner Kraft: 500 Pfund Gepäck, die dir eine Stunde lang folgen.",
    description: "Eine kreisrunde, waagerechte Kraftfläche von knapp einem Meter Durchmesser schwebt einen Meter über dem Boden an einem freien Punkt in 9 Metern und trägt bis zu 500 Pfund. Wird sie stärker beladen, endet der Zauber und alles fällt zu Boden. Solange du innerhalb von 6 Metern bleibst, steht sie still; entfernst du dich weiter, folgt sie dir. Höhenunterschiede von 3 Metern oder mehr überwindet sie nicht, und mehr als 30 Meter Abstand beenden den Zauber.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion oder Ritual",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Quecksilber" },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["zauberer"],
  },
  {
    key: "nebelwolke",
    name: "Nebelwolke",
    nameEn: "Fog Cloud",
    hook: "Eine Nebelkugel, in der niemand mehr etwas sieht — auch du nicht.",
    description: "An einem Punkt in 36 Metern entsteht eine Nebelkugel mit 6 Metern Radius; der Bereich ist stark verschleiert. Sie hält bis zum Ende des Zaubers oder bis starker Wind sie zerstreut. Je höherem Zauberplatz wächst der Radius um 6 Meter.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "waldlaeufer", "hexenmeister", "zauberer"],
  },
];
