/**
 * SRD-Zauber Grad 2 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL2_SPELLS_B: Spell[] = [
  {
    key: "knock",
    name: "Klopfen",
    nameEn: "Knock",
    hook: "Klopfen: Grad 2, Verwandlung — Aktion, 18 Meter.",
    description: "Klopfen ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: barde, hexenmeister, zauberer. Kernwirkung: Laut SRD: Choose an object that you can see in Reichweite. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "lesser_restoration",
    name: "Geringe Wiederherstellung",
    nameEn: "Lesser Restoration",
    hook: "Geringe Wiederherstellung: Grad 2, Abwehr — Aktion, Berührung.",
    description: "Geringe Wiederherstellung ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer, barde. Kernwirkung: Du berührst eine Kreatur and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "barde"],
  },
  {
    key: "levitate",
    name: "Schweben",
    nameEn: "Levitate",
    hook: "Schweben: Grad 2, Verwandlung — Aktion, 18 Meter.",
    description: "Schweben ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: Either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end.). Listen: hexenmeister, zauberer. Kernwirkung: One Kreatur or object of dein choice that you can see in Reichweite rises vertically, up to 6 Meter, and remains suspended there für die Dauer. The spell can levitate a target that weighs up to 500 pounds.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "entweder eine kleine Lederschlaufe oder ein Stück Golddraht, zu einer Becherform mit langem Schaft gebogen" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "locate_animals_or_plants",
    name: "Tiere oder Pflanzen orten",
    nameEn: "Locate Animals or Plants",
    hook: "Tiere oder Pflanzen orten: Grad 2, Erkenntnis — Aktion, Selbst.",
    description: "Tiere oder Pflanzen orten ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A bit of fur from a bloodhound.). Listen: druide, waldlaeufer, barde. Kernwirkung: Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in dein surroundings, you learn the direction and distance to the closest Kreatur or plant of that kind within 5 miles, if any are present.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "etwas Fell eines Bluthundes" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["druide", "waldlaeufer", "barde"],
  },
  {
    key: "locate_object",
    name: "Objekt orten",
    nameEn: "Locate Object",
    hook: "Objekt orten: Grad 2, Erkenntnis — Aktion, Selbst.",
    description: "Objekt orten ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A forked twig.). Listen: kleriker, druide, waldlaeufer, barde, zauberer. Kernwirkung: Describe or name an object that is familiar to you. Du sense the direction to the object's location, as long as that object is within 1,0 Meter of you.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein gegabelter Zweig" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer", "barde", "zauberer"],
  },
  {
    key: "magic_mouth",
    name: "Magischer Mund",
    nameEn: "Magic Mouth",
    hook: "Magischer Mund: Grad 2, Illusion — 1 Minute, 9 Meter.",
    description: "Magischer Mund ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: 1 Minute. Reichweite: 9 Meter. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A small bit of honeycomb and jade dust worth at least 10 gp, which the spell consumes). Listen: barde, zauberer. Kernwirkung: Du implant a message within an object in range, a message that is uttered when a trigger condition is met. Choose an object that you can see and that isn't being worn or carried by another Kreatur.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "1 Minute",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "etwas Honigwabe und Jadestaub im Wert von mindestens 10 KM, die der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: true,
    lists: ["barde", "zauberer"],
  },
  {
    key: "magic_weapon",
    name: "Magische Waffe",
    nameEn: "Magic Weapon",
    hook: "Magische Waffe: Grad 2, Verwandlung — Bonusaktion, Berührung.",
    description: "Magische Waffe ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Bonusaktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: kleriker, zauberer. Kernwirkung: Du berührst a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus to attack rolls and Schaden rolls. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Bonusaktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "zauberer"],
  },
  {
    key: "mirror_image",
    name: "Spiegelbild",
    nameEn: "Mirror Image",
    hook: "Spiegelbild: Grad 2, Illusion — Aktion, Selbst.",
    description: "Spiegelbild ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 1 Minute. Komponenten: V, G. Listen: kleriker, druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Three illusionary duplicates of yourself appear in dein space. Until the end of the spell, duplicates move with you and imitate dein actions, swapping their position so that it is impossible to determine which image is real.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "misty_step",
    name: "Nebelhaftiger Schritt",
    nameEn: "Misty Step",
    hook: "Nebelhaftiger Schritt: Grad 2, Beschwörung — Bonusaktion, Selbst.",
    description: "Nebelhaftiger Schritt ist ein Zauber des 2. Grades (Beschwörung). Wirkungszeit: Bonusaktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V. Listen: druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Briefly surrounded by silvery mist, you teleport up to 9 Meter to an unoccupied space that you can see.",
    source: SRD_SOURCE,
    level: 2,
    school: "conjuration",
    castingTime: "Bonusaktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "moonbeam",
    name: "Mondstrahl",
    nameEn: "Moonbeam",
    hook: "Mondstrahl: Grad 2, Hervorrufung — Aktion, 36 Meter.",
    description: "Mondstrahl ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: Several seeds of any moonseed plant and a piece of opalescent feldspar.). Listen: druide. Kernwirkung: Laut SRD: A silvery beam of pale light shines down in a 1.5 Meter-radius, 12 Meter-high cylinder centered on a point in Reichweite. Until the spell ends, dim light fills the cylinder. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "mehrere Samen einer Mondsamenpflanze und ein Stück opalisierender Feldspat" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "pass_without_trace",
    name: "Spurlos gehen",
    nameEn: "Pass without Trace",
    hook: "Spurlos gehen: Grad 2, Abwehr — Aktion, Selbst.",
    description: "Spurlos gehen ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: Ashes from a burned leaf of mistletoe and a sprig of spruce.). Listen: kleriker, druide, waldlaeufer. Kernwirkung: Laut SRD: A veil of shadows and silence radiates from you, masking you and dein companions from detection. For the duration, each Kreatur you choose within 9 Meter of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can't be tracked except by magical means.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "Asche eines verbrannten Mistelblatts und ein Fichtenzweig" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "prayer_of_healing",
    name: "Gebet der Heilung",
    nameEn: "Prayer of Healing",
    hook: "Gebet der Heilung: Grad 2, Hervorrufung — 10 Minuten, 9 Meter.",
    description: "Gebet der Heilung ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: 10 Minuten. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: kleriker. Kernwirkung: Up to six Kreaturen of dein choice that you can see in Reichweite each regain hit points equal to 2d8 + dein spellcasting ability modifier. This spell has no effect on undead or constructs. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "10 Minuten",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "protection_from_poison",
    name: "Schutz vor Gift",
    nameEn: "Protection from Poison",
    hook: "Schutz vor Gift: Grad 2, Abwehr — Aktion, Berührung.",
    description: "Schutz vor Gift ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer. Kernwirkung: Du berührst eine Kreatur. If it is poisoned, you neutralize the poison.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "ray_of_enfeeblement",
    name: "Strahl der Schwäche",
    nameEn: "Ray of Enfeeblement",
    hook: "Strahl der Schwäche: Grad 2, Nekromantie — Aktion, 18 Meter.",
    description: "Strahl der Schwäche ist ein Zauber des 2. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: A black beam of enervating energy springs from dein finger toward a Kreatur in Reichweite. Mache einen Fernkampf-Zauberangriff gegen das Ziel.",
    source: SRD_SOURCE,
    level: 2,
    school: "necromancy",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "rope_trick",
    name: "Seiltrick",
    nameEn: "Rope Trick",
    hook: "Seiltrick: Grad 2, Verwandlung — Aktion, Berührung.",
    description: "Seiltrick ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G, M (Material: Powdered corn extract and a twisted loop of parchment.). Listen: zauberer. Kernwirkung: Du berührst a length of rope that is up to 18 Meter long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "pulverisiertes Maisextrakt und eine verdrehte Pergamentschlaufe" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "scorching_ray",
    name: "Sengender Strahl",
    nameEn: "Scorching Ray",
    hook: "Sengender Strahl: Grad 2, Hervorrufung — Aktion, 36 Meter.",
    description: "Sengender Strahl ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du create three rays of fire and hurl them at targets in Reichweite. Du can hurl them at one target or several. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "see_invisibility",
    name: "Unsichtbares sehen",
    nameEn: "See Invisibility",
    hook: "Unsichtbares sehen: Grad 2, Erkenntnis — Aktion, Selbst.",
    description: "Unsichtbares sehen ist ein Zauber des 2. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 1 Stunde. Komponenten: V, G, M (Material: A dash of talc and a small amount of silver powder.). Listen: barde, hexenmeister, zauberer. Kernwirkung: For the duration of the spell, you see invisible Kreaturen and objects as if they were visible, and you can see through Ethereal. The ethereal objects and Kreaturen appear ghostly translucent.",
    source: SRD_SOURCE,
    level: 2,
    school: "divination",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "eine Prise Talkum und etwas Silberpulver" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "shatter",
    name: "Zerbersten",
    nameEn: "Shatter",
    hook: "Zerbersten: Grad 2, Hervorrufung — Aktion, 18 Meter.",
    description: "Zerbersten ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A burst of mica.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: A sudden loud ringing noise, painfully intense, erupts from a point of dein choice in Reichweite. Jede Kreatur in a 10-­--foot-­--radius sphere centered on that point muss einen Constitution saving throw bestehen. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "etwas Glimmer" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "silence",
    name: "Stille",
    nameEn: "Silence",
    hook: "Stille: Grad 2, Illusion — Aktion, 36 Meter.",
    description: "Stille ist ein Zauber des 2. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer, barde. Kernwirkung: For the duration, no sound can be created within or pass through a 6 Meter-radius sphere centered on a point you choose in Reichweite. Any Kreatur or object entirely inside the sphere is immune to Donnerschaden, and Kreaturen are deafened while entirely inside it.",
    source: SRD_SOURCE,
    level: 2,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: true,
    lists: ["kleriker", "druide", "waldlaeufer", "barde"],
  },
  {
    key: "spider_climb",
    name: "Spinnenklettern",
    nameEn: "Spider Climb",
    hook: "Spinnenklettern: Grad 2, Verwandlung — Aktion, Berührung.",
    description: "Spinnenklettern ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A drop of bitumen and a spider.). Listen: druide, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: Until the spell ends, one willing Kreatur you touch gains the ability to move up, down, and across vertical surfaces and upside down along ceilings, while leaving its hands free. The target also gains a climbing speed equal to its walking speed.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Tropfen Bitumen und eine Spinne" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "spike_growth",
    name: "Stachelwuchs",
    nameEn: "Spike Growth",
    hook: "Stachelwuchs: Grad 2, Verwandlung — Aktion, 45 Meter.",
    description: "Stachelwuchs ist ein Zauber des 2. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: Seven sharp spines or seven twigs cut peak.). Listen: kleriker, druide, waldlaeufer. Kernwirkung: Laut SRD: The ground in a 6 Meter radius centered on a point in Reichweite twists and sprouts hard spikes and thorns. The area becomes difficult terrain für die Dauer.",
    source: SRD_SOURCE,
    level: 2,
    school: "transmutation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "sieben scharfe Stacheln oder sieben zugespitzte Zweige" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "spiritual_weapon",
    name: "Geistige Waffe",
    nameEn: "Spiritual Weapon",
    hook: "Geistige Waffe: Grad 2, Hervorrufung — Bonusaktion, 18 Meter.",
    description: "Geistige Waffe ist ein Zauber des 2. Grades (Hervorrufung). Wirkungszeit: Bonusaktion. Reichweite: 18 Meter. Dauer: 1 Minute. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du create a floating, spectral weapon in Reichweite that lasts für die Dauer or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a Kreatur within 1.5 Meter of the weapon. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 2,
    school: "evocation",
    castingTime: "Bonusaktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "suggestion",
    name: "Eingebung",
    nameEn: "Suggestion",
    hook: "Eingebung: Grad 2, Verzauberung — Aktion, 9 Meter.",
    description: "Eingebung ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 8 Stunden. Komponenten: V, M (Material: A snake's tongue and either a bit of honeycomb or a drop of sweet oil.). Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du suggest a course of activity (limited to a sentence or two) and magically influence a Kreatur you can see in Reichweite that can hear and understand you. Creatures that can't be charmed are immune to this effect.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: "eine Schlangenzunge und entweder etwas Honigwabe oder ein Tropfen süßes Öl" },
    duration: "Konzentration, bis zu 8 Stunden",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "warding_bond",
    name: "Schutzbund",
    nameEn: "Warding Bond",
    hook: "Schutzbund: Grad 2, Abwehr — Aktion, Berührung.",
    description: "Schutzbund ist ein Zauber des 2. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G, M (Material: A pair of platinum rings worth at least 50gp each, which you and the target must wear for the duration.). Listen: kleriker. Kernwirkung: Laut SRD: This spell wards a willing Kreatur you touch and creates a mystic connection between you and the target bis der Zauber endet. While the target is within 18 Meter of you, it gains a +1 bonus to AC and saving throws, and it has resistance to all Schaden.",
    source: SRD_SOURCE,
    level: 2,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Paar Platinringe im Wert von mindestens 50 KM je Stück, die du und das Ziel für die Dauer tragen müsst" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "web",
    name: "Netz",
    nameEn: "Web",
    hook: "Netz: Grad 2, Beschwörung — Aktion, 18 Meter.",
    description: "Netz ist ein Zauber des 2. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A bit of spiderweb.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Du conjure a mass of thick, sticky webbing at a point of dein choice in Reichweite. The webs fill a 6 Meter cube from that point für die Dauer.",
    source: SRD_SOURCE,
    level: 2,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "etwas Spinnwebe" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "zone_of_truth",
    name: "Zone der Wahrheit",
    nameEn: "Zone of Truth",
    hook: "Zone der Wahrheit: Grad 2, Verzauberung — Aktion, 18 Meter.",
    description: "Zone der Wahrheit ist ein Zauber des 2. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 10 Minuten. Komponenten: V, G. Listen: kleriker, barde. Kernwirkung: Du create a magical zone that guards against deception in a 4.5 Meter-radius sphere centered on a point of dein choice in Reichweite. Until the spell ends, a Kreatur that enters the spell's area for the first time on a turn or starts its turn there muss einen Charisma saving throw bestehen.",
    source: SRD_SOURCE,
    level: 2,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde"],
  },
];
