/**
 * SRD-Zauber Grad 9 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL9_SPELLS: Spell[] = [
  {
    key: "astral_projection",
    name: "Astrale Projektion",
    nameEn: "Astral Projection",
    hook: "Astrale Projektion: Grad 9, Nekromantie — 1 Stunde, 3 Meter.",
    description: "Astrale Projektion ist ein Zauber des 9. Grades (Nekromantie). Wirkungszeit: 1 Stunde. Reichweite: 3 Meter. Dauer: besonders. Komponenten: V, G, M (Material: For each creature you affect with this spell, you must provide one jacinth worth at least 1,000gp and one ornately carved bar of silver worth at least 100gp, all of which the spell consumes.). Listen: kleriker, hexenpakt_magier, zauberer. Kernwirkung: Du and up to eight willing Kreaturen in Reichweite project dein astral bodies into the Astral Plane (the spell fails and the casting is wasted if you are already on that plane). The material body you leave behind is unconscious and in a state of suspended animation; it doesn't need food or air and doesn't age.",
    source: SRD_SOURCE,
    level: 9,
    school: "necromancy",
    castingTime: "1 Stunde",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: "für jede betroffene Kreatur ein Hyazinth im Wert von mindestens 1000 KM und ein kunstvoll geschnitzter Silberstab im Wert von mindestens 100 KM; alles wird verbraucht" },
    duration: "besonders",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "foresight",
    name: "Voraussicht",
    nameEn: "Foresight",
    hook: "Voraussicht: Grad 9, Erkenntnis — 1 Minute, Berührung.",
    description: "Voraussicht ist ein Zauber des 9. Grades (Erkenntnis). Wirkungszeit: 1 Minute. Reichweite: Berührung. Dauer: 8 Stunden. Komponenten: V, G, M (Material: A hummingbird feather.). Listen: druide, barde, hexenpakt_magier, zauberer. Kernwirkung: Du berührst eine willige Kreatur and bestow a limited ability to see into the immediate future. For the duration, the target can't be surprised and has advantage on attack rolls, ability checks, and saving throws.",
    source: SRD_SOURCE,
    level: 9,
    school: "divination",
    castingTime: "1 Minute",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Kolibrifeder" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "gate",
    name: "Tor",
    nameEn: "Gate",
    hook: "Tor: Grad 9, Beschwörung — Aktion, 18 Meter.",
    description: "Tor ist ein Zauber des 9. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A diamond worth at least 5,000gp.). Listen: kleriker, hexenmeister, zauberer. Kernwirkung: Du conjure a portal linking an unoccupied space you can see in Reichweite to a precise location on a different plane of existence. The portal is a circular opening, which you can make 5 to 6 Meter in diameter.",
    source: SRD_SOURCE,
    level: 9,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Diamant im Wert von mindestens 5000 KM" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "hexenmeister", "zauberer"],
  },
  {
    key: "imprisonment",
    name: "Einkerkerung",
    nameEn: "Imprisonment",
    hook: "Einkerkerung: Grad 9, Abwehr — 1 Minute, 9 Meter.",
    description: "Einkerkerung ist ein Zauber des 9. Grades (Abwehr). Wirkungszeit: 1 Minute. Reichweite: 9 Meter. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A vellum depiction or a carved statuette in the likeness of the target, and a special component that varies according to the version of the spell you choose, worth at least 500gp per Hit Die of the target.). Listen: hexenpakt_magier, zauberer. Kernwirkung: Du create a magical restraint to hold a Kreatur that you can see in Reichweite. The target muss einen wisdom saving throw bestehen or be bound by the spell; if it succeeds, it is immune to this spell if you cast it again.",
    source: SRD_SOURCE,
    level: 9,
    school: "abjuration",
    castingTime: "1 Minute",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Pergamentdarstellung oder geschnitzte Statuette des Ziels sowie eine besondere Komponente je Version, im Wert von mindestens 500 KM pro Trefferwürfel des Ziels" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["hexenpakt_magier", "zauberer"],
  },
  {
    key: "mass_heal",
    name: "Massenheilung",
    nameEn: "Mass Heal",
    hook: "Massenheilung: Grad 9, Beschwörung — Aktion, 18 Meter.",
    description: "Massenheilung ist ein Zauber des 9. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker. Kernwirkung: Laut SRD: A flood of healing energy flows from you into injured Kreaturen around you. Du restore up to 700 hit points, divided as you choose among any number of Kreaturen that you can see in Reichweite.",
    source: SRD_SOURCE,
    level: 9,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "meteor_swarm",
    name: "Meteorenschwarm",
    nameEn: "Meteor Swarm",
    hook: "Meteorenschwarm: Grad 9, Hervorrufung — Aktion, 1 mile.",
    description: "Meteorenschwarm ist ein Zauber des 9. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 1 mile. Dauer: Augenblicklich. Komponenten: V, G. Listen: hexenmeister, zauberer. Kernwirkung: Blazing orbs of fire plummet to the ground at four different points you can see in Reichweite. Jede Kreatur in a 12 Meter-radius sphere centered on each point you choose muss einen dexterity saving throw bestehen.",
    source: SRD_SOURCE,
    level: 9,
    school: "evocation",
    castingTime: "Aktion",
    range: "1 mile",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "power_word_kill",
    name: "Machtwort Töten",
    nameEn: "Power Word Kill",
    hook: "Machtwort Töten: Grad 9, Verzauberung — Aktion, 18 Meter.",
    description: "Machtwort Töten ist ein Zauber des 9. Grades (Verzauberung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du utter a word of power that can compel one Kreatur you can see in Reichweite to die instantly. If the Kreatur you choose has 100 hit points or fewer, it dies.",
    source: SRD_SOURCE,
    level: 9,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "prismatic_wall",
    name: "Prismatische Wand",
    nameEn: "Prismatic Wall",
    hook: "Prismatische Wand: Grad 9, Abwehr — Aktion, 18 Meter.",
    description: "Prismatische Wand ist ein Zauber des 9. Grades (Abwehr). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: 10 Minuten. Komponenten: V, G. Listen: zauberer. Kernwirkung: Laut SRD: A shimmering, multicolored plane of light forms a vertical opaque wall-up to 27 Meter long, 9 Meter high, and 1 inch thick-centered on a point you can see in Reichweite. Alternatively, you can shape the wall into a sphere up to 9 Meter in diameter centered on a point you choose in Reichweite.",
    source: SRD_SOURCE,
    level: 9,
    school: "abjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Minuten",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "shapechange",
    name: "Gestaltwandel",
    nameEn: "Shapechange",
    hook: "Gestaltwandel: Grad 9, Verwandlung — Aktion, Selbst.",
    description: "Gestaltwandel ist ein Zauber des 9. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A jade circlet worth at least 1,500 gp, which you must place on your head before you cast the spell.). Listen: druide, zauberer. Kernwirkung: Du assume the form of a different Kreatur für die Dauer. The new form can be of any Kreatur with a challenge rating equal to dein level or lower.",
    source: SRD_SOURCE,
    level: 9,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Jadering im Wert von mindestens 1500 KM, den du vor dem Wirken auf den Kopf setzen musst" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["druide", "zauberer"],
  },
  {
    key: "storm_of_vengeance",
    name: "Sturm der Rache",
    nameEn: "Storm of Vengeance",
    hook: "Sturm der Rache: Grad 9, Beschwörung — Aktion, Sichtweite.",
    description: "Sturm der Rache ist ein Zauber des 9. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Sichtweite. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: druide. Kernwirkung: Laut SRD: A churning storm cloud forms, centered on a point you can see and spreading to a radius of 108 Meter. Lightning flashes in the area, thunder booms, and strong winds roar.",
    source: SRD_SOURCE,
    level: 9,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Sichtweite",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "time_stop",
    name: "Zeitstopp",
    nameEn: "Time Stop",
    hook: "Zeitstopp: Grad 9, Verwandlung — Aktion, Selbst.",
    description: "Zeitstopp ist ein Zauber des 9. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V. Listen: hexenmeister, zauberer. Kernwirkung: Du briefly stop the flow of time for everyone but yourself. No time passes for other Kreaturen, while you take 1d4 + 1 turns in a row, during which you can use actions and move as normal.",
    source: SRD_SOURCE,
    level: 9,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "true_polymorph",
    name: "Wahre Verwandlung",
    nameEn: "True Polymorph",
    hook: "Wahre Verwandlung: Grad 9, Verwandlung — Aktion, 9 Meter.",
    description: "Wahre Verwandlung ist ein Zauber des 9. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G, M (Material: A drop of mercury, a dollop of gum arabic, and a wisp of smoke.). Listen: barde, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: Choose one Kreatur or nonmagical object that you can see in Reichweite. Du transform the Kreatur into a different Kreatur, the Kreatur into an object, or the object into a Kreatur (the object must be neither worn nor carried by another Kreatur).",
    source: SRD_SOURCE,
    level: 9,
    school: "transmutation",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Tropfen Quecksilber, ein Klecks Gummiarabikum und ein Rauchwölkchen" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "true_resurrection",
    name: "Wahre Auferstehung",
    nameEn: "True Resurrection",
    hook: "Wahre Auferstehung: Grad 9, Nekromantie — 1 Stunde, Berührung.",
    description: "Wahre Auferstehung ist ein Zauber des 9. Grades (Nekromantie). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A sprinkle of holy water and diamonds worth at least 25,000gp, which the spell consumes.). Listen: kleriker, druide. Kernwirkung: Du berührst eine Kreatur that has been dead for no longer than 200 years and that died for any reason except old age. If the Kreatur's soul is free and willing, the Kreatur is restored to life with all its hit points.",
    source: SRD_SOURCE,
    level: 9,
    school: "necromancy",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "etwas Weihwasser und Diamanten im Wert von mindestens 25000 KM, die der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide"],
  },
  {
    key: "weird",
    name: "Schrecken",
    nameEn: "Weird",
    hook: "Schrecken: Grad 9, Illusion — Aktion, 36 Meter.",
    description: "Schrecken ist ein Zauber des 9. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: zauberer. Kernwirkung: Drawing on the deepest fears of a group of Kreaturen, you create illusory Kreaturen in their minds, visible only to them. Jede Kreatur in a 9 Meter-radius sphere centered on a point of dein choice in Reichweite muss einen wisdom saving throw bestehen.",
    source: SRD_SOURCE,
    level: 9,
    school: "illusion",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "wish",
    name: "Wunsch",
    nameEn: "Wish",
    hook: "Wunsch: Grad 9, Beschwörung — Aktion, Selbst.",
    description: "Wunsch ist ein Zauber des 9. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V. Listen: hexenmeister, zauberer. Kernwirkung: Wish is the mightiest spell a mortal Kreatur can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with dein desires.",
    source: SRD_SOURCE,
    level: 9,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
];
