/**
 * SRD-Zauber Grad 7 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL7_SPELLS: Spell[] = [
  {
    key: "arcane_sword",
    name: "Arkanes Schwert",
    nameEn: "Arcane Sword",
    hook: "Arkanes Schwert: Grad 7, Hervorrufung — Aktion, 18 Meter.",
    description: "Arkanes Schwert ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp.). Listen: barde, zauberer. Kernwirkung: Du create a sword-shaped plane of force that hovers in Reichweite. It lasts für die Dauer.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Miniatur-Platinschwert mit Griff und Knauf aus Kupfer und Zink im Wert von 250 KM" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "conjure_celestial",
    name: "Himmlisches Wesen herbeizaubern",
    nameEn: "Conjure Celestial",
    hook: "Himmlisches Wesen herbeizaubern: Grad 7, Beschwörung — 1 Minute, 27 Meter.",
    description: "Himmlisches Wesen herbeizaubern ist ein Zauber des 7. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 27 Meter. Dauer: Konzentration, bis zu 1 Stunde. Komponenten: V, G. Listen: kleriker. Kernwirkung: Du summon a celestial of challenge rating 4 or lower, which appears in an unoccupied space that you can see in Reichweite. The celestial disappears when it drops to 0 hit points or when the spell ends. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 7,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "delayed_blast_fireball",
    name: "Verzögerter Feuerball",
    nameEn: "Delayed Blast Fireball",
    hook: "Verzögerter Feuerball: Grad 7, Hervorrufung — Aktion, 45 Meter.",
    description: "Verzögerter Feuerball ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A tiny ball of bat guano and sulfur.). Listen: hexenmeister, zauberer. Kernwirkung: Laut SRD: A beam of yellow light flashes from dein pointing finger, then condenses to linger at a chosen point in Reichweite as a glowing bead für die Dauer. When the spell ends, either because dein concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame that spreads around corners. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: "eine winzige Kugel aus Fledermausguano und Schwefel" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "divine_word",
    name: "Göttliches Wort",
    nameEn: "Divine Word",
    hook: "Göttliches Wort: Grad 7, Hervorrufung — Bonusaktion, 9 Meter.",
    description: "Göttliches Wort ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Bonusaktion. Reichweite: 9 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: kleriker. Kernwirkung: Du utter a divine word, imbued with the power that shaped the world at the dawn of creation. Choose any number of Kreaturen you can see in Reichweite.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Bonusaktion",
    range: "9 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "etherealness",
    name: "Ätherisch werden",
    nameEn: "Etherealness",
    hook: "Ätherisch werden: Grad 7, Verwandlung — Aktion, Selbst.",
    description: "Ätherisch werden ist ein Zauber des 7. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: 8 Stunden. Komponenten: V, G. Listen: kleriker, barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du step into the border regions of the Ethereal Plane, in the area where it overlaps with dein current plane. Du remain in the Border Ethereal für die Dauer or until you use dein action to dismiss the spell. Bei höherem Zauberplatz steigert sich der Effekt laut SRD.",
    source: SRD_SOURCE,
    level: 7,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "finger_of_death",
    name: "Finger des Todes",
    nameEn: "Finger of Death",
    hook: "Finger des Todes: Grad 7, Nekromantie — Aktion, 18 Meter.",
    description: "Finger des Todes ist ein Zauber des 7. Grades (Nekromantie). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du send negative energy coursing through a Kreatur that you can see in Reichweite, causing it searing pain. The target muss einen constitution saving throw bestehen.",
    source: SRD_SOURCE,
    level: 7,
    school: "necromancy",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "fire_storm",
    name: "Feuersturm",
    nameEn: "Fire Storm",
    hook: "Feuersturm: Grad 7, Hervorrufung — Aktion, 45 Meter.",
    description: "Feuersturm ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 45 Meter. Dauer: Augenblicklich. Komponenten: V, G. Listen: kleriker, druide, hexenmeister. Kernwirkung: Laut SRD: A storm made up of sheets of roaring flame appears in a location you choose in Reichweite. The area of the storm consists of up to ten 3 Meter cubes, which you can arrange as you wish.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Aktion",
    range: "45 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "hexenmeister"],
  },
  {
    key: "forcecage",
    name: "Kraftkäfig",
    nameEn: "Forcecage",
    hook: "Kraftkäfig: Grad 7, Hervorrufung — Aktion, 30 Meter.",
    description: "Kraftkäfig ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 30 Meter. Dauer: 1 Stunde. Komponenten: V, G, M (Material: Ruby dust worth 1,500 gp.). Listen: barde, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose in Reichweite. The prison can be a cage or a solid box, as you choose.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Aktion",
    range: "30 Meter",
    components: { verbal: true, somatic: true, material: "Rubinpulver im Wert von 1500 KM" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "magnificent_mansion",
    name: "Prächtige Villa",
    nameEn: "Magnificent Mansion",
    hook: "Prächtige Villa: Grad 7, Beschwörung — 1 Minute, 90 Meter.",
    description: "Prächtige Villa ist ein Zauber des 7. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 90 Meter. Dauer: 24 Stunden. Komponenten: V, G, M (Material: A miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each item worth at least 5 gp.). Listen: barde, zauberer. Kernwirkung: Du conjure an extradimensional dwelling in range that lasts für die Dauer. Du choose where its one entrance is located.",
    source: SRD_SOURCE,
    level: 7,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "90 Meter",
    components: { verbal: true, somatic: true, material: "ein Miniaturportal aus Elfenbein, ein kleines Stück polierten Marmors und ein winziger Silberlöffel, jedes mindestens 5 KM wert" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "mirage_arcane",
    name: "Arkanes Trugbild",
    nameEn: "Mirage Arcane",
    hook: "Arkanes Trugbild: Grad 7, Illusion — 10 Minuten, Sichtweite.",
    description: "Arkanes Trugbild ist ein Zauber des 7. Grades (Illusion). Wirkungszeit: 10 Minuten. Reichweite: Sichtweite. Dauer: 10 Tage. Komponenten: V, G. Listen: druide, barde, zauberer. Kernwirkung: Du make terrain in an area up to 1 mile square look, sound, smell, and even feel like some other sort of terrain. The terrain's general shape remains the same, however.",
    source: SRD_SOURCE,
    level: 7,
    school: "illusion",
    castingTime: "10 Minuten",
    range: "Sichtweite",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Tage",
    concentration: false,
    ritual: false,
    lists: ["druide", "barde", "zauberer"],
  },
  {
    key: "plane_shift",
    name: "Ebenenwechsel",
    nameEn: "Plane Shift",
    hook: "Ebenenwechsel: Grad 7, Beschwörung — Aktion, Berührung.",
    description: "Ebenenwechsel ist ein Zauber des 7. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A forked, metal rod worth at least 250 gp, attuned to a particular plane of existence.). Listen: kleriker, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du and up to eight willing Kreaturen who link hands in a circle are transported to a different plane of existence. Du can specify a target destination in general terms, such as the City of Brass on the Elemental Plane of Fire or the palace of Dispater on the second level of the Nine Hells, and you appear in or near that destination.",
    source: SRD_SOURCE,
    level: 7,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine gegabelte Metallstange im Wert von mindestens 250 KM, auf eine bestimmte Existenzebene eingestimmt" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "prismatic_spray",
    name: "Prismatischer Strahl",
    nameEn: "Prismatic Spray",
    hook: "Prismatischer Strahl: Grad 7, Hervorrufung — Aktion, Selbst.",
    description: "Prismatischer Strahl ist ein Zauber des 7. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Augenblicklich. Komponenten: V, G. Listen: hexenmeister, zauberer. Kernwirkung: Eight multicolored rays of light flash from dein hand. Each ray is a different color and has a different power and purpose.",
    source: SRD_SOURCE,
    level: 7,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "project_image",
    name: "Bildprojektion",
    nameEn: "Project Image",
    hook: "Bildprojektion: Grad 7, Illusion — Aktion, 500 miles.",
    description: "Bildprojektion ist ein Zauber des 7. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 500 miles. Dauer: Konzentration, bis zu 24 Stunden. Komponenten: V, G, M (Material: A small replica of you made from materials worth at least 5 gp.). Listen: barde, zauberer. Kernwirkung: Du create an illusory copy of yourself that lasts für die Dauer. The copy can appear at any location in Reichweite that you have seen before, regardless of intervening obstacles.",
    source: SRD_SOURCE,
    level: 7,
    school: "illusion",
    castingTime: "Aktion",
    range: "500 miles",
    components: { verbal: true, somatic: true, material: "eine kleine Nachbildung von dir aus Materialien im Wert von mindestens 5 KM" },
    duration: "Konzentration, bis zu 24 Stunden",
    concentration: true,
    ritual: false,
    lists: ["barde", "zauberer"],
  },
  {
    key: "regenerate",
    name: "Regenerieren",
    nameEn: "Regenerate",
    hook: "Regenerieren: Grad 7, Verwandlung — 1 Minute, Berührung.",
    description: "Regenerieren ist ein Zauber des 7. Grades (Verwandlung). Wirkungszeit: 1 Minute. Reichweite: Berührung. Dauer: 1 Stunde. Komponenten: V, G, M (Material: A prayer wheel and holy water.). Listen: kleriker, druide, barde. Kernwirkung: Du berührst eine Kreatur and stimulate its natural healing ability. The target regains 4d8 + 15 hit points.",
    source: SRD_SOURCE,
    level: 7,
    school: "transmutation",
    castingTime: "1 Minute",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Gebetsrad und Weihwasser" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "druide", "barde"],
  },
  {
    key: "resurrection",
    name: "Auferstehung",
    nameEn: "Resurrection",
    hook: "Auferstehung: Grad 7, Nekromantie — 1 Stunde, Berührung.",
    description: "Auferstehung ist ein Zauber des 7. Grades (Nekromantie). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: A diamond worth at least 1,000gp, which the spell consumes.). Listen: kleriker, barde. Kernwirkung: Du berührst a dead Kreatur that has been dead for no more than a century, that didn't die of old age, and that isn't undead. If its soul is free and willing, the target returns to life with all its hit points.",
    source: SRD_SOURCE,
    level: 7,
    school: "necromancy",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Diamant im Wert von mindestens 1000 KM, den der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde"],
  },
  {
    key: "reverse_gravity",
    name: "Schwerkraft umkehren",
    nameEn: "Reverse Gravity",
    hook: "Schwerkraft umkehren: Grad 7, Verwandlung — Aktion, 30 Meter.",
    description: "Schwerkraft umkehren ist ein Zauber des 7. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 30 Meter. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G, M (Material: A lodestone and iron filings.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: This spell reverses gravity in a 15 Meter-radius, 30 Meter high cylinder centered on a point in Reichweite. All Kreaturen and objects that aren't somehow anchored to the ground in the area fall upward and reach the top of the area when you cast this spell.",
    source: SRD_SOURCE,
    level: 7,
    school: "transmutation",
    castingTime: "Aktion",
    range: "30 Meter",
    components: { verbal: true, somatic: true, material: "ein Magnetstein und Eisenspäne" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "sequester",
    name: "Absondern",
    nameEn: "Sequester",
    hook: "Absondern: Grad 7, Verwandlung — Aktion, Berührung.",
    description: "Absondern ist ein Zauber des 7. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: A powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes.). Listen: zauberer. Kernwirkung: By means of this spell, a willing Kreatur or an object can be hidden away, safe from detection für die Dauer. When you cast the spell and touch the target, it becomes invisible and can't be targeted by divination spells or perceived through scrying sensors created by divination spells.",
    source: SRD_SOURCE,
    level: 7,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Pulver aus Diamant-, Smaragd-, Rubin- und Saphirstaub im Wert von mindestens 5000 KM, das der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "simulacrum",
    name: "Trugbild",
    nameEn: "Simulacrum",
    hook: "Trugbild: Grad 7, Illusion — 12 Stunden, Berührung.",
    description: "Trugbild ist ein Zauber des 7. Grades (Illusion). Wirkungszeit: 12 Stunden. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Snow or ice in quantities sufficient to made a life-size copy of the duplicated creature; some hair, fingernail clippings, or other piece of that creature's body placed inside the snow or ice; and powdered ruby worth 1,500 gp, sprinkled over the duplicate and consumed by the spell.). Listen: zauberer. Kernwirkung: Du shape an illusory duplicate of one beast or humanoid that is in Reichweite for the entire casting time of the spell. The duplicate is a Kreatur, partially real and formed from ice or snow, and it can take actions and otherwise be affected as a normal Kreatur.",
    source: SRD_SOURCE,
    level: 7,
    school: "illusion",
    castingTime: "12 Stunden",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Schnee oder Eis für eine lebensgroße Kopie; Haare, Nagelabschnitte oder ein anderes Körperstück der Kreatur darin; und Rubinpulver im Wert von 1500 KM, über die Kopie gestreut und verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "symbol",
    name: "Runensymbol",
    nameEn: "Symbol",
    hook: "Runensymbol: Grad 7, Abwehr — 1 Minute, Berührung.",
    description: "Runensymbol ist ein Zauber des 7. Grades (Abwehr). Wirkungszeit: 1 Minute. Reichweite: Berührung. Dauer: Bis gebannt. Komponenten: V, G, M (Material: Mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes.). Listen: kleriker, barde, zauberer. Kernwirkung: Laut SRD: When you cast this spell, you inscribe a harmful glyph either on a surface (such as a section of floor, a wall, or a table) or within an object that can be closed to conceal the glyph (such as a book, a scroll, or a treasure chest). If you choose a surface, the glyph can cover an area of the surface no larger than 3 Meter in diameter.",
    source: SRD_SOURCE,
    level: 7,
    school: "abjuration",
    castingTime: "1 Minute",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "Quecksilber, Phosphor sowie pulverisierter Diamant und Opal im Gesamtwert von mindestens 1000 KM, die der Zauber verbraucht" },
    duration: "Bis gebannt",
    concentration: false,
    ritual: false,
    lists: ["kleriker", "barde", "zauberer"],
  },
  {
    key: "teleport",
    name: "Teleportieren",
    nameEn: "Teleport",
    hook: "Teleportieren: Grad 7, Beschwörung — Aktion, 3 Meter.",
    description: "Teleportieren ist ein Zauber des 7. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: 3 Meter. Dauer: Augenblicklich. Komponenten: V. Listen: barde, hexenmeister, zauberer. Kernwirkung: Laut SRD: This spell instantly transports you and up to eight willing Kreaturen of dein choice that you can see in Reichweite, or a single object that you can see in Reichweite, to a destination you select. If you target an object, it must be able to fit entirely inside a 3 Meter cube, and it can't be held or carried by an unwilling Kreatur.",
    source: SRD_SOURCE,
    level: 7,
    school: "conjuration",
    castingTime: "Aktion",
    range: "3 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
];
