/**
 * Zauber des 1. Grades, Teil 2: Goodberry bis Unseen Servant.
 *
 * Schwesterdatei zu `spells-level1-a-f.ts`; siehe dort zur Aufteilung.
 *
 * Herkunft: SRD 5.2.1 (CC-BY-4.0, Wizards of the Coast), Regeln von 2024.
 * Mechanik — Grad, Schule, Zeit, Reichweite, Komponenten, Dauer und vor allem
 * `lists` — ist 1:1 aus dem SRD übernommen; `lists` steuert den Zauberschritt,
 * eine falsche Liste zeigt einem Spieler Zauber, die er nicht wirken kann.
 *
 * Deutsch ist Übersetzung, nicht Zitat: Ein deutsches SRD gibt es nicht, daher
 * sind `name`, `hook` und `description` UWEs eigene Fassung. `nameEn` hält den
 * Originalnamen, damit der Abgleich gegen die Quelle möglich bleibt.
 * Entfernungen stehen wie im übrigen Katalog in Metern (1,5 m je 5 Fuß).
 */

import { SRD_SOURCE, type Spell } from "../types";

/** Goodberry … Unseen Servant (29 Zauber), alphabetisch nach dem englischen Namen. */
export const LEVEL1_SPELLS_G_Z: Spell[] = [
  {
    key: "zauberbeere",
    name: "Zauberbeere",
    nameEn: "Goodberry",
    hook: "Zehn Beeren: je ein Trefferpunkt und ein Tagesbedarf Nahrung.",
    description: "Zehn Beeren erscheinen in deiner Hand und bleiben für die Dauer magisch. Eine Kreatur kann als Bonusaktion eine Beere essen: Sie erhält 1 Trefferpunkt zurück und ist für einen Tag satt. Ungegessene Beeren verschwinden, wenn der Zauber endet.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Mistelzweig" },
    duration: "24 Stunden",
    concentration: false,
    ritual: false,
    lists: ["druide", "waldlaeufer"],
  },
  {
    key: "schmierfett",
    name: "Schmierfett",
    nameEn: "Grease",
    hook: "Drei mal drei Meter rutschiger Boden — der billigste Weg, eine Verfolgung zu beenden.",
    description: "Nicht brennbares Fett bedeckt eine Fläche von 3 mal 3 Metern um einen Punkt in 18 Metern und macht sie für die Dauer zu schwierigem Gelände. Wer beim Erscheinen darin steht, muss einen Geschicklichkeits-Rettungswurf bestehen oder liegt. Dasselbe gilt für jede Kreatur, die den Bereich betritt oder ihren Zug darin beendet.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "etwas Schweineschwarte oder Butter" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "fuehrender_lichtstrahl",
    name: "Führender Lichtstrahl",
    nameEn: "Guiding Bolt",
    hook: "Der härteste Angriffszauber des Klerikers — und der nächste Angriff hat Vorteil.",
    description: "Du schleuderst einen Lichtblitz auf eine Kreatur in 36 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt sie 4W6 gleißenden Schaden, und der nächste Angriffswurf gegen sie vor dem Ende deines nächsten Zuges hat Vorteil. Je höherem Zauberplatz steigt der Schaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "heilendes_wort",
    name: "Heilendes Wort",
    nameEn: "Healing Word",
    hook: "Heilung als Bonusaktion auf 18 Meter — der Zauber, der Gefallene wieder hochholt.",
    description: "Eine sichtbare Kreatur deiner Wahl in 18 Metern erhält Trefferpunkte in Höhe von 2W4 plus deinem Zauberattributsmodifikator zurück. Je höherem Zauberplatz steigt die Heilung um 2W4.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Bonusaktion",
    range: "18 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "kleriker", "druide"],
  },
  {
    key: "hoellische_vergeltung",
    name: "Höllische Vergeltung",
    nameEn: "Hellish Rebuke",
    hook: "Wer dir weh tut, steht im nächsten Moment in grünen Flammen.",
    description: "Du wirkst den Zauber als Reaktion, wenn dir eine sichtbare Kreatur in 18 Metern Schaden zufügt. Sie wird von grünen Flammen umhüllt und macht einen Geschicklichkeits-Rettungswurf: 2W10 Feuerschaden bei Misserfolg, die Hälfte bei Erfolg. Je höherem Zauberplatz steigt der Schaden um 1W10.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Reaktion, wenn dir eine sichtbare Kreatur in 18 Metern Schaden zufügt",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenpakt_magier"],
  },
  {
    key: "heldenmut",
    name: "Heldenmut",
    nameEn: "Heroism",
    hook: "Immun gegen Furcht, und jede Runde ein frischer Puffer temporärer Trefferpunkte.",
    description: "Eine willige Kreatur, die du berührst, ist bis zum Ende des Zaubers immun gegen den Zustand Verängstigt und erhält zu Beginn jedes ihrer Züge temporäre Trefferpunkte in Höhe deines Zauberattributsmodifikators. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "paladin"],
  },
  {
    key: "verhexen",
    name: "Verhexen",
    nameEn: "Hex",
    hook: "Ein Fluch, der jedem deiner Treffer 1W6 nekrotischen Schaden anhängt — und mitwandert.",
    description: "Du belegst eine sichtbare Kreatur in 27 Metern mit einem Fluch. Bis der Zauber endet, verursachst du bei jedem Treffer gegen sie 1W6 zusätzlichen nekrotischen Schaden. Außerdem wählst du beim Wirken ein Attribut: Auf Proben damit hat das Ziel Nachteil. Fällt es auf 0 Trefferpunkte, verschiebst du den Fluch als Bonusaktion auf ein neues Ziel. Höhere Zauberplätze verlängern die Konzentration: Grad 2 bis zu 4 Stunden, Grad 3–4 bis zu 8 Stunden, ab Grad 5 bis zu 24 Stunden.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Bonusaktion",
    range: "27 Meter",
    components: { verbal: true, somatic: true, material: "das versteinerte Auge eines Molchs" },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["hexenpakt_magier"],
  },
  {
    key: "grauenhaftes_gelaechter",
    name: "Grauenhaftes Gelächter",
    nameEn: "Hideous Laughter",
    hook: "Das Ziel bricht in Lachen aus, liegt am Boden und ist handlungsunfähig.",
    description: "Eine sichtbare Kreatur deiner Wahl in 9 Metern macht einen Weisheits-Rettungswurf. Bei Misserfolg liegt sie und ist handlungsunfähig; sie lacht unkontrolliert und kann nicht selbst aufstehen. Am Ende jedes ihrer Züge und jedes Mal, wenn sie Schaden nimmt, wiederholt sie den Rettungswurf — nach Schaden mit Vorteil. Bei Erfolg endet der Zauber. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "ein Törtchen und eine Feder" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "zeichen_des_jaegers",
    name: "Zeichen des Jägers",
    nameEn: "Hunter's Mark",
    hook: "Der Zauber, den fast jeder Waldläufer zuerst wirkt: markieren, dann jeden Treffer aufwerten.",
    description: "Du markierst eine sichtbare Kreatur in 27 Metern als deine Beute. Bis der Zauber endet, verursachst du bei jedem Treffer gegen sie 1W6 zusätzlichen energetischen Schaden und hast Vorteil auf Weisheitsproben (Wahrnehmung oder Überleben), um sie zu finden. Fällt sie auf 0 Trefferpunkte, verschiebst du das Zeichen als Bonusaktion. Höhere Zauberplätze verlängern die Konzentration: Grad 3–4 bis zu 8 Stunden, ab Grad 5 bis zu 24 Stunden.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Bonusaktion",
    range: "27 Meter",
    components: { verbal: true, somatic: false, material: null },
    duration: "Konzentration, bis zu 1 Stunde",
    concentration: true,
    ritual: false,
    lists: ["waldlaeufer"],
  },
  {
    key: "eismesser",
    name: "Eismesser",
    nameEn: "Ice Knife",
    hook: "Ein Eissplitter, der trifft oder nicht — explodieren tut er in jedem Fall.",
    description: "Du schleuderst einen Eissplitter auf eine Kreatur in 18 Metern und machst einen Fernkampf-Zauberangriff; bei einem Treffer 1W10 Stichschaden. Treffer oder nicht, der Splitter zerplatzt danach: Das Ziel und jede Kreatur im Umkreis von 1,5 Metern muss einen Geschicklichkeits-Rettungswurf bestehen oder nimmt 2W6 Kälteschaden. Je höherem Zauberplatz steigt der Kälteschaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: false, somatic: true, material: "ein Tropfen Wasser oder ein Stück Eis" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
  {
    key: "identifizieren",
    name: "Identifizieren",
    nameEn: "Identify",
    hook: "Was kann dieser Ring? Eine Minute Ritual, und du weißt es.",
    description: "Du berührst während des gesamten Wirkens einen Gegenstand. Ist er magisch, erfährst du seine Eigenschaften, wie man sie nutzt, ob er Einstimmung verlangt und wie viele Ladungen er hat. Du erfährst außerdem, welche Zauber auf ihm liegen und welcher Zauber ihn erschaffen hat. Berührst du stattdessen eine Kreatur, erfährst du, welche Zauber gerade auf ihr wirken.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "1 Minute oder Ritual",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Perle im Wert von mindestens 100 GM" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["barde", "zauberer", "erfinder"],
  },
  {
    key: "illusionaere_schrift",
    name: "Illusionäre Schrift",
    nameEn: "Illusory Script",
    hook: "Eine Botschaft, die nur die richtigen Augen lesen können — zehn Tage lang.",
    description: "Du beschreibst Pergament, Papier oder ein anderes geeignetes Material und legst eine Illusion darüber. Dir und den Kreaturen, die du beim Wirken benennst, erscheint der Text normal und in deiner Handschrift. Alle anderen sehen unverständliche, fremdartige Zeichen — oder, wenn du willst, einen anderen Text in anderer Handschrift und Sprache, die du beherrschen musst. Wer Wahren Blick besitzt, liest die verborgene Botschaft.",
    source: SRD_SOURCE,
    level: 1,
    school: "illusion",
    castingTime: "1 Minute oder Ritual",
    range: "Berührung",
    components: { verbal: false, somatic: true, material: "Tinte im Wert von mindestens 10 GM, die der Zauber verbraucht" },
    duration: "10 Tage",
    concentration: false,
    ritual: true,
    lists: ["barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "wunden_zufuegen",
    name: "Wunden zufügen",
    nameEn: "Inflict Wounds",
    hook: "Das Gegenstück zu Wunden heilen: nekrotischer Schaden per Berührung.",
    description: "Eine Kreatur, die du berührst, macht einen Konstitutions-Rettungswurf und nimmt bei Misserfolg 2W10 nekrotischen Schaden, bei Erfolg die Hälfte. Je höherem Zauberplatz steigt der Schaden um 1W10.",
    source: SRD_SOURCE,
    level: 1,
    school: "necromancy",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "sprung",
    name: "Sprung",
    nameEn: "Jump",
    hook: "Neun Meter weit springen für drei Meter Bewegung.",
    description: "Du berührst eine willige Kreatur. Einmal in jedem ihrer Züge kann sie bis zum Ende des Zaubers 9 Meter weit springen und gibt dafür 3 Meter Bewegung aus. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Bonusaktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "das Hinterbein einer Heuschrecke" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["druide", "waldlaeufer", "hexenmeister", "zauberer", "erfinder"],
  },
  {
    key: "weitschritt",
    name: "Weitschritt",
    nameEn: "Longstrider",
    hook: "Drei Meter mehr Bewegung, eine Stunde lang.",
    description: "Du berührst eine Kreatur. Ihre Bewegungsrate steigt bis zum Ende des Zaubers um 3 Meter. Mit einem höheren Zauberplatz kommt je Grad ein Ziel dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Prise Erde" },
    duration: "1 Stunde",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide", "waldlaeufer", "zauberer"],
  },
  {
    key: "magierruestung",
    name: "Magierrüstung",
    nameEn: "Mage Armor",
    hook: "Rüstungsklasse 13 plus Geschicklichkeit, acht Stunden lang, ohne ein Stück Metall.",
    description: "Du berührst eine willige Kreatur, die keine Rüstung trägt. Bis der Zauber endet, beträgt ihre Grund-Rüstungsklasse 13 plus Geschicklichkeitsmodifikator. Legt sie eine Rüstung an, endet der Zauber vorzeitig.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "ein Stück gegerbtes Leder" },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "magisches_geschoss",
    name: "Magisches Geschoss",
    nameEn: "Magic Missile",
    hook: "Drei Geschosse, die immer treffen — kein Angriffswurf, kein Rettungswurf.",
    description: "Du erschaffst drei leuchtende Pfeile aus magischer Energie. Jeder trifft eine sichtbare Kreatur deiner Wahl in 36 Metern und verursacht 1W4 + 1 energetischen Schaden. Alle schlagen gleichzeitig ein; du darfst sie auf ein Ziel bündeln oder verteilen. Je höherem Zauberplatz kommt ein Pfeil dazu.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "schutz_vor_gut_und_boese",
    name: "Schutz vor Gut und Böse",
    nameEn: "Protection from Evil and Good",
    hook: "Zehn Minuten Schutz gegen genau die Kreaturen, die einen bezaubern oder besetzen wollen.",
    description: "Eine willige Kreatur, die du berührst, ist gegen Aberrationen, Himmlische, Elementare, Feenwesen, Unholde und Untote geschützt. Diese Kreaturen haben Nachteil auf Angriffe gegen sie, können sie nicht besetzen und ihr nicht die Zustände Bezaubert oder Verängstigt zufügen. Wirkt bereits ein solcher Effekt, hat das Ziel Vorteil auf neue Rettungswürfe dagegen.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Aktion",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "eine Phiole Weihwasser im Wert von mindestens 25 GM, die der Zauber verbraucht" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "paladin", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "speis_und_trank_reinigen",
    name: "Speis und Trank reinigen",
    nameEn: "Purify Food and Drink",
    hook: "Gift und Fäulnis raus aus allem, was auf dem Tisch steht.",
    description: "Du entfernst Gift und Fäulnis aus allen nichtmagischen Speisen und Getränken in einer Kugel mit 1,5 Metern Radius um einen Punkt in 3 Metern.",
    source: SRD_SOURCE,
    level: 1,
    school: "transmutation",
    castingTime: "Aktion oder Ritual",
    range: "3 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: true,
    lists: ["kleriker", "druide", "paladin"],
  },
  {
    key: "strahl_der_uebelkeit",
    name: "Strahl der Übelkeit",
    nameEn: "Ray of Sickness",
    hook: "Giftschaden und ein vergifteter Gegner für eine Runde.",
    description: "Du schießt einen grünlichen Strahl auf eine Kreatur in 18 Metern und machst einen Fernkampf-Zauberangriff. Bei einem Treffer nimmt sie 2W8 Giftschaden und ist bis zum Ende deines nächsten Zuges vergiftet. Je höherem Zauberplatz steigt der Schaden um 1W8.",
    source: SRD_SOURCE,
    level: 1,
    school: "necromancy",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer"],
  },
  {
    key: "zufluchtsort",
    name: "Zufluchtsort",
    nameEn: "Sanctuary",
    hook: "Wer den Geschützten angreifen will, muss erst einen Rettungswurf bestehen.",
    description: "Du schützt eine Kreatur in 9 Metern. Bis der Zauber endet, muss jeder, der sie mit einem Angriffswurf oder einem schädigenden Zauber ins Visier nimmt, einen Weisheits-Rettungswurf bestehen — sonst wählt er ein neues Ziel oder verliert Angriff bzw. Zauber. Gegen Flächeneffekte hilft der Schutz nicht. Er endet, sobald die geschützte Kreatur selbst angreift, zaubert oder Schaden verursacht.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Bonusaktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "eine Glasscherbe aus einem Spiegel" },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["kleriker"],
  },
  {
    key: "sengendes_schmettern",
    name: "Sengendes Schmettern",
    nameEn: "Searing Smite",
    hook: "Ein Treffer, der weiterbrennt, bis das Ziel den Rettungswurf schafft.",
    description: "Du wirkst den Zauber unmittelbar nach einem Treffer mit einer Nahkampfwaffe oder einem waffenlosen Schlag. Das Ziel nimmt zusätzlich 1W6 Feuerschaden. Zu Beginn jedes seiner Züge nimmt es erneut 1W6 Feuerschaden und macht danach einen Konstitutions-Rettungswurf; bei Erfolg endet der Zauber. Je höherem Zauberplatz steigt der gesamte Schaden um 1W6.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Bonusaktion, unmittelbar nachdem du ein Ziel mit einer Nahkampfwaffe oder einem waffenlosen Schlag getroffen hast",
    range: "Selbst",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 Minute",
    concentration: false,
    ritual: false,
    lists: ["paladin"],
  },
  {
    key: "schild",
    name: "Schild",
    nameEn: "Shield",
    hook: "Die Reaktion, die einen Treffer nachträglich zum Fehlschlag macht: +5 Rüstungsklasse.",
    description: "Du wirkst den Zauber als Reaktion, wenn dich ein Angriffswurf trifft oder ein Magisches Geschoss auf dich zielt. Bis zum Beginn deines nächsten Zuges hast du +5 auf die Rüstungsklasse — auch gegen den auslösenden Angriff — und nimmst keinen Schaden von Magisches Geschoss.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Reaktion, wenn dich ein Angriffswurf trifft oder ein Magisches Geschoss auf dich zielt",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["hexenmeister", "zauberer", "erfinder"],
  },
  {
    key: "schild_des_glaubens",
    name: "Schild des Glaubens",
    nameEn: "Shield of Faith",
    hook: "+2 Rüstungsklasse für zehn Minuten, als Bonusaktion auf 18 Meter.",
    description: "Ein schimmerndes Feld umgibt eine Kreatur deiner Wahl in 18 Metern und gibt ihr bis zum Ende des Zaubers einen Bonus von +2 auf die Rüstungsklasse.",
    source: SRD_SOURCE,
    level: 1,
    school: "abjuration",
    castingTime: "Bonusaktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "eine Gebetsrolle" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "paladin"],
  },
  {
    key: "stummes_abbild",
    name: "Stummes Abbild",
    nameEn: "Silent Image",
    hook: "Ein bewegliches Bild von der Größe eines kleinen Zimmers — ohne Ton.",
    description: "Du erschaffst an einem Punkt in 18 Metern das Bild eines Objekts, einer Kreatur oder einer Erscheinung, das höchstens einen Würfel von 4,5 Metern Kantenlänge füllt. Das Bild ist rein optisch — kein Ton, kein Geruch. Als Magieaktion bewegst du es innerhalb der Reichweite und passt sein Aussehen der Bewegung an. Berührung enttarnt es, ebenso eine Untersuchen-Aktion mit gelungener Intelligenzprobe (Nachforschen) gegen deinen Zauberrettungswurf-SG; danach sieht die Kreatur hindurch.",
    source: SRD_SOURCE,
    level: 1,
    school: "illusion",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "ein Stück Vlies" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "schlaf",
    name: "Schlaf",
    nameEn: "Sleep",
    hook: "Eine Kugel voller Schlaf — wer zweimal den Rettungswurf verpatzt, liegt.",
    description: "Jede Kreatur deiner Wahl in einer Kugel mit 1,5 Metern Radius um einen Punkt in 18 Metern muss einen Weisheits-Rettungswurf bestehen oder ist bis zum Ende ihres nächsten Zuges handlungsunfähig und wiederholt dann den Wurf. Misslingt auch der zweite, ist sie bis zum Ende des Zaubers bewusstlos. Schaden oder eine Aktion zum Wachrütteln beenden den Effekt für ein Ziel. Wer nicht schläft — etwa Elfen — oder immun gegen Erschöpfung ist, besteht automatisch.",
    source: SRD_SOURCE,
    level: 1,
    school: "enchantment",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Sand oder Rosenblätter" },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "mit_tieren_sprechen",
    name: "Mit Tieren sprechen",
    nameEn: "Speak with Animals",
    hook: "Zehn Minuten Gespräch mit jedem Tier in Hörweite.",
    description: "Bis der Zauber endet, verstehst du Tiere und kannst mit ihnen sprechen; auch die Fertigkeitsoptionen der Beeinflussen-Aktion stehen dir bei ihnen offen. Die meisten Tiere haben wenig zu sagen, was über Überleben und Gesellschaft hinausgeht, können dir aber von nahen Orten und Monstern berichten — samt allem, was sie am letzten Tag wahrgenommen haben.",
    source: SRD_SOURCE,
    level: 1,
    school: "divination",
    castingTime: "Aktion oder Ritual",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 Minuten",
    concentration: false,
    ritual: true,
    lists: ["barde", "druide", "waldlaeufer", "hexenpakt_magier"],
  },
  {
    key: "donnerwoge",
    name: "Donnerwoge",
    nameEn: "Thunderwave",
    hook: "Eine Druckwelle, die Schaden macht und alles drei Meter von dir wegschiebt.",
    description: "Eine Woge donnernder Energie füllt einen Würfel von 4,5 Metern Kantenlänge, der von dir ausgeht. Jede Kreatur darin macht einen Konstitutions-Rettungswurf: bei Misserfolg 2W8 Schallschaden und 3 Meter Rückstoß, bei Erfolg der halbe Schaden. Lose Gegenstände im Würfel werden ebenfalls weggeschoben, und der Donner ist 90 Meter weit zu hören. Je höherem Zauberplatz steigt der Schaden um 1W8.",
    source: SRD_SOURCE,
    level: 1,
    school: "evocation",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["barde", "druide", "hexenmeister", "zauberer"],
  },
  {
    key: "unsichtbarer_diener",
    name: "Unsichtbarer Diener",
    nameEn: "Unseen Servant",
    hook: "Ein unsichtbarer Helfer für eine Stunde: holen, putzen, Feuer machen, servieren.",
    description: "Du erschaffst eine unsichtbare, geistlose, formlose mittelgroße Kraft, die an einem freien Punkt am Boden in 18 Metern entsteht. Sie hat Rüstungsklasse 10, 1 Trefferpunkt und Stärke 2 und kann nicht angreifen; fällt sie auf 0 Trefferpunkte, endet der Zauber. Einmal pro Zug befiehlst du ihr als Bonusaktion, sich bis zu 4,5 Meter zu bewegen und mit einem Gegenstand zu hantieren. Sie erledigt einfache Aufgaben, die auch ein Mensch könnte. Entfernt sie sich weiter als 18 Meter von dir, endet der Zauber.",
    source: SRD_SOURCE,
    level: 1,
    school: "conjuration",
    castingTime: "Aktion oder Ritual",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: "etwas Schnur und Holz" },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["barde", "hexenpakt_magier", "zauberer"],
  },
];
