/**
 * SRD-Zauber Grad 5 — Open5e wotc-srd (CC-BY-4.0), deutsche UWE-Fassungen.
 * Ability score names bleiben Englisch (Strength, Dexterity, …).
 */

import { SRD_SOURCE, type Spell } from "../types";

export const LEVEL5_SPELLS_B: Spell[] = [
  {
    key: "reincarnate",
    name: "Wiedergeburt",
    nameEn: "Reincarnate",
    hook: "Wiedergeburt: Grad 5, Verwandlung — 1 Stunde, Berührung.",
    description: "Wiedergeburt ist ein Zauber des 5. Grades (Verwandlung). Wirkungszeit: 1 Stunde. Reichweite: Berührung. Dauer: Augenblicklich. Komponenten: V, G, M (Material: Rare oils and unguents worth at least 1,000 gp, which the spell consumes.). Listen: druide. Kernwirkung: Du berührst a dead humanoid or a piece of a dead humanoid. Provided that the Kreatur has been dead no longer than 10 days, the spell forms a new adult body for it and then calls the soul to enter that body.",
    source: SRD_SOURCE,
    level: 5,
    school: "transmutation",
    castingTime: "1 Stunde",
    range: "Berührung",
    components: { verbal: true, somatic: true, material: "seltene Öle und Salben im Wert von mindestens 1000 KM, die der Zauber verbraucht" },
    duration: "Augenblicklich",
    concentration: false,
    ritual: false,
    lists: ["druide"],
  },
  {
    key: "scrying",
    name: "Spähen",
    nameEn: "Scrying",
    hook: "Spähen: Grad 5, Erkenntnis — 10 Minuten, Selbst.",
    description: "Spähen ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: 10 Minuten. Reichweite: Selbst. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water.). Listen: kleriker, druide, barde, hexenpakt_magier, zauberer. Kernwirkung: Du can see and hear a particular Kreatur you choose that is on the same plane of existence as you. The target muss einen wisdom saving throw bestehen, which is modified by how well you know the target and the sort of physical connection you have to it.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "10 Minuten",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: "ein Fokus im Wert von mindestens 1000 KM, z. B. Kristallkugel, Silberspiegel oder Weihwasserbecken" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "barde", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "seeming",
    name: "Schein",
    nameEn: "Seeming",
    hook: "Schein: Grad 5, Illusion — Aktion, 9 Meter.",
    description: "Schein ist ein Zauber des 5. Grades (Illusion). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 8 Stunden. Komponenten: V, G. Listen: barde, hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Laut SRD: This spell allows you to change the appearance of any number of Kreaturen that you can see in Reichweite. Du give each target you choose a new, illusory appearance.",
    source: SRD_SOURCE,
    level: 5,
    school: "illusion",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "8 Stunden",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "telekinesis",
    name: "Telekinese",
    nameEn: "Telekinesis",
    hook: "Telekinese: Grad 5, Verwandlung — Aktion, 18 Meter.",
    description: "Telekinese ist ein Zauber des 5. Grades (Verwandlung). Wirkungszeit: Aktion. Reichweite: 18 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G. Listen: hexenmeister, hexenpakt_magier, zauberer. Kernwirkung: Du gain the ability to move or manipulate Kreaturen or objects by thought. When you cast the spell, and as dein action each round für die Dauer, you can exert dein will on one Kreatur or object that you can see in Reichweite, causing the appropriate effect below.",
    source: SRD_SOURCE,
    level: 5,
    school: "transmutation",
    castingTime: "Aktion",
    range: "18 Meter",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["hexenmeister", "hexenpakt_magier", "zauberer"],
  },
  {
    key: "telepathic_bond",
    name: "Telepathische Verbindung",
    nameEn: "Telepathic Bond",
    hook: "Telepathische Verbindung: Grad 5, Erkenntnis — Aktion, 9 Meter.",
    description: "Telepathische Verbindung ist ein Zauber des 5. Grades (Erkenntnis). Wirkungszeit: Aktion. Reichweite: 9 Meter. Dauer: 1 Stunde. Komponenten: V, G, M (Material: Pieces of eggshell from two different kinds of creatures). Listen: zauberer. Kernwirkung: Du forge a telepathic link among up to eight willing Kreaturen of dein choice in Reichweite, psychically linking each Kreatur to all the others für die Dauer. Creatures with Intelligence scores of 2 or less aren't affected by this spell.",
    source: SRD_SOURCE,
    level: 5,
    school: "divination",
    castingTime: "Aktion",
    range: "9 Meter",
    components: { verbal: true, somatic: true, material: "Eierschalenstücke von zwei verschiedenen Kreaturenarten" },
    duration: "1 Stunde",
    concentration: false,
    ritual: true,
    lists: ["zauberer"],
  },
  {
    key: "teleportation_circle",
    name: "Teleportationskreis",
    nameEn: "Teleportation Circle",
    hook: "Teleportationskreis: Grad 5, Beschwörung — 1 Minute, 3 Meter.",
    description: "Teleportationskreis ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: 1 Minute. Reichweite: 3 Meter. Dauer: 1 Runde. Komponenten: V, M (Material: Rare chalks and inks infused with precious gems with 50 gp, which the spell consumes.). Listen: barde, hexenmeister, zauberer. Kernwirkung: As you cast the spell, you draw a 3 Meter-diameter circle on the ground inscribed with sigils that link dein location to a permanent teleportation circle of dein choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of dein next turn.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "1 Minute",
    range: "3 Meter",
    components: { verbal: true, somatic: false, material: "seltene Kreiden und Tinten mit Edelsteinen im Wert von 50 KM, die der Zauber verbraucht" },
    duration: "1 Runde",
    concentration: false,
    ritual: false,
    lists: ["barde", "hexenmeister", "zauberer"],
  },
  {
    key: "tree_stride",
    name: "Baumschritt",
    nameEn: "Tree Stride",
    hook: "Baumschritt: Grad 5, Beschwörung — Aktion, Selbst.",
    description: "Baumschritt ist ein Zauber des 5. Grades (Beschwörung). Wirkungszeit: Aktion. Reichweite: Selbst. Dauer: Konzentration, bis zu 1 Minute. Komponenten: V, G. Listen: kleriker, druide, waldlaeufer. Kernwirkung: Du gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 150 Meter. Both trees must be living and at least the same size as you.",
    source: SRD_SOURCE,
    level: 5,
    school: "conjuration",
    castingTime: "Aktion",
    range: "Selbst",
    components: { verbal: true, somatic: true, material: null },
    duration: "Konzentration, bis zu 1 Minute",
    concentration: true,
    ritual: false,
    lists: ["kleriker", "druide", "waldlaeufer"],
  },
  {
    key: "wall_of_force",
    name: "Kraftwall",
    nameEn: "Wall of Force",
    hook: "Kraftwall: Grad 5, Hervorrufung — Aktion, 36 Meter.",
    description: "Kraftwall ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A pinch of powder made by crushing a clear gemstone.). Listen: zauberer. Kernwirkung: Laut SRD: An invisible wall of force springs into existence at a point you choose in Reichweite. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "eine Prise Pulver aus einem zerkleinerten klaren Edelstein" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["zauberer"],
  },
  {
    key: "wall_of_stone",
    name: "Steinwall",
    nameEn: "Wall of Stone",
    hook: "Steinwall: Grad 5, Hervorrufung — Aktion, 36 Meter.",
    description: "Steinwall ist ein Zauber des 5. Grades (Hervorrufung). Wirkungszeit: Aktion. Reichweite: 36 Meter. Dauer: Konzentration, bis zu 10 Minuten. Komponenten: V, G, M (Material: A small block of granite.). Listen: druide, hexenmeister, zauberer. Kernwirkung: Laut SRD: A nonmagical wall of solid stone springs into existence at a point you choose in Reichweite. The wall is 6 inches thick and is composed of ten 3 Meter-by-3 Meter panels.",
    source: SRD_SOURCE,
    level: 5,
    school: "evocation",
    castingTime: "Aktion",
    range: "36 Meter",
    components: { verbal: true, somatic: true, material: "ein kleiner Granitblock" },
    duration: "Konzentration, bis zu 10 Minuten",
    concentration: true,
    ritual: false,
    lists: ["druide", "hexenmeister", "zauberer"],
  },
];
