[package]
name = "uwe_rtx_connector_client"
version = "0.1.0"
description = "UWE RTX Connector Client"
authors = ["UWE"]
edition = "2021"
build = "build.rs"

[lib]
name = "uwe_rtx_connector_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.0.0", features = [] }

[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.228", package = "serde", features = ["derive"] }
serde_json = "1.0.150"
tauri = { version = "=2.0.0", features = ["tray-icon"] }
tauri-plugin-updater = { version = "=2.0.0", default-features = false, features = ["rustls-tls"] }
url = "2.5.8"
