/**
 * System area navigation — owner/admin operations.
 * Part of the central navigation contract (see ./types.ts).
 */
import type { NavGroup } from "./types";

const SECTION = "System";

export const ADMIN_HUB_SECTIONS = [
  {
    title: "Setup & Host",
    links: [
      { href: "/admin/setup", label: "Einrichtung" },
      { href: "/system", label: "System-Hub" },
    ],
  },
  {
    title: "Nutzer & Sicherheit",
    links: [
      { href: "/admin/users", label: "Benutzer" },
      { href: "/admin/security", label: "Security" },
      { href: "/admin/secrets", label: "Secrets-Status" },
    ],
  },
  {
    title: "Content & KI",
    links: [
      { href: "/admin/ai-gateway", label: "KI-Gateway" },
      { href: "/admin/agent-jobs", label: "Agent Jobs" },
      { href: "/admin/ai-prompt", label: "AI-Prompt" },
    ],
  },
  {
    title: "Betrieb",
    links: [
      { href: "/admin/activity", label: "Verlauf" },
      { href: "/backup", label: "Backup" },
      { href: "/mail", label: "Mail Center" },
      { href: "/worlds", label: "Welten verwalten", primary: true },
    ],
  },
] as const;

export const SYSTEM_NAV: NavGroup[] = [
  {
    id: "system-overview",
    title: "Übersicht",
    items: [
      {
        id: "system-hub",
        label: "System-Hub",
        href: "/system",
        icon: "server",
        group: "Übersicht",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["system", "status", "diagnose"],
      },
      {
        id: "system-admin",
        label: "Admin Übersicht",
        href: "/admin",
        icon: "layout-dashboard",
        group: "Übersicht",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["admin"],
      },
      {
        id: "system-activity",
        label: "Verlauf",
        href: "/admin/activity",
        icon: "history",
        group: "Übersicht",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["activity", "audit", "verlauf"],
      },
      {
        id: "system-command-center",
        label: "NL-Befehle",
        href: "/command",
        icon: "terminal",
        group: "Übersicht",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["command", "nl", "befehl", "intent", "admin", "nl-befehle"],
      },
    ],
  },
  {
    id: "system-setup-host",
    title: "Setup & Host",
    items: [
      {
        id: "system-setup",
        label: "Owner-Einrichtung",
        href: "/admin/setup",
        icon: "sliders-horizontal",
        group: "Setup & Host",
        section: SECTION,
        permission: ["owner"],
        status: "active",
        source: "system",
        keywords: ["setup", "einrichtung", "owner"],
      },
      {
        id: "system-host-control",
        label: "Host Control",
        href: "/system/host-control",
        icon: "server-cog",
        group: "Setup & Host",
        section: SECTION,
        permission: ["owner"],
        status: "active",
        source: "system",
        keywords: ["host", "control", "url", "healthcheck"],
      },
      {
        id: "system-cloudflare",
        label: "Cloudflare",
        href: "/system/cloudflare",
        icon: "cloud",
        group: "Setup & Host",
        section: SECTION,
        permission: ["owner"],
        status: "active",
        source: "system",
        keywords: ["cloudflare", "tunnel", "access", "dns"],
      },
      {
        id: "system-rtx",
        label: "RTX Connector",
        href: "/system/rtx-connector",
        icon: "cpu",
        group: "Setup & Host",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["rtx", "connector", "ollama", "host"],
      },
      {
        id: "system-printers",
        label: "Drucker",
        href: "/system/printers",
        icon: "printer",
        group: "Setup & Host",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["drucker", "printer", "label", "print"],
      },
    ],
  },
  {
    id: "system-access",
    title: "Benutzer & Sicherheit",
    items: [
      {
        id: "system-users",
        label: "Benutzer & Rollen",
        href: "/admin/users",
        icon: "users",
        group: "Benutzer & Sicherheit",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["benutzer", "rollen", "membership", "portalzugriff"],
      },
      {
        id: "system-security",
        label: "Security",
        href: "/admin/security",
        icon: "shield",
        group: "Benutzer & Sicherheit",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["security", "sicherheit", "leaks"],
      },
      {
        id: "system-audit-log",
        label: "Audit Log",
        href: "/admin/audit-log",
        icon: "scroll-text",
        group: "Benutzer & Sicherheit",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["audit", "log"],
      },
      {
        id: "system-api-tokens",
        label: "API Tokens",
        href: "/admin/api-tokens",
        icon: "key-round",
        group: "Benutzer & Sicherheit",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["api", "token"],
      },
      {
        id: "system-webhooks",
        label: "Webhooks",
        href: "/admin/webhooks",
        icon: "webhook",
        group: "Benutzer & Sicherheit",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["webhook"],
      },
    ],
  },
  {
    id: "system-operations",
    title: "Betrieb",
    items: [
      {
        id: "system-backup",
        label: "Backup & Restore",
        href: "/backup",
        icon: "database-backup",
        group: "Betrieb",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["backup", "restore", "sicherung"],
      },
      {
        id: "system-migrations",
        label: "Migrationen",
        href: "/admin/migrations",
        icon: "database",
        group: "Betrieb",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["migration", "prisma", "schema", "deploy", "datenbank"],
      },
      {
        id: "system-diagnose",
        label: "Diagnose",
        href: "/system?tab=diagnose",
        icon: "stethoscope",
        group: "Betrieb",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["diagnose", "status", "leak", "env", "systemstatus"],
      },
      {
        id: "system-tags",
        label: "Tags",
        href: "/admin/tags",
        icon: "tags",
        group: "Betrieb",
        section: SECTION,
        permission: ["owner", "admin"],
        status: "active",
        source: "system",
        keywords: ["tags"],
      },
    ],
  },
  {
    id: "system-settings",
    title: "Einstellungen",
    items: [
      {
        id: "system-settings",
        label: "Einstellungen",
        href: "/settings",
        icon: "settings",
        group: "Einstellungen",
        section: SECTION,
        permission: ["owner", "admin", "dm"],
        status: "active",
        source: "system",
        keywords: ["settings", "einstellungen", "erscheinungsbild", "theme"],
      },
      {
        id: "system-account-password",
        label: "Passwort",
        href: "/account/password",
        icon: "lock",
        group: "Einstellungen",
        section: SECTION,
        permission: ["owner", "admin", "dm", "player", "readonly"],
        status: "active",
        source: "system",
        keywords: ["passwort", "account"],
      },
      {
        id: "system-account-security",
        label: "Sicherheit (2FA)",
        href: "/account/security",
        icon: "shield-check",
        group: "Einstellungen",
        section: SECTION,
        permission: ["owner", "admin", "dm", "player", "readonly"],
        status: "active",
        source: "system",
        keywords: ["2fa", "sicherheit", "account"],
      },
    ],
  },
];
