#!/usr/bin/env bash
# Idempotent Linux production host setup for UWE (systemd + /etc/uwe/uwe.env).
#
# Usage:
#   sudo bash ./deploy/scripts/setup-uwe-host.sh              # safe update/repair (default)
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --quick      # fast update after git pull
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --repair     # rebuild deps + rewrite systemd
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --healthcheck
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --fresh      # destructive reset (requires confirmation)
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --reset      # alias for --fresh
#   sudo bash ./deploy/scripts/setup-uwe-host.sh --full-reinstall  # alias for --fresh
#
# Official paths:
#   Repo:    /opt/uwe
#   Env:     /etc/uwe/uwe.env
#   Data:    /var/lib/uwe
#   Logs:    /var/log/uwe
#   Backups: /var/backups/uwe
#   Service: uwe.service
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# shellcheck source=lib/uwe-host-common.sh
source "$LIB_DIR/uwe-host-common.sh"
# shellcheck source=lib/uwe-host-preflight.sh
source "$LIB_DIR/uwe-host-preflight.sh"
# shellcheck source=lib/uwe-host-deps.sh
source "$LIB_DIR/uwe-host-deps.sh"
# shellcheck source=lib/uwe-host-ai-diagnostics.sh
source "$LIB_DIR/uwe-host-ai-diagnostics.sh"
# shellcheck source=lib/uwe-host-update-install.sh
source "$LIB_DIR/uwe-host-update-install.sh"

MODE="default"

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --quick)
        MODE="quick"
        ;;
      --repair)
        MODE="repair"
        ;;
      --fresh | --wipe-and-reinstall | --reset | --full-reinstall)
        MODE="fresh"
        ;;
      --healthcheck)
        MODE="healthcheck"
        ;;
      -h | --help)
        usage "$0"
        exit 0
        ;;
      *)
        die "Unbekanntes Argument: $1 (siehe --help)"
        ;;
    esac
    shift
  done
}

git_safety_check() {
  if [[ ! -d "$UWE_HOME/.git" ]]; then
    warn "Kein Git-Repository unter $UWE_HOME — überspringe Git-Prüfung."
    return 0
  fi

  log "Git-Status prüfen …"
  local branch dirty
  branch="$(git -C "$UWE_HOME" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
  dirty="$(git -C "$UWE_HOME" status --porcelain 2>/dev/null | wc -l | tr -d ' ')"

  if [[ "$dirty" != "0" ]]; then
    warn "Uncommitted changes in $UWE_HOME (Branch: $branch, $dirty Datei(en))."
    warn "Für reproduzierbare Deployments: git stash oder commit vor dem Update."
  else
    ok "Git-Working-Tree sauber (Branch: $branch)."
  fi
}

migrate_legacy_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    return 0
  fi

  if systemctl list-unit-files "$LEGACY_SYSTEMD_UNIT" >/dev/null 2>&1; then
    if systemctl is-active --quiet "$LEGACY_SYSTEMD_UNIT" 2>/dev/null; then
      log "Stoppe veralteten Dienst $LEGACY_SYSTEMD_UNIT …"
      systemctl stop "$LEGACY_SYSTEMD_UNIT" || true
    fi
    if systemctl is-enabled --quiet "$LEGACY_SYSTEMD_UNIT" 2>/dev/null; then
      log "Deaktiviere veralteten Dienst $LEGACY_SYSTEMD_UNIT …"
      systemctl disable "$LEGACY_SYSTEMD_UNIT" || true
    fi
    if [[ -f "/etc/systemd/system/$LEGACY_SYSTEMD_UNIT" ]]; then
      log "Entferne veraltete Unit-Datei $LEGACY_SYSTEMD_UNIT …"
      rm -f "/etc/systemd/system/$LEGACY_SYSTEMD_UNIT"
      systemctl daemon-reload || true
    fi
  fi
}

ensure_service_user() {
  if id "$SERVICE_USER" >/dev/null 2>&1; then
    ok "Service-User $SERVICE_USER existiert."
    return 0
  fi

  log "Lege Service-User $SERVICE_USER an …"
  useradd --system --home "$UWE_HOME" --shell /usr/sbin/nologin "$SERVICE_USER"
}

ensure_directories() {
  log "Erstelle Verzeichnisse und setze Rechte …"
  install -d -m 750 -o root -g "$SERVICE_GROUP" "$UWE_ENV_DIR"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$UWE_DATA_DIR"/{uploads,exports}
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$UWE_LOG_DIR"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$UWE_BACKUP_DIR"
  install -d -m 750 -o root -g "$SERVICE_GROUP" "$UWE_DIAG_DIR" 2>/dev/null || install -d -m 755 "$UWE_DIAG_DIR"
}

upsert_env_var_if_missing() {
  local key="$1"
  local value="$2"
  local file="$3"

  if grep -q "^${key}=" "$file" 2>/dev/null; then
    return 0
  fi
  printf '%s=%s\n' "$key" "$value" >>"$file"
}

sanitize_env_file_for_systemd() {
  local file="$1"

  if [[ ! -f "$file" ]]; then
    return 0
  fi

  if grep -q '^PATH=' "$file" 2>/dev/null; then
    warn "$file enthält PATH= — entferne Eintrag (systemd setzt PATH explizit)."
    sed -i '/^PATH=/d' "$file"
  fi
}

upsert_env_var() {
  local key="$1"
  local value="$2"
  local file="$3"

  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

create_minimal_env() {
  cat >"$UWE_ENV_FILE" <<EOF
# UWE production environment — generated by setup-uwe-host.sh
# Replace CHANGE_ME secrets before exposing UWE beyond your LAN.
NODE_ENV=production
PORT=${STUDIO_PORT}
HOST=0.0.0.0
HOSTNAME=0.0.0.0
DATABASE_URL=file:${UWE_DATA_DIR}/uwe.db
UWE_HOME=${UWE_HOME}
UWE_ENV=${UWE_ENV_FILE}
UWE_DATA_DIR=${UWE_DATA_DIR}
UWE_UPLOADS_DIR=${UWE_DATA_DIR}/uploads
UWE_EXPORT_DIR=${UWE_DATA_DIR}/exports
UWE_BACKUP_DIR=${UWE_BACKUP_DIR}
UWE_MAIL_DIR=${UWE_DATA_DIR}/mail
UWE_BRIEFING_DIR=${UWE_DATA_DIR}/briefings
STUDIO_PORT=${STUDIO_PORT}
PORTAL_PORT=${PORTAL_PORT}
RUN_DB_SEED=false
AUTH_SECRET=CHANGE_ME_generate_with_openssl_rand_base64_32
EOF
}

ensure_secret_var() {
  local key="$1"
  local generator="$2"
  local file="$3"
  local force="${4:-0}"

  local current=""
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    current="$(grep "^${key}=" "$file" | head -n 1 | cut -d= -f2-)"
  fi

  if [[ "$force" -eq 1 ]] || [[ -z "$current" ]] || [[ "$current" == CHANGE_ME* ]]; then
    local value
    value="$(eval "$generator")"
    upsert_env_var "$key" "$value" "$file"
    log "Secret $key ergänzt oder erneuert."
  fi
}

ensure_env_file() {
  local force_recreate="${1:-0}"

  if [[ "$force_recreate" -eq 1 ]]; then
    log "Erzeuge $UWE_ENV_FILE neu (--fresh) …"
    create_minimal_env
  elif [[ ! -f "$UWE_ENV_FILE" ]]; then
    log "Erzeuge $UWE_ENV_FILE …"
    if [[ -f "$UWE_HOME/.env.production.example" ]]; then
      install -m 640 -o root -g "$SERVICE_GROUP" "$UWE_HOME/.env.production.example" "$UWE_ENV_FILE"
    elif [[ -f "$UWE_HOME/.env.example" ]]; then
      install -m 640 -o root -g "$SERVICE_GROUP" "$UWE_HOME/.env.example" "$UWE_ENV_FILE"
    else
      create_minimal_env
    fi
  else
    ok "$UWE_ENV_FILE existiert — behalte vorhandene Werte bei."
  fi

  upsert_env_var_if_missing NODE_ENV production "$UWE_ENV_FILE"
  upsert_env_var_if_missing PORT "$STUDIO_PORT" "$UWE_ENV_FILE"
  upsert_env_var_if_missing HOST "0.0.0.0" "$UWE_ENV_FILE"
  upsert_env_var_if_missing HOSTNAME "0.0.0.0" "$UWE_ENV_FILE"
  upsert_env_var_if_missing DATABASE_URL "file:${UWE_DATA_DIR}/uwe.db" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_HOME "$UWE_HOME" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_ENV "$UWE_ENV_FILE" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_DATA_DIR "$UWE_DATA_DIR" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_UPLOADS_DIR "${UWE_DATA_DIR}/uploads" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_EXPORT_DIR "${UWE_DATA_DIR}/exports" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_BACKUP_DIR "$UWE_BACKUP_DIR" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_MAIL_DIR "${UWE_DATA_DIR}/mail" "$UWE_ENV_FILE"
  upsert_env_var_if_missing UWE_BRIEFING_DIR "${UWE_DATA_DIR}/briefings" "$UWE_ENV_FILE"
  upsert_env_var_if_missing STUDIO_PORT "$STUDIO_PORT" "$UWE_ENV_FILE"
  upsert_env_var_if_missing PORTAL_PORT "$PORTAL_PORT" "$UWE_ENV_FILE"
  upsert_env_var_if_missing RUN_DB_SEED false "$UWE_ENV_FILE"

  ensure_secret_var AUTH_SECRET "openssl rand -base64 32" "$UWE_ENV_FILE" "$force_recreate"
  ensure_secret_var UWE_SETUP_TOKEN "openssl rand -hex 32" "$UWE_ENV_FILE" "$force_recreate"
  ensure_secret_var STUDIO_API_TOKEN "openssl rand -base64 32" "$UWE_ENV_FILE" "$force_recreate"

  chown root:"$SERVICE_GROUP" "$UWE_ENV_FILE"
  chmod 640 "$UWE_ENV_FILE"
  chown root:"$SERVICE_GROUP" "$UWE_ENV_DIR"
  chmod 750 "$UWE_ENV_DIR"

  sanitize_env_file_for_systemd "$UWE_ENV_FILE"
}

verify_http_healthchecks() {
  local url code health_body
  log "HTTP-Healthchecks …"

  for url in \
    "http://127.0.0.1:${STUDIO_PORT}/api/health" \
    "http://127.0.0.1:${STUDIO_PORT}/setup" \
    "http://127.0.0.1:${PORTAL_PORT}/api/health"; do
    code="$(http_status_code "$url")"
    if [[ "$code" == "500" || "$code" == "502" || "$code" == "504" ]]; then
      die "HTTP $code für $url — Service nicht gesund. Siehe: journalctl -u $SYSTEMD_UNIT -n 80"
    fi
    if [[ "$code" == "503" ]]; then
      warn "HTTP 503 (degraded) — $url"
    elif [[ "$code" == "000" ]]; then
      warn "HTTP nicht erreichbar: $url"
    else
      ok "HTTP $code — $url"
    fi
  done

  health_body="$(curl -sS --max-time 8 "http://127.0.0.1:${STUDIO_PORT}/api/health" 2>/dev/null || true)"
  if echo "$health_body" | grep -qE '"pendingCount":[1-9][0-9]*'; then
    die "Ausstehende Datenbank-Migrationen nach Neustart — erneut ausführen: sudo bash $UWE_HOME/deploy/scripts/setup-uwe-host.sh --quick"
  fi
  if echo "$health_body" | grep -q '"ok":false' && echo "$health_body" | grep -q '"migrations"'; then
    warn "Migration-Check meldet Probleme — curl http://127.0.0.1:${STUDIO_PORT}/api/health"
  fi
}

ensure_start_script() {
  local start_script="$UWE_HOME/deploy/scripts/start-uwe.sh"
  if [[ ! -f "$start_script" ]]; then
    die "Start-Script fehlt: $start_script"
  fi
  chmod +x "$start_script" "$UWE_HOME/deploy/scripts/uwe-backup.sh" 2>/dev/null || true
}

write_systemd_unit() {
  local unit_path="/etc/systemd/system/$SYSTEMD_UNIT"
  local node_bin
  node_bin="$(find_node_binary)"
  if [[ -z "$node_bin" || ! -x "$node_bin" ]]; then
    node_bin="/usr/bin/node"
  fi

  log "Schreibe systemd Unit nach $unit_path …"

  cat >"$unit_path" <<EOF
[Unit]
Description=UWE — Universeller Welten-Editor (Studio + Portal)
Documentation=file://${UWE_HOME}/docs/UWE_HOST_LINUX_STARTUP.md
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${UWE_HOME}
Environment=UWE_HOME=${UWE_HOME}
Environment=UWE_ENV=${UWE_ENV_FILE}
Environment=NODE_ENV=production
Environment=HOST=0.0.0.0
Environment=HOSTNAME=0.0.0.0
Environment=PORT=${STUDIO_PORT}
EnvironmentFile=-${UWE_ENV_FILE}
Environment=PATH=${SYSTEMD_PATH}
Environment=NODE_BIN=${node_bin}

ExecStart=${UWE_HOME}/deploy/scripts/start-uwe.sh

Restart=on-failure
RestartSec=5
TimeoutStopSec=30

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${UWE_DATA_DIR} ${UWE_BACKUP_DIR} ${UWE_LOG_DIR}
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictRealtime=true
LockPersonality=true
MemoryDenyWriteExecute=false

StandardOutput=journal
StandardError=journal
SyslogIdentifier=uwe

[Install]
WantedBy=multi-user.target
EOF
}

configure_firewall() {
  if ! command -v ufw >/dev/null 2>&1; then
    return 0
  fi

  if ufw status 2>/dev/null | grep -qi 'Status: active'; then
    log "UFW ist aktiv — erlaube Port ${STUDIO_PORT}/tcp und ${PORTAL_PORT}/tcp …"
    ufw allow "${STUDIO_PORT}/tcp" >/dev/null 2>&1 || ufw allow "${STUDIO_PORT}/tcp"
    ufw allow "${PORTAL_PORT}/tcp" >/dev/null 2>&1 || ufw allow "${PORTAL_PORT}/tcp"
  else
    ok "UFW ist nicht aktiv — überspringe Firewall-Regel."
  fi
}

confirm_fresh_reset() {
  echo ""
  echo "========================================"
  echo " WARNUNG: Destruktiver Reset (--fresh)"
  echo "========================================"
  echo " Dies löscht:"
  echo "   - $UWE_DATA_DIR (Datenbank, Uploads, Exports)"
  echo "   - $UWE_ENV_FILE (Konfiguration und Secrets)"
  echo "   - Build-Artefakte im Repository"
  echo ""
  echo " Vor dem Löschen wird ein Backup nach"
  echo " $UWE_BACKUP_DIR/<timestamp>/ angelegt, soweit möglich."
  echo ""
  echo " Zum Fortfahren eingeben: DELETE-UWE"
  echo " (Abbruch mit Strg+C oder leerer Eingabe)"
  echo "========================================"
  echo -n "Bestätigung: "
  local answer
  read -r answer
  if [[ "$answer" != "DELETE-UWE" ]]; then
    die "Abgebrochen — Bestätigung nicht korrekt."
  fi
}

backup_before_fresh() {
  local timestamp backup_dir
  timestamp="$(date +%Y%m%d-%H%M%S)"
  backup_dir="${UWE_BACKUP_DIR}/${timestamp}-pre-fresh"

  log "Erstelle Backup vor Reset nach $backup_dir …"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_GROUP" "$backup_dir"

  if [[ -f "$UWE_ENV_FILE" ]]; then
    cp -a "$UWE_ENV_FILE" "$backup_dir/uwe.env" 2>/dev/null || warn "Env-Backup fehlgeschlagen."
  fi

  if [[ -d "$UWE_DATA_DIR" ]]; then
    if command -v tar >/dev/null 2>&1; then
      tar -czf "$backup_dir/uwe-data.tar.gz" -C "$(dirname "$UWE_DATA_DIR")" "$(basename "$UWE_DATA_DIR")" 2>/dev/null \
        || warn "Daten-Backup fehlgeschlagen."
    else
      cp -a "$UWE_DATA_DIR" "$backup_dir/data" 2>/dev/null || warn "Daten-Backup fehlgeschlagen."
    fi
  fi

  ok "Backup abgeschlossen: $backup_dir"
}

run_fresh_wipe() {
  log "Stoppe Dienste …"
  systemctl stop "$SYSTEMD_UNIT" >/dev/null 2>&1 || true
  systemctl stop "$LEGACY_SYSTEMD_UNIT" >/dev/null 2>&1 || true

  log "Entferne Produktionsdaten …"
  remove_path_if_present "$UWE_DATA_DIR"
  remove_path_if_present "$UWE_ENV_FILE"
  remove_node_caches_and_workspace_modules
}

healthcheck_item() {
  local label="$1"
  local status="$2"
  local detail="${3:-}"
  if [[ "$status" == "ok" ]]; then
    ok "$label${detail:+ — $detail}"
  elif [[ "$status" == "warn" ]]; then
    warn "$label${detail:+ — $detail}"
  else
    fail "$label${detail:+ — $detail}"
  fi
}

run_healthcheck() {
  local lan_ip node_bin pnpm_bin code
  lan_ip="$(get_lan_ip)"

  echo ""
  echo "========================================"
  echo " UWE Healthcheck (read-only)"
  echo "========================================"
  echo ""

  export_system_path
  node_bin="$(find_node_binary)"
  if [[ -n "$node_bin" ]] && node_version_ok "$node_bin"; then
    healthcheck_item "node" ok "$("$node_bin" --version) $node_bin"
  else
    healthcheck_item "node" fail "${node_bin:-missing}"
  fi

  if command -v npm >/dev/null 2>&1; then
    healthcheck_item "npm" ok "$(npm --version)"
  else
    healthcheck_item "npm" fail "missing"
  fi

  pnpm_bin="$(find_pnpm_binary)"
  if [[ -n "$pnpm_bin" ]]; then
    healthcheck_item "pnpm" ok "$("$pnpm_bin" --version) $pnpm_bin"
  else
    healthcheck_item "pnpm" fail "missing"
  fi

  if systemctl is-active --quiet "$SYSTEMD_UNIT" 2>/dev/null; then
    healthcheck_item "systemd uwe.service" ok "active"
  else
    healthcheck_item "systemd uwe.service" fail "$(systemctl is-active "$SYSTEMD_UNIT" 2>/dev/null || echo inactive)"
  fi

  if ss -ltnp 2>/dev/null | grep -q ":${STUDIO_PORT}\b"; then
    healthcheck_item "Port ${STUDIO_PORT}" ok "listening"
  else
    healthcheck_item "Port ${STUDIO_PORT}" fail "not listening"
  fi

  if ss -ltnp 2>/dev/null | grep -q ":${PORTAL_PORT}\b"; then
    healthcheck_item "Port ${PORTAL_PORT}" ok "listening"
  else
    healthcheck_item "Port ${PORTAL_PORT}" fail "not listening"
  fi

  for url in \
    "http://127.0.0.1:${STUDIO_PORT}/api/health" \
    "http://127.0.0.1:${STUDIO_PORT}/setup" \
    "http://127.0.0.1:${PORTAL_PORT}/api/health"; do
    code="$(http_status_code "$url")"
    if [[ "$code" =~ ^[23] ]]; then
      healthcheck_item "HTTP $url" ok "$code"
    elif [[ "$code" =~ ^5 ]]; then
      healthcheck_item "HTTP $url" fail "HTTP $code"
    else
      healthcheck_item "HTTP $url" warn "HTTP $code"
    fi
  done

  if [[ -x "$UWE_HOME/deploy/scripts/check-cloudflare-tunnel.sh" ]]; then
    if bash "$UWE_HOME/deploy/scripts/check-cloudflare-tunnel.sh"; then
      healthcheck_item "Cloudflare Tunnel" ok "checks passed"
    else
      healthcheck_item "Cloudflare Tunnel" warn "see messages above"
    fi
  elif [[ -f "$UWE_HOME/deploy/scripts/check-cloudflare-tunnel.sh" ]]; then
    healthcheck_item "Cloudflare Tunnel" warn "check script not executable"
  fi

  if [[ -f "$UWE_HOME/scripts/check-standalone-prisma-deps.mjs" ]] && id "$SERVICE_USER" >/dev/null 2>&1; then
    for app in studio portal; do
      if [[ -d "$UWE_HOME/apps/$app/.next/standalone" ]]; then
        if run_as_uwe "node '$UWE_HOME/scripts/check-standalone-prisma-deps.mjs' '$app'" >/dev/null 2>&1; then
          healthcheck_item "Standalone Prisma ($app)" ok "modules resolve"
        else
          healthcheck_item "Standalone Prisma ($app)" fail "missing modules"
        fi
      else
        healthcheck_item "Standalone Prisma ($app)" warn "standalone output missing"
      fi
    done
  fi

  echo ""
  echo "LAN Setup-URL: http://${lan_ip}:${STUDIO_PORT}/setup"
  echo "LAN Studio:    http://${lan_ip}:${STUDIO_PORT}/"
  echo "LAN Portal:    http://${lan_ip}:${PORTAL_PORT}/"
  echo "========================================"
}

print_diagnostics() {
  echo ""
  log "Diagnose"
  echo ""
  systemctl status "$SYSTEMD_UNIT" --no-pager || true
  echo ""
  ss -tulpn | grep -E ":${STUDIO_PORT}|:${PORTAL_PORT}" || warn "Kein Prozess lauscht auf Port ${STUDIO_PORT}/${PORTAL_PORT}."
  echo ""
  log "HTTP-Test"
  curl -i --max-time 8 "http://127.0.0.1:${STUDIO_PORT}/api/health" 2>/dev/null | head -n 20 || \
    warn "HTTP-Test fehlgeschlagen — siehe journalctl -u ${SYSTEMD_UNIT} -n 50"
}

check_reachability() {
  local urls=(
    "http://127.0.0.1:${STUDIO_PORT}/"
    "http://127.0.0.1:${STUDIO_PORT}/api/health"
  )
  local url
  for url in "${urls[@]}"; do
    if http_reachable "$url"; then
      printf '%s\n' "$url"
      return 0
    fi
  done
  return 1
}

print_summary() {
  local active="nein"
  local bind_mode="unbekannt"
  local lan_ip reachable_url

  if service_active; then
    active="ja"
  fi

  if ss -tulpn 2>/dev/null | grep -E ":${STUDIO_PORT}\b" | grep -q '127.0.0.1'; then
    if listening_on_all_interfaces "$STUDIO_PORT"; then
      bind_mode="0.0.0.0:${STUDIO_PORT}"
    else
      bind_mode="nur 127.0.0.1:${STUDIO_PORT} — LAN-Zugriff blockiert!"
    fi
  elif listening_on_all_interfaces "$STUDIO_PORT"; then
    bind_mode="0.0.0.0:${STUDIO_PORT}"
  elif ss -tulpn 2>/dev/null | grep -q ":${STUDIO_PORT}"; then
    bind_mode="Port ${STUDIO_PORT} (Adresse prüfen)"
  else
    bind_mode="Port ${STUDIO_PORT} nicht aktiv"
  fi

  lan_ip="$(get_lan_ip)"
  reachable_url="nicht erreichbar"
  if url="$(check_reachability)"; then
    reachable_url="$url"
  fi

  echo ""
  echo "========================================"
  echo " UWE Host Setup — Zusammenfassung"
  echo "========================================"
  echo " Modus:               $MODE"
  echo " Service aktiv:       $active"
  echo " Lauscht auf:         $bind_mode"
  echo " HTTP erreichbar:     $reachable_url"
  echo " Lokale Studio-URL:   http://127.0.0.1:${STUDIO_PORT}/"
  echo " LAN Studio-URL:      http://${lan_ip}:${STUDIO_PORT}/"
  echo " Setup (lokal):       http://127.0.0.1:${STUDIO_PORT}/setup"
  echo " Setup (LAN):         http://${lan_ip}:${STUDIO_PORT}/setup"
  echo " Portal (LAN):        http://${lan_ip}:${PORTAL_PORT}/"
  echo " Env-Datei:           $UWE_ENV_FILE"
  echo " Repository:          $UWE_HOME"
  echo " Node.js:             $(node -v 2>/dev/null || echo unbekannt)"
  echo " pnpm:                $(pnpm -v 2>/dev/null || echo unbekannt)"
  echo ""
  echo " Nächste Schritte:"
  echo "  1. Erstes Setup: http://${lan_ip}:${STUDIO_PORT}/setup"
  echo "  2. Healthcheck:  sudo bash $0 --healthcheck"
  echo "  3. Quick-Update: sudo bash $0 --quick"
  echo "========================================"
}

start_or_restart_service() {
  log "systemd neu laden und Service starten …"
  systemctl daemon-reload
  systemctl enable "$SYSTEMD_UNIT"
  systemctl reset-failed "$SYSTEMD_UNIT" 2>/dev/null || true
  systemctl restart "$SYSTEMD_UNIT"
}

handle_setup_failure() {
  local exit_code=$?
  echo ""
  fail "Setup fehlgeschlagen (exit $exit_code)."
  if declare -F uwe_ai_diagnostics_offer >/dev/null 2>&1; then
    uwe_ai_diagnostics_offer "setup" "Setup script failed with exit code $exit_code"
  fi
  exit "$exit_code"
}

main() {
  parse_args "$@"
  require_root
  UWE_HOME="$(detect_uwe_home "$SCRIPT_DIR")"
  export UWE_HOME

  if [[ "$MODE" == "healthcheck" ]]; then
    run_preflight 1
    run_healthcheck
    exit 0
  fi

  log "UWE Host Setup — Modus: $MODE — Repository: $UWE_HOME"
  run_preflight 0

  trap handle_setup_failure ERR

  migrate_legacy_service

  case "$MODE" in
    fresh)
      confirm_fresh_reset
      backup_before_fresh
      run_fresh_wipe
      reset_system_dependencies
      ;;
    repair)
      reset_system_dependencies
      remove_node_caches_and_workspace_modules
      ;;
    quick)
      if node_needs_install_or_repair; then
        ensure_system_dependencies 1 0
      else
        ensure_system_dependencies 0 0
      fi
      git_safety_check
      ;;
    default)
      ensure_system_dependencies 0 0
      git_safety_check
      ;;
  esac

  ensure_service_user
  ensure_directories

  if [[ "$MODE" == "fresh" ]]; then
    ensure_env_file 1
  else
    ensure_env_file 0
  fi

  chown -R "$SERVICE_USER:$SERVICE_GROUP" "$UWE_HOME"

  local quick_flag=0
  if [[ "$MODE" == "quick" ]]; then
    quick_flag=1
  fi

  stop_uwe_service_for_maintenance
  run_deploy_steps "$quick_flag"
  ensure_start_script
  verify_service_node_access
  write_systemd_unit
  install_host_update_assets
  start_or_restart_service

  sleep 8
  verify_http_healthchecks
  configure_firewall
  sleep 2
  print_diagnostics
  print_summary

  if [[ "$MODE" == "quick" || "$MODE" == "repair" ]]; then
    run_healthcheck
  fi
}

main "$@"
